// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	ent "github.com/datahearth/streamline/ent"
	db "github.com/datahearth/streamline/internal/db"

	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// Approve provides a mock function with given fields: ctx, id, adminID, qualityProfile
func (_m *MockManager) Approve(ctx context.Context, id uint32, adminID uint32, qualityProfile string) (*ent.Request, error) {
	ret := _m.Called(ctx, id, adminID, qualityProfile)

	if len(ret) == 0 {
		panic("no return value specified for Approve")
	}

	var r0 *ent.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, string) (*ent.Request, error)); ok {
		return rf(ctx, id, adminID, qualityProfile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, string) *ent.Request); ok {
		r0 = rf(ctx, id, adminID, qualityProfile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, string) error); ok {
		r1 = rf(ctx, id, adminID, qualityProfile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_Approve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Approve'
type MockManager_Approve_Call struct {
	*mock.Call
}

// Approve is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
//   - adminID uint32
//   - qualityProfile string
func (_e *MockManager_Expecter) Approve(ctx interface{}, id interface{}, adminID interface{}, qualityProfile interface{}) *MockManager_Approve_Call {
	return &MockManager_Approve_Call{Call: _e.mock.On("Approve", ctx, id, adminID, qualityProfile)}
}

func (_c *MockManager_Approve_Call) Run(run func(ctx context.Context, id uint32, adminID uint32, qualityProfile string)) *MockManager_Approve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(string))
	})
	return _c
}

func (_c *MockManager_Approve_Call) Return(_a0 *ent.Request, _a1 error) *MockManager_Approve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_Approve_Call) RunAndReturn(run func(context.Context, uint32, uint32, string) (*ent.Request, error)) *MockManager_Approve_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, mediaType, mediaID, title, requesterID
func (_m *MockManager) Create(ctx context.Context, mediaType string, mediaID uint32, title string, requesterID uint32) (*ent.Request, error) {
	ret := _m.Called(ctx, mediaType, mediaID, title, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *ent.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint32, string, uint32) (*ent.Request, error)); ok {
		return rf(ctx, mediaType, mediaID, title, requesterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint32, string, uint32) *ent.Request); ok {
		r0 = rf(ctx, mediaType, mediaID, title, requesterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint32, string, uint32) error); ok {
		r1 = rf(ctx, mediaType, mediaID, title, requesterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaType string
//   - mediaID uint32
//   - title string
//   - requesterID uint32
func (_e *MockManager_Expecter) Create(ctx interface{}, mediaType interface{}, mediaID interface{}, title interface{}, requesterID interface{}) *MockManager_Create_Call {
	return &MockManager_Create_Call{Call: _e.mock.On("Create", ctx, mediaType, mediaID, title, requesterID)}
}

func (_c *MockManager_Create_Call) Run(run func(ctx context.Context, mediaType string, mediaID uint32, title string, requesterID uint32)) *MockManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint32), args[3].(string), args[4].(uint32))
	})
	return _c
}

func (_c *MockManager_Create_Call) Return(_a0 *ent.Request, _a1 error) *MockManager_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_Create_Call) RunAndReturn(run func(context.Context, string, uint32, string, uint32) (*ent.Request, error)) *MockManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deny provides a mock function with given fields: ctx, id, adminID, reason
func (_m *MockManager) Deny(ctx context.Context, id uint32, adminID uint32, reason string) (*ent.Request, error) {
	ret := _m.Called(ctx, id, adminID, reason)

	if len(ret) == 0 {
		panic("no return value specified for Deny")
	}

	var r0 *ent.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, string) (*ent.Request, error)); ok {
		return rf(ctx, id, adminID, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, string) *ent.Request); ok {
		r0 = rf(ctx, id, adminID, reason)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, string) error); ok {
		r1 = rf(ctx, id, adminID, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_Deny_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deny'
type MockManager_Deny_Call struct {
	*mock.Call
}

// Deny is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
//   - adminID uint32
//   - reason string
func (_e *MockManager_Expecter) Deny(ctx interface{}, id interface{}, adminID interface{}, reason interface{}) *MockManager_Deny_Call {
	return &MockManager_Deny_Call{Call: _e.mock.On("Deny", ctx, id, adminID, reason)}
}

func (_c *MockManager_Deny_Call) Run(run func(ctx context.Context, id uint32, adminID uint32, reason string)) *MockManager_Deny_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(string))
	})
	return _c
}

func (_c *MockManager_Deny_Call) Return(_a0 *ent.Request, _a1 error) *MockManager_Deny_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_Deny_Call) RunAndReturn(run func(context.Context, uint32, uint32, string) (*ent.Request, error)) *MockManager_Deny_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockManager) Get(ctx context.Context, id uint32) (*ent.Request, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *ent.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (*ent.Request, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) *ent.Request); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockManager_Expecter) Get(ctx interface{}, id interface{}) *MockManager_Get_Call {
	return &MockManager_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockManager_Get_Call) Run(run func(ctx context.Context, id uint32)) *MockManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *MockManager_Get_Call) Return(_a0 *ent.Request, _a1 error) *MockManager_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_Get_Call) RunAndReturn(run func(context.Context, uint32) (*ent.Request, error)) *MockManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, p
func (_m *MockManager) List(ctx context.Context, p db.ListRequestsParams) ([]*ent.Request, int, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*ent.Request
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListRequestsParams) ([]*ent.Request, int, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListRequestsParams) []*ent.Request); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListRequestsParams) int); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, db.ListRequestsParams) error); ok {
		r2 = rf(ctx, p)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockManager_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockManager_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - p db.ListRequestsParams
func (_e *MockManager_Expecter) List(ctx interface{}, p interface{}) *MockManager_List_Call {
	return &MockManager_List_Call{Call: _e.mock.On("List", ctx, p)}
}

func (_c *MockManager_List_Call) Run(run func(ctx context.Context, p db.ListRequestsParams)) *MockManager_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListRequestsParams))
	})
	return _c
}

func (_c *MockManager_List_Call) Return(_a0 []*ent.Request, _a1 int, _a2 error) *MockManager_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockManager_List_Call) RunAndReturn(run func(context.Context, db.ListRequestsParams) ([]*ent.Request, int, error)) *MockManager_List_Call {
	_c.Call.Return(run)
	return _c
}

// Reopen provides a mock function with given fields: ctx, id
func (_m *MockManager) Reopen(ctx context.Context, id uint32) (*ent.Request, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Reopen")
	}

	var r0 *ent.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (*ent.Request, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) *ent.Request); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_Reopen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reopen'
type MockManager_Reopen_Call struct {
	*mock.Call
}

// Reopen is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockManager_Expecter) Reopen(ctx interface{}, id interface{}) *MockManager_Reopen_Call {
	return &MockManager_Reopen_Call{Call: _e.mock.On("Reopen", ctx, id)}
}

func (_c *MockManager_Reopen_Call) Run(run func(ctx context.Context, id uint32)) *MockManager_Reopen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *MockManager_Reopen_Call) Return(_a0 *ent.Request, _a1 error) *MockManager_Reopen_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_Reopen_Call) RunAndReturn(run func(context.Context, uint32) (*ent.Request, error)) *MockManager_Reopen_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
