// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBookAdder creates a new instance of MockBookAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookAdder {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBookAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBookAdder is an autogenerated mock type for the BookAdder type
type MockBookAdder struct {
	mock.Mock
}

type MockBookAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookAdder) EXPECT() *MockBookAdder_Expecter {
	return &MockBookAdder_Expecter{mock: &_m.Mock}
}

// AddBook provides a mock function for the type MockBookAdder
func (_mock *MockBookAdder) AddBook(ctx context.Context, hardcoverID uint32, monitor string, qualityProfile string) error {
	ret := _mock.Called(ctx, hardcoverID, monitor, qualityProfile)

	if len(ret) == 0 {
		panic("no return value specified for AddBook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32, string, string) error); ok {
		r0 = returnFunc(ctx, hardcoverID, monitor, qualityProfile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookAdder_AddBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBook'
type MockBookAdder_AddBook_Call struct {
	*mock.Call
}

// AddBook is a helper method to define mock.On call
//   - ctx context.Context
//   - hardcoverID uint32
//   - monitor string
//   - qualityProfile string
func (_e *MockBookAdder_Expecter) AddBook(ctx any, hardcoverID any, monitor any, qualityProfile any) *MockBookAdder_AddBook_Call {
	return &MockBookAdder_AddBook_Call{Call: _e.mock.On("AddBook", ctx, hardcoverID, monitor, qualityProfile)}
}

func (_c *MockBookAdder_AddBook_Call) Run(run func(ctx context.Context, hardcoverID uint32, monitor string, qualityProfile string)) *MockBookAdder_AddBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookAdder_AddBook_Call) Return(err error) *MockBookAdder_AddBook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookAdder_AddBook_Call) RunAndReturn(run func(ctx context.Context, hardcoverID uint32, monitor string, qualityProfile string) error) *MockBookAdder_AddBook_Call {
	_c.Call.Return(run)
	return _c
}

// AddSeries provides a mock function for the type MockBookAdder
func (_mock *MockBookAdder) AddSeries(ctx context.Context, hardcoverID uint32, monitor string, qualityProfile string) error {
	ret := _mock.Called(ctx, hardcoverID, monitor, qualityProfile)

	if len(ret) == 0 {
		panic("no return value specified for AddSeries")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32, string, string) error); ok {
		r0 = returnFunc(ctx, hardcoverID, monitor, qualityProfile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookAdder_AddSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSeries'
type MockBookAdder_AddSeries_Call struct {
	*mock.Call
}

// AddSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - hardcoverID uint32
//   - monitor string
//   - qualityProfile string
func (_e *MockBookAdder_Expecter) AddSeries(ctx any, hardcoverID any, monitor any, qualityProfile any) *MockBookAdder_AddSeries_Call {
	return &MockBookAdder_AddSeries_Call{Call: _e.mock.On("AddSeries", ctx, hardcoverID, monitor, qualityProfile)}
}

func (_c *MockBookAdder_AddSeries_Call) Run(run func(ctx context.Context, hardcoverID uint32, monitor string, qualityProfile string)) *MockBookAdder_AddSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookAdder_AddSeries_Call) Return(err error) *MockBookAdder_AddSeries_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookAdder_AddSeries_Call) RunAndReturn(run func(ctx context.Context, hardcoverID uint32, monitor string, qualityProfile string) error) *MockBookAdder_AddSeries_Call {
	_c.Call.Return(run)
	return _c
}

// HasBook provides a mock function for the type MockBookAdder
func (_mock *MockBookAdder) HasBook(ctx context.Context, hardcoverID uint32) (bool, error) {
	ret := _mock.Called(ctx, hardcoverID)

	if len(ret) == 0 {
		panic("no return value specified for HasBook")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) (bool, error)); ok {
		return returnFunc(ctx, hardcoverID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) bool); ok {
		r0 = returnFunc(ctx, hardcoverID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = returnFunc(ctx, hardcoverID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookAdder_HasBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasBook'
type MockBookAdder_HasBook_Call struct {
	*mock.Call
}

// HasBook is a helper method to define mock.On call
//   - ctx context.Context
//   - hardcoverID uint32
func (_e *MockBookAdder_Expecter) HasBook(ctx any, hardcoverID any) *MockBookAdder_HasBook_Call {
	return &MockBookAdder_HasBook_Call{Call: _e.mock.On("HasBook", ctx, hardcoverID)}
}

func (_c *MockBookAdder_HasBook_Call) Run(run func(ctx context.Context, hardcoverID uint32)) *MockBookAdder_HasBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookAdder_HasBook_Call) Return(b bool, err error) *MockBookAdder_HasBook_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBookAdder_HasBook_Call) RunAndReturn(run func(ctx context.Context, hardcoverID uint32) (bool, error)) *MockBookAdder_HasBook_Call {
	_c.Call.Return(run)
	return _c
}

// HasSeries provides a mock function for the type MockBookAdder
func (_mock *MockBookAdder) HasSeries(ctx context.Context, hardcoverID uint32) (bool, error) {
	ret := _mock.Called(ctx, hardcoverID)

	if len(ret) == 0 {
		panic("no return value specified for HasSeries")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) (bool, error)); ok {
		return returnFunc(ctx, hardcoverID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) bool); ok {
		r0 = returnFunc(ctx, hardcoverID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = returnFunc(ctx, hardcoverID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookAdder_HasSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasSeries'
type MockBookAdder_HasSeries_Call struct {
	*mock.Call
}

// HasSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - hardcoverID uint32
func (_e *MockBookAdder_Expecter) HasSeries(ctx any, hardcoverID any) *MockBookAdder_HasSeries_Call {
	return &MockBookAdder_HasSeries_Call{Call: _e.mock.On("HasSeries", ctx, hardcoverID)}
}

func (_c *MockBookAdder_HasSeries_Call) Run(run func(ctx context.Context, hardcoverID uint32)) *MockBookAdder_HasSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookAdder_HasSeries_Call) Return(b bool, err error) *MockBookAdder_HasSeries_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBookAdder_HasSeries_Call) RunAndReturn(run func(ctx context.Context, hardcoverID uint32) (bool, error)) *MockBookAdder_HasSeries_Call {
	_c.Call.Return(run)
	return _c
}
