// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/datahearth/streamline/internal/metadata"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOverviewProvider creates a new instance of MockOverviewProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOverviewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOverviewProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOverviewProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOverviewProvider is an autogenerated mock type for the OverviewProvider type
type MockOverviewProvider struct {
	mock.Mock
}

type MockOverviewProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOverviewProvider) EXPECT() *MockOverviewProvider_Expecter {
	return &MockOverviewProvider_Expecter{mock: &_m.Mock}
}

// Overviews provides a mock function for the type MockOverviewProvider
func (_mock *MockOverviewProvider) Overviews(ctx context.Context, wikidataID string, langs []string) (map[string]metadata.Overview, error) {
	ret := _mock.Called(ctx, wikidataID, langs)

	if len(ret) == 0 {
		panic("no return value specified for Overviews")
	}

	var r0 map[string]metadata.Overview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (map[string]metadata.Overview, error)); ok {
		return returnFunc(ctx, wikidataID, langs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) map[string]metadata.Overview); ok {
		r0 = returnFunc(ctx, wikidataID, langs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]metadata.Overview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, wikidataID, langs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOverviewProvider_Overviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Overviews'
type MockOverviewProvider_Overviews_Call struct {
	*mock.Call
}

// Overviews is a helper method to define mock.On call
//   - ctx context.Context
//   - wikidataID string
//   - langs []string
func (_e *MockOverviewProvider_Expecter) Overviews(ctx any, wikidataID any, langs any) *MockOverviewProvider_Overviews_Call {
	return &MockOverviewProvider_Overviews_Call{Call: _e.mock.On("Overviews", ctx, wikidataID, langs)}
}

func (_c *MockOverviewProvider_Overviews_Call) Run(run func(ctx context.Context, wikidataID string, langs []string)) *MockOverviewProvider_Overviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOverviewProvider_Overviews_Call) Return(stringToOverview map[string]metadata.Overview, err error) *MockOverviewProvider_Overviews_Call {
	_c.Call.Return(stringToOverview, err)
	return _c
}

func (_c *MockOverviewProvider_Overviews_Call) RunAndReturn(run func(ctx context.Context, wikidataID string, langs []string) (map[string]metadata.Overview, error)) *MockOverviewProvider_Overviews_Call {
	_c.Call.Return(run)
	return _c
}
