// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/datahearth/streamline/internal/metadata"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// FetchDigitalRelease provides a mock function for the type MockProvider
func (_mock *MockProvider) FetchDigitalRelease(ctx context.Context, tmdbID uint32, region string) (*time.Time, error) {
	ret := _mock.Called(ctx, tmdbID, region)

	if len(ret) == 0 {
		panic("no return value specified for FetchDigitalRelease")
	}

	var r0 *time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32, string) (*time.Time, error)); ok {
		return returnFunc(ctx, tmdbID, region)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32, string) *time.Time); ok {
		r0 = returnFunc(ctx, tmdbID, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint32, string) error); ok {
		r1 = returnFunc(ctx, tmdbID, region)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_FetchDigitalRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchDigitalRelease'
type MockProvider_FetchDigitalRelease_Call struct {
	*mock.Call
}

// FetchDigitalRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - tmdbID uint32
//   - region string
func (_e *MockProvider_Expecter) FetchDigitalRelease(ctx any, tmdbID any, region any) *MockProvider_FetchDigitalRelease_Call {
	return &MockProvider_FetchDigitalRelease_Call{Call: _e.mock.On("FetchDigitalRelease", ctx, tmdbID, region)}
}

func (_c *MockProvider_FetchDigitalRelease_Call) Run(run func(ctx context.Context, tmdbID uint32, region string)) *MockProvider_FetchDigitalRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProvider_FetchDigitalRelease_Call) Return(time1 *time.Time, err error) *MockProvider_FetchDigitalRelease_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockProvider_FetchDigitalRelease_Call) RunAndReturn(run func(ctx context.Context, tmdbID uint32, region string) (*time.Time, error)) *MockProvider_FetchDigitalRelease_Call {
	_c.Call.Return(run)
	return _c
}

// GetMovie provides a mock function for the type MockProvider
func (_mock *MockProvider) GetMovie(ctx context.Context, tmdbID uint32) (*metadata.MovieDetails, error) {
	ret := _mock.Called(ctx, tmdbID)

	if len(ret) == 0 {
		panic("no return value specified for GetMovie")
	}

	var r0 *metadata.MovieDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) (*metadata.MovieDetails, error)); ok {
		return returnFunc(ctx, tmdbID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) *metadata.MovieDetails); ok {
		r0 = returnFunc(ctx, tmdbID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata.MovieDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = returnFunc(ctx, tmdbID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_GetMovie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovie'
type MockProvider_GetMovie_Call struct {
	*mock.Call
}

// GetMovie is a helper method to define mock.On call
//   - ctx context.Context
//   - tmdbID uint32
func (_e *MockProvider_Expecter) GetMovie(ctx any, tmdbID any) *MockProvider_GetMovie_Call {
	return &MockProvider_GetMovie_Call{Call: _e.mock.On("GetMovie", ctx, tmdbID)}
}

func (_c *MockProvider_GetMovie_Call) Run(run func(ctx context.Context, tmdbID uint32)) *MockProvider_GetMovie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_GetMovie_Call) Return(movieDetails *metadata.MovieDetails, err error) *MockProvider_GetMovie_Call {
	_c.Call.Return(movieDetails, err)
	return _c
}

func (_c *MockProvider_GetMovie_Call) RunAndReturn(run func(ctx context.Context, tmdbID uint32) (*metadata.MovieDetails, error)) *MockProvider_GetMovie_Call {
	_c.Call.Return(run)
	return _c
}

// Recommendations provides a mock function for the type MockProvider
func (_mock *MockProvider) Recommendations(ctx context.Context, tmdbID uint32) ([]metadata.MovieResult, error) {
	ret := _mock.Called(ctx, tmdbID)

	if len(ret) == 0 {
		panic("no return value specified for Recommendations")
	}

	var r0 []metadata.MovieResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) ([]metadata.MovieResult, error)); ok {
		return returnFunc(ctx, tmdbID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) []metadata.MovieResult); ok {
		r0 = returnFunc(ctx, tmdbID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metadata.MovieResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = returnFunc(ctx, tmdbID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Recommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recommendations'
type MockProvider_Recommendations_Call struct {
	*mock.Call
}

// Recommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - tmdbID uint32
func (_e *MockProvider_Expecter) Recommendations(ctx any, tmdbID any) *MockProvider_Recommendations_Call {
	return &MockProvider_Recommendations_Call{Call: _e.mock.On("Recommendations", ctx, tmdbID)}
}

func (_c *MockProvider_Recommendations_Call) Run(run func(ctx context.Context, tmdbID uint32)) *MockProvider_Recommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_Recommendations_Call) Return(movieResults []metadata.MovieResult, err error) *MockProvider_Recommendations_Call {
	_c.Call.Return(movieResults, err)
	return _c
}

func (_c *MockProvider_Recommendations_Call) RunAndReturn(run func(ctx context.Context, tmdbID uint32) ([]metadata.MovieResult, error)) *MockProvider_Recommendations_Call {
	_c.Call.Return(run)
	return _c
}

// SearchMovie provides a mock function for the type MockProvider
func (_mock *MockProvider) SearchMovie(ctx context.Context, query string, year uint16) ([]metadata.MovieResult, error) {
	ret := _mock.Called(ctx, query, year)

	if len(ret) == 0 {
		panic("no return value specified for SearchMovie")
	}

	var r0 []metadata.MovieResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint16) ([]metadata.MovieResult, error)); ok {
		return returnFunc(ctx, query, year)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint16) []metadata.MovieResult); ok {
		r0 = returnFunc(ctx, query, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metadata.MovieResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint16) error); ok {
		r1 = returnFunc(ctx, query, year)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_SearchMovie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMovie'
type MockProvider_SearchMovie_Call struct {
	*mock.Call
}

// SearchMovie is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - year uint16
func (_e *MockProvider_Expecter) SearchMovie(ctx any, query any, year any) *MockProvider_SearchMovie_Call {
	return &MockProvider_SearchMovie_Call{Call: _e.mock.On("SearchMovie", ctx, query, year)}
}

func (_c *MockProvider_SearchMovie_Call) Run(run func(ctx context.Context, query string, year uint16)) *MockProvider_SearchMovie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint16
		if args[2] != nil {
			arg2 = args[2].(uint16)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProvider_SearchMovie_Call) Return(movieResults []metadata.MovieResult, err error) *MockProvider_SearchMovie_Call {
	_c.Call.Return(movieResults, err)
	return _c
}

func (_c *MockProvider_SearchMovie_Call) RunAndReturn(run func(ctx context.Context, query string, year uint16) ([]metadata.MovieResult, error)) *MockProvider_SearchMovie_Call {
	_c.Call.Return(run)
	return _c
}
