with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}.go"
outpkg: mocks
dir: "{{.InterfaceDir}}/mocks"
all: false
packages:
  github.com/datahearth/streamline/internal/metadata:
    interfaces:
      Provider:
      TVProvider:
  github.com/datahearth/streamline/internal/posters:
    interfaces:
      Manager:
  github.com/datahearth/streamline/internal/media/movie:
    interfaces:
      MetadataRefresher:
      Manager:
  github.com/datahearth/streamline/internal/media/tvshow:
    interfaces:
      Manager:
  github.com/datahearth/streamline/internal/indexer:
    interfaces:
      Client:
      Manager:
  github.com/datahearth/streamline/internal/download:
    interfaces:
      Client:
      Checker:
      Downloader:
      Cleaner:
      Adopter:
  github.com/datahearth/streamline/internal/mediaserver:
    interfaces:
      Server:
      Manager:
  github.com/datahearth/streamline/internal/rss:
    interfaces:
      IndexerSearcher:
      IndexerFeeder:
      Downloader:
      MissingSearchRunner:
      FeedRunner:
      TVIndexerSearcher:
      EpisodeGrabber:
  github.com/datahearth/streamline/internal/db:
    interfaces:
      Store:
      Tx:
  github.com/datahearth/streamline/internal/auth:
    interfaces:
      SessionPurger:
      Manager:
  github.com/datahearth/streamline/internal/server/middleware:
    interfaces:
      Authenticator:
  github.com/datahearth/streamline/internal/importer:
    interfaces:
      MediaServerDispatcher:
      Enqueuer:
  github.com/datahearth/streamline/internal/scheduler:
    interfaces:
      Controller:
  github.com/datahearth/streamline/internal/library/bulkimport:
    interfaces:
      Manager:
  github.com/datahearth/streamline/internal/library:
    interfaces:
      Importer:
  github.com/datahearth/streamline/internal/request:
    interfaces:
      Manager:
      MovieAdder:
      ShowAdder:
  github.com/datahearth/streamline/internal/bittorrent:
    interfaces:
      Manager:
