// Code generated by ent, DO NOT EDIT.

package importscanbook

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/datahearth/streamline/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldUpdateTime, v))
}

// ParsedTitle applies equality check predicate on the "parsed_title" field. It's identical to ParsedTitleEQ.
func ParsedTitle(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldParsedTitle, v))
}

// ParsedAuthor applies equality check predicate on the "parsed_author" field. It's identical to ParsedAuthorEQ.
func ParsedAuthor(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldParsedAuthor, v))
}

// ParsedIsbn applies equality check predicate on the "parsed_isbn" field. It's identical to ParsedIsbnEQ.
func ParsedIsbn(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldParsedIsbn, v))
}

// BookHardcoverID applies equality check predicate on the "book_hardcover_id" field. It's identical to BookHardcoverIDEQ.
func BookHardcoverID(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldBookHardcoverID, v))
}

// AuthorHardcoverID applies equality check predicate on the "author_hardcover_id" field. It's identical to AuthorHardcoverIDEQ.
func AuthorHardcoverID(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldAuthorHardcoverID, v))
}

// ExistingBookID applies equality check predicate on the "existing_book_id" field. It's identical to ExistingBookIDEQ.
func ExistingBookID(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldExistingBookID, v))
}

// DecisionBookHardcoverID applies equality check predicate on the "decision_book_hardcover_id" field. It's identical to DecisionBookHardcoverIDEQ.
func DecisionBookHardcoverID(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldDecisionBookHardcoverID, v))
}

// OutcomeMessage applies equality check predicate on the "outcome_message" field. It's identical to OutcomeMessageEQ.
func OutcomeMessage(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldOutcomeMessage, v))
}

// CreatedBookID applies equality check predicate on the "created_book_id" field. It's identical to CreatedBookIDEQ.
func CreatedBookID(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldCreatedBookID, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLTE(FieldUpdateTime, v))
}

// SlotEQ applies the EQ predicate on the "slot" field.
func SlotEQ(v Slot) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldSlot, v))
}

// SlotNEQ applies the NEQ predicate on the "slot" field.
func SlotNEQ(v Slot) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldSlot, v))
}

// SlotIn applies the In predicate on the "slot" field.
func SlotIn(vs ...Slot) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldSlot, vs...))
}

// SlotNotIn applies the NotIn predicate on the "slot" field.
func SlotNotIn(vs ...Slot) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldSlot, vs...))
}

// ParsedTitleEQ applies the EQ predicate on the "parsed_title" field.
func ParsedTitleEQ(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldParsedTitle, v))
}

// ParsedTitleNEQ applies the NEQ predicate on the "parsed_title" field.
func ParsedTitleNEQ(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldParsedTitle, v))
}

// ParsedTitleIn applies the In predicate on the "parsed_title" field.
func ParsedTitleIn(vs ...string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldParsedTitle, vs...))
}

// ParsedTitleNotIn applies the NotIn predicate on the "parsed_title" field.
func ParsedTitleNotIn(vs ...string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldParsedTitle, vs...))
}

// ParsedTitleGT applies the GT predicate on the "parsed_title" field.
func ParsedTitleGT(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGT(FieldParsedTitle, v))
}

// ParsedTitleGTE applies the GTE predicate on the "parsed_title" field.
func ParsedTitleGTE(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGTE(FieldParsedTitle, v))
}

// ParsedTitleLT applies the LT predicate on the "parsed_title" field.
func ParsedTitleLT(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLT(FieldParsedTitle, v))
}

// ParsedTitleLTE applies the LTE predicate on the "parsed_title" field.
func ParsedTitleLTE(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLTE(FieldParsedTitle, v))
}

// ParsedTitleContains applies the Contains predicate on the "parsed_title" field.
func ParsedTitleContains(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldContains(FieldParsedTitle, v))
}

// ParsedTitleHasPrefix applies the HasPrefix predicate on the "parsed_title" field.
func ParsedTitleHasPrefix(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldHasPrefix(FieldParsedTitle, v))
}

// ParsedTitleHasSuffix applies the HasSuffix predicate on the "parsed_title" field.
func ParsedTitleHasSuffix(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldHasSuffix(FieldParsedTitle, v))
}

// ParsedTitleIsNil applies the IsNil predicate on the "parsed_title" field.
func ParsedTitleIsNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIsNull(FieldParsedTitle))
}

// ParsedTitleNotNil applies the NotNil predicate on the "parsed_title" field.
func ParsedTitleNotNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotNull(FieldParsedTitle))
}

// ParsedTitleEqualFold applies the EqualFold predicate on the "parsed_title" field.
func ParsedTitleEqualFold(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEqualFold(FieldParsedTitle, v))
}

// ParsedTitleContainsFold applies the ContainsFold predicate on the "parsed_title" field.
func ParsedTitleContainsFold(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldContainsFold(FieldParsedTitle, v))
}

// ParsedAuthorEQ applies the EQ predicate on the "parsed_author" field.
func ParsedAuthorEQ(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldParsedAuthor, v))
}

// ParsedAuthorNEQ applies the NEQ predicate on the "parsed_author" field.
func ParsedAuthorNEQ(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldParsedAuthor, v))
}

// ParsedAuthorIn applies the In predicate on the "parsed_author" field.
func ParsedAuthorIn(vs ...string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldParsedAuthor, vs...))
}

// ParsedAuthorNotIn applies the NotIn predicate on the "parsed_author" field.
func ParsedAuthorNotIn(vs ...string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldParsedAuthor, vs...))
}

// ParsedAuthorGT applies the GT predicate on the "parsed_author" field.
func ParsedAuthorGT(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGT(FieldParsedAuthor, v))
}

// ParsedAuthorGTE applies the GTE predicate on the "parsed_author" field.
func ParsedAuthorGTE(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGTE(FieldParsedAuthor, v))
}

// ParsedAuthorLT applies the LT predicate on the "parsed_author" field.
func ParsedAuthorLT(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLT(FieldParsedAuthor, v))
}

// ParsedAuthorLTE applies the LTE predicate on the "parsed_author" field.
func ParsedAuthorLTE(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLTE(FieldParsedAuthor, v))
}

// ParsedAuthorContains applies the Contains predicate on the "parsed_author" field.
func ParsedAuthorContains(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldContains(FieldParsedAuthor, v))
}

// ParsedAuthorHasPrefix applies the HasPrefix predicate on the "parsed_author" field.
func ParsedAuthorHasPrefix(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldHasPrefix(FieldParsedAuthor, v))
}

// ParsedAuthorHasSuffix applies the HasSuffix predicate on the "parsed_author" field.
func ParsedAuthorHasSuffix(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldHasSuffix(FieldParsedAuthor, v))
}

// ParsedAuthorIsNil applies the IsNil predicate on the "parsed_author" field.
func ParsedAuthorIsNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIsNull(FieldParsedAuthor))
}

// ParsedAuthorNotNil applies the NotNil predicate on the "parsed_author" field.
func ParsedAuthorNotNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotNull(FieldParsedAuthor))
}

// ParsedAuthorEqualFold applies the EqualFold predicate on the "parsed_author" field.
func ParsedAuthorEqualFold(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEqualFold(FieldParsedAuthor, v))
}

// ParsedAuthorContainsFold applies the ContainsFold predicate on the "parsed_author" field.
func ParsedAuthorContainsFold(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldContainsFold(FieldParsedAuthor, v))
}

// ParsedIsbnEQ applies the EQ predicate on the "parsed_isbn" field.
func ParsedIsbnEQ(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldParsedIsbn, v))
}

// ParsedIsbnNEQ applies the NEQ predicate on the "parsed_isbn" field.
func ParsedIsbnNEQ(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldParsedIsbn, v))
}

// ParsedIsbnIn applies the In predicate on the "parsed_isbn" field.
func ParsedIsbnIn(vs ...string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldParsedIsbn, vs...))
}

// ParsedIsbnNotIn applies the NotIn predicate on the "parsed_isbn" field.
func ParsedIsbnNotIn(vs ...string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldParsedIsbn, vs...))
}

// ParsedIsbnGT applies the GT predicate on the "parsed_isbn" field.
func ParsedIsbnGT(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGT(FieldParsedIsbn, v))
}

// ParsedIsbnGTE applies the GTE predicate on the "parsed_isbn" field.
func ParsedIsbnGTE(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGTE(FieldParsedIsbn, v))
}

// ParsedIsbnLT applies the LT predicate on the "parsed_isbn" field.
func ParsedIsbnLT(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLT(FieldParsedIsbn, v))
}

// ParsedIsbnLTE applies the LTE predicate on the "parsed_isbn" field.
func ParsedIsbnLTE(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLTE(FieldParsedIsbn, v))
}

// ParsedIsbnContains applies the Contains predicate on the "parsed_isbn" field.
func ParsedIsbnContains(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldContains(FieldParsedIsbn, v))
}

// ParsedIsbnHasPrefix applies the HasPrefix predicate on the "parsed_isbn" field.
func ParsedIsbnHasPrefix(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldHasPrefix(FieldParsedIsbn, v))
}

// ParsedIsbnHasSuffix applies the HasSuffix predicate on the "parsed_isbn" field.
func ParsedIsbnHasSuffix(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldHasSuffix(FieldParsedIsbn, v))
}

// ParsedIsbnIsNil applies the IsNil predicate on the "parsed_isbn" field.
func ParsedIsbnIsNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIsNull(FieldParsedIsbn))
}

// ParsedIsbnNotNil applies the NotNil predicate on the "parsed_isbn" field.
func ParsedIsbnNotNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotNull(FieldParsedIsbn))
}

// ParsedIsbnEqualFold applies the EqualFold predicate on the "parsed_isbn" field.
func ParsedIsbnEqualFold(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEqualFold(FieldParsedIsbn, v))
}

// ParsedIsbnContainsFold applies the ContainsFold predicate on the "parsed_isbn" field.
func ParsedIsbnContainsFold(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldContainsFold(FieldParsedIsbn, v))
}

// ClassificationEQ applies the EQ predicate on the "classification" field.
func ClassificationEQ(v Classification) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldClassification, v))
}

// ClassificationNEQ applies the NEQ predicate on the "classification" field.
func ClassificationNEQ(v Classification) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldClassification, v))
}

// ClassificationIn applies the In predicate on the "classification" field.
func ClassificationIn(vs ...Classification) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldClassification, vs...))
}

// ClassificationNotIn applies the NotIn predicate on the "classification" field.
func ClassificationNotIn(vs ...Classification) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldClassification, vs...))
}

// BookHardcoverIDEQ applies the EQ predicate on the "book_hardcover_id" field.
func BookHardcoverIDEQ(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldBookHardcoverID, v))
}

// BookHardcoverIDNEQ applies the NEQ predicate on the "book_hardcover_id" field.
func BookHardcoverIDNEQ(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldBookHardcoverID, v))
}

// BookHardcoverIDIn applies the In predicate on the "book_hardcover_id" field.
func BookHardcoverIDIn(vs ...uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldBookHardcoverID, vs...))
}

// BookHardcoverIDNotIn applies the NotIn predicate on the "book_hardcover_id" field.
func BookHardcoverIDNotIn(vs ...uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldBookHardcoverID, vs...))
}

// BookHardcoverIDGT applies the GT predicate on the "book_hardcover_id" field.
func BookHardcoverIDGT(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGT(FieldBookHardcoverID, v))
}

// BookHardcoverIDGTE applies the GTE predicate on the "book_hardcover_id" field.
func BookHardcoverIDGTE(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGTE(FieldBookHardcoverID, v))
}

// BookHardcoverIDLT applies the LT predicate on the "book_hardcover_id" field.
func BookHardcoverIDLT(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLT(FieldBookHardcoverID, v))
}

// BookHardcoverIDLTE applies the LTE predicate on the "book_hardcover_id" field.
func BookHardcoverIDLTE(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLTE(FieldBookHardcoverID, v))
}

// BookHardcoverIDIsNil applies the IsNil predicate on the "book_hardcover_id" field.
func BookHardcoverIDIsNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIsNull(FieldBookHardcoverID))
}

// BookHardcoverIDNotNil applies the NotNil predicate on the "book_hardcover_id" field.
func BookHardcoverIDNotNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotNull(FieldBookHardcoverID))
}

// AuthorHardcoverIDEQ applies the EQ predicate on the "author_hardcover_id" field.
func AuthorHardcoverIDEQ(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldAuthorHardcoverID, v))
}

// AuthorHardcoverIDNEQ applies the NEQ predicate on the "author_hardcover_id" field.
func AuthorHardcoverIDNEQ(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldAuthorHardcoverID, v))
}

// AuthorHardcoverIDIn applies the In predicate on the "author_hardcover_id" field.
func AuthorHardcoverIDIn(vs ...uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldAuthorHardcoverID, vs...))
}

// AuthorHardcoverIDNotIn applies the NotIn predicate on the "author_hardcover_id" field.
func AuthorHardcoverIDNotIn(vs ...uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldAuthorHardcoverID, vs...))
}

// AuthorHardcoverIDGT applies the GT predicate on the "author_hardcover_id" field.
func AuthorHardcoverIDGT(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGT(FieldAuthorHardcoverID, v))
}

// AuthorHardcoverIDGTE applies the GTE predicate on the "author_hardcover_id" field.
func AuthorHardcoverIDGTE(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGTE(FieldAuthorHardcoverID, v))
}

// AuthorHardcoverIDLT applies the LT predicate on the "author_hardcover_id" field.
func AuthorHardcoverIDLT(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLT(FieldAuthorHardcoverID, v))
}

// AuthorHardcoverIDLTE applies the LTE predicate on the "author_hardcover_id" field.
func AuthorHardcoverIDLTE(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLTE(FieldAuthorHardcoverID, v))
}

// AuthorHardcoverIDIsNil applies the IsNil predicate on the "author_hardcover_id" field.
func AuthorHardcoverIDIsNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIsNull(FieldAuthorHardcoverID))
}

// AuthorHardcoverIDNotNil applies the NotNil predicate on the "author_hardcover_id" field.
func AuthorHardcoverIDNotNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotNull(FieldAuthorHardcoverID))
}

// CandidatesIsNil applies the IsNil predicate on the "candidates" field.
func CandidatesIsNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIsNull(FieldCandidates))
}

// CandidatesNotNil applies the NotNil predicate on the "candidates" field.
func CandidatesNotNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotNull(FieldCandidates))
}

// ExistingBookIDEQ applies the EQ predicate on the "existing_book_id" field.
func ExistingBookIDEQ(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldExistingBookID, v))
}

// ExistingBookIDNEQ applies the NEQ predicate on the "existing_book_id" field.
func ExistingBookIDNEQ(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldExistingBookID, v))
}

// ExistingBookIDIn applies the In predicate on the "existing_book_id" field.
func ExistingBookIDIn(vs ...uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldExistingBookID, vs...))
}

// ExistingBookIDNotIn applies the NotIn predicate on the "existing_book_id" field.
func ExistingBookIDNotIn(vs ...uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldExistingBookID, vs...))
}

// ExistingBookIDGT applies the GT predicate on the "existing_book_id" field.
func ExistingBookIDGT(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGT(FieldExistingBookID, v))
}

// ExistingBookIDGTE applies the GTE predicate on the "existing_book_id" field.
func ExistingBookIDGTE(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGTE(FieldExistingBookID, v))
}

// ExistingBookIDLT applies the LT predicate on the "existing_book_id" field.
func ExistingBookIDLT(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLT(FieldExistingBookID, v))
}

// ExistingBookIDLTE applies the LTE predicate on the "existing_book_id" field.
func ExistingBookIDLTE(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLTE(FieldExistingBookID, v))
}

// ExistingBookIDIsNil applies the IsNil predicate on the "existing_book_id" field.
func ExistingBookIDIsNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIsNull(FieldExistingBookID))
}

// ExistingBookIDNotNil applies the NotNil predicate on the "existing_book_id" field.
func ExistingBookIDNotNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotNull(FieldExistingBookID))
}

// DecisionEQ applies the EQ predicate on the "decision" field.
func DecisionEQ(v Decision) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldDecision, v))
}

// DecisionNEQ applies the NEQ predicate on the "decision" field.
func DecisionNEQ(v Decision) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldDecision, v))
}

// DecisionIn applies the In predicate on the "decision" field.
func DecisionIn(vs ...Decision) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldDecision, vs...))
}

// DecisionNotIn applies the NotIn predicate on the "decision" field.
func DecisionNotIn(vs ...Decision) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldDecision, vs...))
}

// DecisionBookHardcoverIDEQ applies the EQ predicate on the "decision_book_hardcover_id" field.
func DecisionBookHardcoverIDEQ(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldDecisionBookHardcoverID, v))
}

// DecisionBookHardcoverIDNEQ applies the NEQ predicate on the "decision_book_hardcover_id" field.
func DecisionBookHardcoverIDNEQ(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldDecisionBookHardcoverID, v))
}

// DecisionBookHardcoverIDIn applies the In predicate on the "decision_book_hardcover_id" field.
func DecisionBookHardcoverIDIn(vs ...uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldDecisionBookHardcoverID, vs...))
}

// DecisionBookHardcoverIDNotIn applies the NotIn predicate on the "decision_book_hardcover_id" field.
func DecisionBookHardcoverIDNotIn(vs ...uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldDecisionBookHardcoverID, vs...))
}

// DecisionBookHardcoverIDGT applies the GT predicate on the "decision_book_hardcover_id" field.
func DecisionBookHardcoverIDGT(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGT(FieldDecisionBookHardcoverID, v))
}

// DecisionBookHardcoverIDGTE applies the GTE predicate on the "decision_book_hardcover_id" field.
func DecisionBookHardcoverIDGTE(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGTE(FieldDecisionBookHardcoverID, v))
}

// DecisionBookHardcoverIDLT applies the LT predicate on the "decision_book_hardcover_id" field.
func DecisionBookHardcoverIDLT(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLT(FieldDecisionBookHardcoverID, v))
}

// DecisionBookHardcoverIDLTE applies the LTE predicate on the "decision_book_hardcover_id" field.
func DecisionBookHardcoverIDLTE(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLTE(FieldDecisionBookHardcoverID, v))
}

// DecisionBookHardcoverIDIsNil applies the IsNil predicate on the "decision_book_hardcover_id" field.
func DecisionBookHardcoverIDIsNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIsNull(FieldDecisionBookHardcoverID))
}

// DecisionBookHardcoverIDNotNil applies the NotNil predicate on the "decision_book_hardcover_id" field.
func DecisionBookHardcoverIDNotNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotNull(FieldDecisionBookHardcoverID))
}

// OutcomeEQ applies the EQ predicate on the "outcome" field.
func OutcomeEQ(v Outcome) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldOutcome, v))
}

// OutcomeNEQ applies the NEQ predicate on the "outcome" field.
func OutcomeNEQ(v Outcome) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldOutcome, v))
}

// OutcomeIn applies the In predicate on the "outcome" field.
func OutcomeIn(vs ...Outcome) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldOutcome, vs...))
}

// OutcomeNotIn applies the NotIn predicate on the "outcome" field.
func OutcomeNotIn(vs ...Outcome) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldOutcome, vs...))
}

// OutcomeMessageEQ applies the EQ predicate on the "outcome_message" field.
func OutcomeMessageEQ(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldOutcomeMessage, v))
}

// OutcomeMessageNEQ applies the NEQ predicate on the "outcome_message" field.
func OutcomeMessageNEQ(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldOutcomeMessage, v))
}

// OutcomeMessageIn applies the In predicate on the "outcome_message" field.
func OutcomeMessageIn(vs ...string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldOutcomeMessage, vs...))
}

// OutcomeMessageNotIn applies the NotIn predicate on the "outcome_message" field.
func OutcomeMessageNotIn(vs ...string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldOutcomeMessage, vs...))
}

// OutcomeMessageGT applies the GT predicate on the "outcome_message" field.
func OutcomeMessageGT(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGT(FieldOutcomeMessage, v))
}

// OutcomeMessageGTE applies the GTE predicate on the "outcome_message" field.
func OutcomeMessageGTE(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGTE(FieldOutcomeMessage, v))
}

// OutcomeMessageLT applies the LT predicate on the "outcome_message" field.
func OutcomeMessageLT(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLT(FieldOutcomeMessage, v))
}

// OutcomeMessageLTE applies the LTE predicate on the "outcome_message" field.
func OutcomeMessageLTE(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLTE(FieldOutcomeMessage, v))
}

// OutcomeMessageContains applies the Contains predicate on the "outcome_message" field.
func OutcomeMessageContains(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldContains(FieldOutcomeMessage, v))
}

// OutcomeMessageHasPrefix applies the HasPrefix predicate on the "outcome_message" field.
func OutcomeMessageHasPrefix(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldHasPrefix(FieldOutcomeMessage, v))
}

// OutcomeMessageHasSuffix applies the HasSuffix predicate on the "outcome_message" field.
func OutcomeMessageHasSuffix(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldHasSuffix(FieldOutcomeMessage, v))
}

// OutcomeMessageIsNil applies the IsNil predicate on the "outcome_message" field.
func OutcomeMessageIsNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIsNull(FieldOutcomeMessage))
}

// OutcomeMessageNotNil applies the NotNil predicate on the "outcome_message" field.
func OutcomeMessageNotNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotNull(FieldOutcomeMessage))
}

// OutcomeMessageEqualFold applies the EqualFold predicate on the "outcome_message" field.
func OutcomeMessageEqualFold(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEqualFold(FieldOutcomeMessage, v))
}

// OutcomeMessageContainsFold applies the ContainsFold predicate on the "outcome_message" field.
func OutcomeMessageContainsFold(v string) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldContainsFold(FieldOutcomeMessage, v))
}

// CreatedBookIDEQ applies the EQ predicate on the "created_book_id" field.
func CreatedBookIDEQ(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldEQ(FieldCreatedBookID, v))
}

// CreatedBookIDNEQ applies the NEQ predicate on the "created_book_id" field.
func CreatedBookIDNEQ(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNEQ(FieldCreatedBookID, v))
}

// CreatedBookIDIn applies the In predicate on the "created_book_id" field.
func CreatedBookIDIn(vs ...uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIn(FieldCreatedBookID, vs...))
}

// CreatedBookIDNotIn applies the NotIn predicate on the "created_book_id" field.
func CreatedBookIDNotIn(vs ...uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotIn(FieldCreatedBookID, vs...))
}

// CreatedBookIDGT applies the GT predicate on the "created_book_id" field.
func CreatedBookIDGT(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGT(FieldCreatedBookID, v))
}

// CreatedBookIDGTE applies the GTE predicate on the "created_book_id" field.
func CreatedBookIDGTE(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldGTE(FieldCreatedBookID, v))
}

// CreatedBookIDLT applies the LT predicate on the "created_book_id" field.
func CreatedBookIDLT(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLT(FieldCreatedBookID, v))
}

// CreatedBookIDLTE applies the LTE predicate on the "created_book_id" field.
func CreatedBookIDLTE(v uint32) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldLTE(FieldCreatedBookID, v))
}

// CreatedBookIDIsNil applies the IsNil predicate on the "created_book_id" field.
func CreatedBookIDIsNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldIsNull(FieldCreatedBookID))
}

// CreatedBookIDNotNil applies the NotNil predicate on the "created_book_id" field.
func CreatedBookIDNotNil() predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.FieldNotNull(FieldCreatedBookID))
}

// HasScan applies the HasEdge predicate on the "scan" edge.
func HasScan() predicate.ImportScanBook {
	return predicate.ImportScanBook(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ScanTable, ScanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScanWith applies the HasEdge predicate on the "scan" edge with a given conditions (other predicates).
func HasScanWith(preds ...predicate.ImportScan) predicate.ImportScanBook {
	return predicate.ImportScanBook(func(s *sql.Selector) {
		step := newScanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImportScanBook) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImportScanBook) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImportScanBook) predicate.ImportScanBook {
	return predicate.ImportScanBook(sql.NotPredicates(p))
}
