// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/datahearth/streamline/ent"
	"github.com/datahearth/streamline/internal/media/music"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAdder creates a new instance of MockAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdder {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAdder is an autogenerated mock type for the Adder type
type MockAdder struct {
	mock.Mock
}

type MockAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdder) EXPECT() *MockAdder_Expecter {
	return &MockAdder_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockAdder
func (_mock *MockAdder) Add(ctx context.Context, p music.AddParams) (*ent.Artist, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *ent.Artist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, music.AddParams) (*ent.Artist, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, music.AddParams) *ent.Artist); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Artist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, music.AddParams) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdder_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockAdder_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - p music.AddParams
func (_e *MockAdder_Expecter) Add(ctx any, p any) *MockAdder_Add_Call {
	return &MockAdder_Add_Call{Call: _e.mock.On("Add", ctx, p)}
}

func (_c *MockAdder_Add_Call) Run(run func(ctx context.Context, p music.AddParams)) *MockAdder_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 music.AddParams
		if args[1] != nil {
			arg1 = args[1].(music.AddParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdder_Add_Call) Return(artist *ent.Artist, err error) *MockAdder_Add_Call {
	_c.Call.Return(artist, err)
	return _c
}

func (_c *MockAdder_Add_Call) RunAndReturn(run func(ctx context.Context, p music.AddParams) (*ent.Artist, error)) *MockAdder_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockAdder
func (_mock *MockAdder) Get(ctx context.Context, id uint32) (*ent.Artist, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *ent.Artist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) (*ent.Artist, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) *ent.Artist); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Artist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdder_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAdder_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockAdder_Expecter) Get(ctx any, id any) *MockAdder_Get_Call {
	return &MockAdder_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockAdder_Get_Call) Run(run func(ctx context.Context, id uint32)) *MockAdder_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdder_Get_Call) Return(artist *ent.Artist, err error) *MockAdder_Get_Call {
	_c.Call.Return(artist, err)
	return _c
}

func (_c *MockAdder_Get_Call) RunAndReturn(run func(ctx context.Context, id uint32) (*ent.Artist, error)) *MockAdder_Get_Call {
	_c.Call.Return(run)
	return _c
}
