// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/datahearth/streamline/internal/scheduler"
	mock "github.com/stretchr/testify/mock"
)

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

type MockController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockController) EXPECT() *MockController_Expecter {
	return &MockController_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockController
func (_mock *MockController) Get(name string) (scheduler.JobInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 scheduler.JobInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (scheduler.JobInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) scheduler.JobInfo); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(scheduler.JobInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockController_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockController_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
func (_e *MockController_Expecter) Get(name any) *MockController_Get_Call {
	return &MockController_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *MockController_Get_Call) Run(run func(name string)) *MockController_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockController_Get_Call) Return(jobInfo scheduler.JobInfo, err error) *MockController_Get_Call {
	_c.Call.Return(jobInfo, err)
	return _c
}

func (_c *MockController_Get_Call) RunAndReturn(run func(name string) (scheduler.JobInfo, error)) *MockController_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockController
func (_mock *MockController) List() []scheduler.JobInfo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []scheduler.JobInfo
	if returnFunc, ok := ret.Get(0).(func() []scheduler.JobInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]scheduler.JobInfo)
		}
	}
	return r0
}

// MockController_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockController_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockController_Expecter) List() *MockController_List_Call {
	return &MockController_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockController_List_Call) Run(run func()) *MockController_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockController_List_Call) Return(jobInfos []scheduler.JobInfo) *MockController_List_Call {
	_c.Call.Return(jobInfos)
	return _c
}

func (_c *MockController_List_Call) RunAndReturn(run func() []scheduler.JobInfo) *MockController_List_Call {
	_c.Call.Return(run)
	return _c
}

// Pause provides a mock function for the type MockController
func (_mock *MockController) Pause(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Pause")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockController_Pause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pause'
type MockController_Pause_Call struct {
	*mock.Call
}

// Pause is a helper method to define mock.On call
//   - name string
func (_e *MockController_Expecter) Pause(name any) *MockController_Pause_Call {
	return &MockController_Pause_Call{Call: _e.mock.On("Pause", name)}
}

func (_c *MockController_Pause_Call) Run(run func(name string)) *MockController_Pause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockController_Pause_Call) Return(err error) *MockController_Pause_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockController_Pause_Call) RunAndReturn(run func(name string) error) *MockController_Pause_Call {
	_c.Call.Return(run)
	return _c
}

// Reschedule provides a mock function for the type MockController
func (_mock *MockController) Reschedule(name string, interval time.Duration) error {
	ret := _mock.Called(name, interval)

	if len(ret) == 0 {
		panic("no return value specified for Reschedule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Duration) error); ok {
		r0 = returnFunc(name, interval)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockController_Reschedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reschedule'
type MockController_Reschedule_Call struct {
	*mock.Call
}

// Reschedule is a helper method to define mock.On call
//   - name string
//   - interval time.Duration
func (_e *MockController_Expecter) Reschedule(name any, interval any) *MockController_Reschedule_Call {
	return &MockController_Reschedule_Call{Call: _e.mock.On("Reschedule", name, interval)}
}

func (_c *MockController_Reschedule_Call) Run(run func(name string, interval time.Duration)) *MockController_Reschedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockController_Reschedule_Call) Return(err error) *MockController_Reschedule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockController_Reschedule_Call) RunAndReturn(run func(name string, interval time.Duration) error) *MockController_Reschedule_Call {
	_c.Call.Return(run)
	return _c
}

// Resume provides a mock function for the type MockController
func (_mock *MockController) Resume(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockController_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockController_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - name string
func (_e *MockController_Expecter) Resume(name any) *MockController_Resume_Call {
	return &MockController_Resume_Call{Call: _e.mock.On("Resume", name)}
}

func (_c *MockController_Resume_Call) Run(run func(name string)) *MockController_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockController_Resume_Call) Return(err error) *MockController_Resume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockController_Resume_Call) RunAndReturn(run func(name string) error) *MockController_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// RunNow provides a mock function for the type MockController
func (_mock *MockController) RunNow(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for RunNow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockController_RunNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunNow'
type MockController_RunNow_Call struct {
	*mock.Call
}

// RunNow is a helper method to define mock.On call
//   - name string
func (_e *MockController_Expecter) RunNow(name any) *MockController_RunNow_Call {
	return &MockController_RunNow_Call{Call: _e.mock.On("RunNow", name)}
}

func (_c *MockController_RunNow_Call) Run(run func(name string)) *MockController_RunNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockController_RunNow_Call) Return(err error) *MockController_RunNow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockController_RunNow_Call) RunAndReturn(run func(name string) error) *MockController_RunNow_Call {
	_c.Call.Return(run)
	return _c
}
