// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	download "github.com/datahearth/streamline/internal/download"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// AddTorrent provides a mock function with given fields: ctx, src
func (_m *MockClient) AddTorrent(ctx context.Context, src download.TorrentSource) (string, error) {
	ret := _m.Called(ctx, src)

	if len(ret) == 0 {
		panic("no return value specified for AddTorrent")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, download.TorrentSource) (string, error)); ok {
		return rf(ctx, src)
	}
	if rf, ok := ret.Get(0).(func(context.Context, download.TorrentSource) string); ok {
		r0 = rf(ctx, src)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, download.TorrentSource) error); ok {
		r1 = rf(ctx, src)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_AddTorrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTorrent'
type MockClient_AddTorrent_Call struct {
	*mock.Call
}

// AddTorrent is a helper method to define mock.On call
//   - ctx context.Context
//   - src download.TorrentSource
func (_e *MockClient_Expecter) AddTorrent(ctx interface{}, src interface{}) *MockClient_AddTorrent_Call {
	return &MockClient_AddTorrent_Call{Call: _e.mock.On("AddTorrent", ctx, src)}
}

func (_c *MockClient_AddTorrent_Call) Run(run func(ctx context.Context, src download.TorrentSource)) *MockClient_AddTorrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(download.TorrentSource))
	})
	return _c
}

func (_c *MockClient_AddTorrent_Call) Return(_a0 string, _a1 error) *MockClient_AddTorrent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_AddTorrent_Call) RunAndReturn(run func(context.Context, download.TorrentSource) (string, error)) *MockClient_AddTorrent_Call {
	_c.Call.Return(run)
	return _c
}

// GetTorrent provides a mock function with given fields: ctx, hash
func (_m *MockClient) GetTorrent(ctx context.Context, hash string) (*download.Torrent, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetTorrent")
	}

	var r0 *download.Torrent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*download.Torrent, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *download.Torrent); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*download.Torrent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetTorrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTorrent'
type MockClient_GetTorrent_Call struct {
	*mock.Call
}

// GetTorrent is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockClient_Expecter) GetTorrent(ctx interface{}, hash interface{}) *MockClient_GetTorrent_Call {
	return &MockClient_GetTorrent_Call{Call: _e.mock.On("GetTorrent", ctx, hash)}
}

func (_c *MockClient_GetTorrent_Call) Run(run func(ctx context.Context, hash string)) *MockClient_GetTorrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetTorrent_Call) Return(_a0 *download.Torrent, _a1 error) *MockClient_GetTorrent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetTorrent_Call) RunAndReturn(run func(context.Context, string) (*download.Torrent, error)) *MockClient_GetTorrent_Call {
	_c.Call.Return(run)
	return _c
}

// ListTorrents provides a mock function with given fields: ctx
func (_m *MockClient) ListTorrents(ctx context.Context) ([]download.Torrent, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTorrents")
	}

	var r0 []download.Torrent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]download.Torrent, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []download.Torrent); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]download.Torrent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListTorrents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTorrents'
type MockClient_ListTorrents_Call struct {
	*mock.Call
}

// ListTorrents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) ListTorrents(ctx interface{}) *MockClient_ListTorrents_Call {
	return &MockClient_ListTorrents_Call{Call: _e.mock.On("ListTorrents", ctx)}
}

func (_c *MockClient_ListTorrents_Call) Run(run func(ctx context.Context)) *MockClient_ListTorrents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_ListTorrents_Call) Return(_a0 []download.Torrent, _a1 error) *MockClient_ListTorrents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListTorrents_Call) RunAndReturn(run func(context.Context) ([]download.Torrent, error)) *MockClient_ListTorrents_Call {
	_c.Call.Return(run)
	return _c
}

// PauseTorrent provides a mock function with given fields: ctx, hash
func (_m *MockClient) PauseTorrent(ctx context.Context, hash string) error {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for PauseTorrent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_PauseTorrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseTorrent'
type MockClient_PauseTorrent_Call struct {
	*mock.Call
}

// PauseTorrent is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockClient_Expecter) PauseTorrent(ctx interface{}, hash interface{}) *MockClient_PauseTorrent_Call {
	return &MockClient_PauseTorrent_Call{Call: _e.mock.On("PauseTorrent", ctx, hash)}
}

func (_c *MockClient_PauseTorrent_Call) Run(run func(ctx context.Context, hash string)) *MockClient_PauseTorrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_PauseTorrent_Call) Return(_a0 error) *MockClient_PauseTorrent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_PauseTorrent_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_PauseTorrent_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTorrent provides a mock function with given fields: ctx, hash, deleteFiles
func (_m *MockClient) RemoveTorrent(ctx context.Context, hash string, deleteFiles bool) error {
	ret := _m.Called(ctx, hash, deleteFiles)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTorrent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, hash, deleteFiles)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_RemoveTorrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTorrent'
type MockClient_RemoveTorrent_Call struct {
	*mock.Call
}

// RemoveTorrent is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
//   - deleteFiles bool
func (_e *MockClient_Expecter) RemoveTorrent(ctx interface{}, hash interface{}, deleteFiles interface{}) *MockClient_RemoveTorrent_Call {
	return &MockClient_RemoveTorrent_Call{Call: _e.mock.On("RemoveTorrent", ctx, hash, deleteFiles)}
}

func (_c *MockClient_RemoveTorrent_Call) Run(run func(ctx context.Context, hash string, deleteFiles bool)) *MockClient_RemoveTorrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockClient_RemoveTorrent_Call) Return(_a0 error) *MockClient_RemoveTorrent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_RemoveTorrent_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockClient_RemoveTorrent_Call {
	_c.Call.Return(run)
	return _c
}

// ResumeTorrent provides a mock function with given fields: ctx, hash
func (_m *MockClient) ResumeTorrent(ctx context.Context, hash string) error {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for ResumeTorrent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_ResumeTorrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResumeTorrent'
type MockClient_ResumeTorrent_Call struct {
	*mock.Call
}

// ResumeTorrent is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockClient_Expecter) ResumeTorrent(ctx interface{}, hash interface{}) *MockClient_ResumeTorrent_Call {
	return &MockClient_ResumeTorrent_Call{Call: _e.mock.On("ResumeTorrent", ctx, hash)}
}

func (_c *MockClient_ResumeTorrent_Call) Run(run func(ctx context.Context, hash string)) *MockClient_ResumeTorrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_ResumeTorrent_Call) Return(_a0 error) *MockClient_ResumeTorrent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_ResumeTorrent_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_ResumeTorrent_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function with given fields: ctx
func (_m *MockClient) TestConnection(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type MockClient_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) TestConnection(ctx interface{}) *MockClient_TestConnection_Call {
	return &MockClient_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx)}
}

func (_c *MockClient_TestConnection_Call) Run(run func(ctx context.Context)) *MockClient_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_TestConnection_Call) Return(_a0 error) *MockClient_TestConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_TestConnection_Call) RunAndReturn(run func(context.Context) error) *MockClient_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
