// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	indexer "github.com/datahearth/streamline/internal/indexer"
	mock "github.com/stretchr/testify/mock"
)

// MockTVIndexerSearcher is an autogenerated mock type for the TVIndexerSearcher type
type MockTVIndexerSearcher struct {
	mock.Mock
}

type MockTVIndexerSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTVIndexerSearcher) EXPECT() *MockTVIndexerSearcher_Expecter {
	return &MockTVIndexerSearcher_Expecter{mock: &_m.Mock}
}

// SearchEpisode provides a mock function with given fields: ctx, titles, tvdbID, season, episode
func (_m *MockTVIndexerSearcher) SearchEpisode(ctx context.Context, titles []string, tvdbID uint32, season uint16, episode uint16) ([]indexer.SearchResult, error) {
	ret := _m.Called(ctx, titles, tvdbID, season, episode)

	if len(ret) == 0 {
		panic("no return value specified for SearchEpisode")
	}

	var r0 []indexer.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, uint32, uint16, uint16) ([]indexer.SearchResult, error)); ok {
		return rf(ctx, titles, tvdbID, season, episode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, uint32, uint16, uint16) []indexer.SearchResult); ok {
		r0 = rf(ctx, titles, tvdbID, season, episode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]indexer.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, uint32, uint16, uint16) error); ok {
		r1 = rf(ctx, titles, tvdbID, season, episode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTVIndexerSearcher_SearchEpisode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchEpisode'
type MockTVIndexerSearcher_SearchEpisode_Call struct {
	*mock.Call
}

// SearchEpisode is a helper method to define mock.On call
//   - ctx context.Context
//   - titles []string
//   - tvdbID uint32
//   - season uint16
//   - episode uint16
func (_e *MockTVIndexerSearcher_Expecter) SearchEpisode(ctx interface{}, titles interface{}, tvdbID interface{}, season interface{}, episode interface{}) *MockTVIndexerSearcher_SearchEpisode_Call {
	return &MockTVIndexerSearcher_SearchEpisode_Call{Call: _e.mock.On("SearchEpisode", ctx, titles, tvdbID, season, episode)}
}

func (_c *MockTVIndexerSearcher_SearchEpisode_Call) Run(run func(ctx context.Context, titles []string, tvdbID uint32, season uint16, episode uint16)) *MockTVIndexerSearcher_SearchEpisode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(uint32), args[3].(uint16), args[4].(uint16))
	})
	return _c
}

func (_c *MockTVIndexerSearcher_SearchEpisode_Call) Return(_a0 []indexer.SearchResult, _a1 error) *MockTVIndexerSearcher_SearchEpisode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTVIndexerSearcher_SearchEpisode_Call) RunAndReturn(run func(context.Context, []string, uint32, uint16, uint16) ([]indexer.SearchResult, error)) *MockTVIndexerSearcher_SearchEpisode_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSeason provides a mock function with given fields: ctx, titles, tvdbID, season
func (_m *MockTVIndexerSearcher) SearchSeason(ctx context.Context, titles []string, tvdbID uint32, season uint16) ([]indexer.SearchResult, error) {
	ret := _m.Called(ctx, titles, tvdbID, season)

	if len(ret) == 0 {
		panic("no return value specified for SearchSeason")
	}

	var r0 []indexer.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, uint32, uint16) ([]indexer.SearchResult, error)); ok {
		return rf(ctx, titles, tvdbID, season)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, uint32, uint16) []indexer.SearchResult); ok {
		r0 = rf(ctx, titles, tvdbID, season)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]indexer.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, uint32, uint16) error); ok {
		r1 = rf(ctx, titles, tvdbID, season)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTVIndexerSearcher_SearchSeason_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSeason'
type MockTVIndexerSearcher_SearchSeason_Call struct {
	*mock.Call
}

// SearchSeason is a helper method to define mock.On call
//   - ctx context.Context
//   - titles []string
//   - tvdbID uint32
//   - season uint16
func (_e *MockTVIndexerSearcher_Expecter) SearchSeason(ctx interface{}, titles interface{}, tvdbID interface{}, season interface{}) *MockTVIndexerSearcher_SearchSeason_Call {
	return &MockTVIndexerSearcher_SearchSeason_Call{Call: _e.mock.On("SearchSeason", ctx, titles, tvdbID, season)}
}

func (_c *MockTVIndexerSearcher_SearchSeason_Call) Run(run func(ctx context.Context, titles []string, tvdbID uint32, season uint16)) *MockTVIndexerSearcher_SearchSeason_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(uint32), args[3].(uint16))
	})
	return _c
}

func (_c *MockTVIndexerSearcher_SearchSeason_Call) Return(_a0 []indexer.SearchResult, _a1 error) *MockTVIndexerSearcher_SearchSeason_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTVIndexerSearcher_SearchSeason_Call) RunAndReturn(run func(context.Context, []string, uint32, uint16) ([]indexer.SearchResult, error)) *MockTVIndexerSearcher_SearchSeason_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTVIndexerSearcher creates a new instance of MockTVIndexerSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTVIndexerSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTVIndexerSearcher {
	mock := &MockTVIndexerSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
