// Code generated by ent, DO NOT EDIT.

package bookedition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/datahearth/streamline/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldUpdateTime, v))
}

// HardcoverEditionID applies equality check predicate on the "hardcover_edition_id" field. It's identical to HardcoverEditionIDEQ.
func HardcoverEditionID(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldHardcoverEditionID, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldLanguage, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldTitle, v))
}

// Publisher applies equality check predicate on the "publisher" field. It's identical to PublisherEQ.
func Publisher(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldPublisher, v))
}

// Year applies equality check predicate on the "year" field. It's identical to YearEQ.
func Year(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldYear, v))
}

// Original applies equality check predicate on the "original" field. It's identical to OriginalEQ.
func Original(v bool) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldOriginal, v))
}

// Pages applies equality check predicate on the "pages" field. It's identical to PagesEQ.
func Pages(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldPages, v))
}

// DurationSeconds applies equality check predicate on the "duration_seconds" field. It's identical to DurationSecondsEQ.
func DurationSeconds(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldDurationSeconds, v))
}

// Narrator applies equality check predicate on the "narrator" field. It's identical to NarratorEQ.
func Narrator(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldNarrator, v))
}

// Translator applies equality check predicate on the "translator" field. It's identical to TranslatorEQ.
func Translator(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldTranslator, v))
}

// Isbn13 applies equality check predicate on the "isbn_13" field. It's identical to Isbn13EQ.
func Isbn13(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldIsbn13, v))
}

// Asin applies equality check predicate on the "asin" field. It's identical to AsinEQ.
func Asin(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldAsin, v))
}

// Popularity applies equality check predicate on the "popularity" field. It's identical to PopularityEQ.
func Popularity(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldPopularity, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldUpdateTime, v))
}

// HardcoverEditionIDEQ applies the EQ predicate on the "hardcover_edition_id" field.
func HardcoverEditionIDEQ(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldHardcoverEditionID, v))
}

// HardcoverEditionIDNEQ applies the NEQ predicate on the "hardcover_edition_id" field.
func HardcoverEditionIDNEQ(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldHardcoverEditionID, v))
}

// HardcoverEditionIDIn applies the In predicate on the "hardcover_edition_id" field.
func HardcoverEditionIDIn(vs ...uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldHardcoverEditionID, vs...))
}

// HardcoverEditionIDNotIn applies the NotIn predicate on the "hardcover_edition_id" field.
func HardcoverEditionIDNotIn(vs ...uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldHardcoverEditionID, vs...))
}

// HardcoverEditionIDGT applies the GT predicate on the "hardcover_edition_id" field.
func HardcoverEditionIDGT(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldHardcoverEditionID, v))
}

// HardcoverEditionIDGTE applies the GTE predicate on the "hardcover_edition_id" field.
func HardcoverEditionIDGTE(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldHardcoverEditionID, v))
}

// HardcoverEditionIDLT applies the LT predicate on the "hardcover_edition_id" field.
func HardcoverEditionIDLT(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldHardcoverEditionID, v))
}

// HardcoverEditionIDLTE applies the LTE predicate on the "hardcover_edition_id" field.
func HardcoverEditionIDLTE(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldHardcoverEditionID, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContainsFold(FieldLanguage, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContainsFold(FieldTitle, v))
}

// PublisherEQ applies the EQ predicate on the "publisher" field.
func PublisherEQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldPublisher, v))
}

// PublisherNEQ applies the NEQ predicate on the "publisher" field.
func PublisherNEQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldPublisher, v))
}

// PublisherIn applies the In predicate on the "publisher" field.
func PublisherIn(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldPublisher, vs...))
}

// PublisherNotIn applies the NotIn predicate on the "publisher" field.
func PublisherNotIn(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldPublisher, vs...))
}

// PublisherGT applies the GT predicate on the "publisher" field.
func PublisherGT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldPublisher, v))
}

// PublisherGTE applies the GTE predicate on the "publisher" field.
func PublisherGTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldPublisher, v))
}

// PublisherLT applies the LT predicate on the "publisher" field.
func PublisherLT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldPublisher, v))
}

// PublisherLTE applies the LTE predicate on the "publisher" field.
func PublisherLTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldPublisher, v))
}

// PublisherContains applies the Contains predicate on the "publisher" field.
func PublisherContains(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContains(FieldPublisher, v))
}

// PublisherHasPrefix applies the HasPrefix predicate on the "publisher" field.
func PublisherHasPrefix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasPrefix(FieldPublisher, v))
}

// PublisherHasSuffix applies the HasSuffix predicate on the "publisher" field.
func PublisherHasSuffix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasSuffix(FieldPublisher, v))
}

// PublisherEqualFold applies the EqualFold predicate on the "publisher" field.
func PublisherEqualFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEqualFold(FieldPublisher, v))
}

// PublisherContainsFold applies the ContainsFold predicate on the "publisher" field.
func PublisherContainsFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContainsFold(FieldPublisher, v))
}

// YearEQ applies the EQ predicate on the "year" field.
func YearEQ(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldYear, v))
}

// YearNEQ applies the NEQ predicate on the "year" field.
func YearNEQ(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldYear, v))
}

// YearIn applies the In predicate on the "year" field.
func YearIn(vs ...uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldYear, vs...))
}

// YearNotIn applies the NotIn predicate on the "year" field.
func YearNotIn(vs ...uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldYear, vs...))
}

// YearGT applies the GT predicate on the "year" field.
func YearGT(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldYear, v))
}

// YearGTE applies the GTE predicate on the "year" field.
func YearGTE(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldYear, v))
}

// YearLT applies the LT predicate on the "year" field.
func YearLT(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldYear, v))
}

// YearLTE applies the LTE predicate on the "year" field.
func YearLTE(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldYear, v))
}

// FormatEQ applies the EQ predicate on the "format" field.
func FormatEQ(v Format) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldFormat, v))
}

// FormatNEQ applies the NEQ predicate on the "format" field.
func FormatNEQ(v Format) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldFormat, v))
}

// FormatIn applies the In predicate on the "format" field.
func FormatIn(vs ...Format) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldFormat, vs...))
}

// FormatNotIn applies the NotIn predicate on the "format" field.
func FormatNotIn(vs ...Format) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldFormat, vs...))
}

// OriginalEQ applies the EQ predicate on the "original" field.
func OriginalEQ(v bool) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldOriginal, v))
}

// OriginalNEQ applies the NEQ predicate on the "original" field.
func OriginalNEQ(v bool) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldOriginal, v))
}

// PagesEQ applies the EQ predicate on the "pages" field.
func PagesEQ(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldPages, v))
}

// PagesNEQ applies the NEQ predicate on the "pages" field.
func PagesNEQ(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldPages, v))
}

// PagesIn applies the In predicate on the "pages" field.
func PagesIn(vs ...uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldPages, vs...))
}

// PagesNotIn applies the NotIn predicate on the "pages" field.
func PagesNotIn(vs ...uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldPages, vs...))
}

// PagesGT applies the GT predicate on the "pages" field.
func PagesGT(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldPages, v))
}

// PagesGTE applies the GTE predicate on the "pages" field.
func PagesGTE(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldPages, v))
}

// PagesLT applies the LT predicate on the "pages" field.
func PagesLT(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldPages, v))
}

// PagesLTE applies the LTE predicate on the "pages" field.
func PagesLTE(v uint16) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldPages, v))
}

// PagesIsNil applies the IsNil predicate on the "pages" field.
func PagesIsNil() predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIsNull(FieldPages))
}

// PagesNotNil applies the NotNil predicate on the "pages" field.
func PagesNotNil() predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotNull(FieldPages))
}

// DurationSecondsEQ applies the EQ predicate on the "duration_seconds" field.
func DurationSecondsEQ(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldDurationSeconds, v))
}

// DurationSecondsNEQ applies the NEQ predicate on the "duration_seconds" field.
func DurationSecondsNEQ(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldDurationSeconds, v))
}

// DurationSecondsIn applies the In predicate on the "duration_seconds" field.
func DurationSecondsIn(vs ...uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldDurationSeconds, vs...))
}

// DurationSecondsNotIn applies the NotIn predicate on the "duration_seconds" field.
func DurationSecondsNotIn(vs ...uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldDurationSeconds, vs...))
}

// DurationSecondsGT applies the GT predicate on the "duration_seconds" field.
func DurationSecondsGT(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldDurationSeconds, v))
}

// DurationSecondsGTE applies the GTE predicate on the "duration_seconds" field.
func DurationSecondsGTE(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldDurationSeconds, v))
}

// DurationSecondsLT applies the LT predicate on the "duration_seconds" field.
func DurationSecondsLT(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldDurationSeconds, v))
}

// DurationSecondsLTE applies the LTE predicate on the "duration_seconds" field.
func DurationSecondsLTE(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldDurationSeconds, v))
}

// DurationSecondsIsNil applies the IsNil predicate on the "duration_seconds" field.
func DurationSecondsIsNil() predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIsNull(FieldDurationSeconds))
}

// DurationSecondsNotNil applies the NotNil predicate on the "duration_seconds" field.
func DurationSecondsNotNil() predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotNull(FieldDurationSeconds))
}

// NarratorEQ applies the EQ predicate on the "narrator" field.
func NarratorEQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldNarrator, v))
}

// NarratorNEQ applies the NEQ predicate on the "narrator" field.
func NarratorNEQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldNarrator, v))
}

// NarratorIn applies the In predicate on the "narrator" field.
func NarratorIn(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldNarrator, vs...))
}

// NarratorNotIn applies the NotIn predicate on the "narrator" field.
func NarratorNotIn(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldNarrator, vs...))
}

// NarratorGT applies the GT predicate on the "narrator" field.
func NarratorGT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldNarrator, v))
}

// NarratorGTE applies the GTE predicate on the "narrator" field.
func NarratorGTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldNarrator, v))
}

// NarratorLT applies the LT predicate on the "narrator" field.
func NarratorLT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldNarrator, v))
}

// NarratorLTE applies the LTE predicate on the "narrator" field.
func NarratorLTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldNarrator, v))
}

// NarratorContains applies the Contains predicate on the "narrator" field.
func NarratorContains(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContains(FieldNarrator, v))
}

// NarratorHasPrefix applies the HasPrefix predicate on the "narrator" field.
func NarratorHasPrefix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasPrefix(FieldNarrator, v))
}

// NarratorHasSuffix applies the HasSuffix predicate on the "narrator" field.
func NarratorHasSuffix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasSuffix(FieldNarrator, v))
}

// NarratorIsNil applies the IsNil predicate on the "narrator" field.
func NarratorIsNil() predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIsNull(FieldNarrator))
}

// NarratorNotNil applies the NotNil predicate on the "narrator" field.
func NarratorNotNil() predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotNull(FieldNarrator))
}

// NarratorEqualFold applies the EqualFold predicate on the "narrator" field.
func NarratorEqualFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEqualFold(FieldNarrator, v))
}

// NarratorContainsFold applies the ContainsFold predicate on the "narrator" field.
func NarratorContainsFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContainsFold(FieldNarrator, v))
}

// TranslatorEQ applies the EQ predicate on the "translator" field.
func TranslatorEQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldTranslator, v))
}

// TranslatorNEQ applies the NEQ predicate on the "translator" field.
func TranslatorNEQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldTranslator, v))
}

// TranslatorIn applies the In predicate on the "translator" field.
func TranslatorIn(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldTranslator, vs...))
}

// TranslatorNotIn applies the NotIn predicate on the "translator" field.
func TranslatorNotIn(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldTranslator, vs...))
}

// TranslatorGT applies the GT predicate on the "translator" field.
func TranslatorGT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldTranslator, v))
}

// TranslatorGTE applies the GTE predicate on the "translator" field.
func TranslatorGTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldTranslator, v))
}

// TranslatorLT applies the LT predicate on the "translator" field.
func TranslatorLT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldTranslator, v))
}

// TranslatorLTE applies the LTE predicate on the "translator" field.
func TranslatorLTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldTranslator, v))
}

// TranslatorContains applies the Contains predicate on the "translator" field.
func TranslatorContains(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContains(FieldTranslator, v))
}

// TranslatorHasPrefix applies the HasPrefix predicate on the "translator" field.
func TranslatorHasPrefix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasPrefix(FieldTranslator, v))
}

// TranslatorHasSuffix applies the HasSuffix predicate on the "translator" field.
func TranslatorHasSuffix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasSuffix(FieldTranslator, v))
}

// TranslatorIsNil applies the IsNil predicate on the "translator" field.
func TranslatorIsNil() predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIsNull(FieldTranslator))
}

// TranslatorNotNil applies the NotNil predicate on the "translator" field.
func TranslatorNotNil() predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotNull(FieldTranslator))
}

// TranslatorEqualFold applies the EqualFold predicate on the "translator" field.
func TranslatorEqualFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEqualFold(FieldTranslator, v))
}

// TranslatorContainsFold applies the ContainsFold predicate on the "translator" field.
func TranslatorContainsFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContainsFold(FieldTranslator, v))
}

// Isbn13EQ applies the EQ predicate on the "isbn_13" field.
func Isbn13EQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldIsbn13, v))
}

// Isbn13NEQ applies the NEQ predicate on the "isbn_13" field.
func Isbn13NEQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldIsbn13, v))
}

// Isbn13In applies the In predicate on the "isbn_13" field.
func Isbn13In(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldIsbn13, vs...))
}

// Isbn13NotIn applies the NotIn predicate on the "isbn_13" field.
func Isbn13NotIn(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldIsbn13, vs...))
}

// Isbn13GT applies the GT predicate on the "isbn_13" field.
func Isbn13GT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldIsbn13, v))
}

// Isbn13GTE applies the GTE predicate on the "isbn_13" field.
func Isbn13GTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldIsbn13, v))
}

// Isbn13LT applies the LT predicate on the "isbn_13" field.
func Isbn13LT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldIsbn13, v))
}

// Isbn13LTE applies the LTE predicate on the "isbn_13" field.
func Isbn13LTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldIsbn13, v))
}

// Isbn13Contains applies the Contains predicate on the "isbn_13" field.
func Isbn13Contains(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContains(FieldIsbn13, v))
}

// Isbn13HasPrefix applies the HasPrefix predicate on the "isbn_13" field.
func Isbn13HasPrefix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasPrefix(FieldIsbn13, v))
}

// Isbn13HasSuffix applies the HasSuffix predicate on the "isbn_13" field.
func Isbn13HasSuffix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasSuffix(FieldIsbn13, v))
}

// Isbn13IsNil applies the IsNil predicate on the "isbn_13" field.
func Isbn13IsNil() predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIsNull(FieldIsbn13))
}

// Isbn13NotNil applies the NotNil predicate on the "isbn_13" field.
func Isbn13NotNil() predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotNull(FieldIsbn13))
}

// Isbn13EqualFold applies the EqualFold predicate on the "isbn_13" field.
func Isbn13EqualFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEqualFold(FieldIsbn13, v))
}

// Isbn13ContainsFold applies the ContainsFold predicate on the "isbn_13" field.
func Isbn13ContainsFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContainsFold(FieldIsbn13, v))
}

// AsinEQ applies the EQ predicate on the "asin" field.
func AsinEQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldAsin, v))
}

// AsinNEQ applies the NEQ predicate on the "asin" field.
func AsinNEQ(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldAsin, v))
}

// AsinIn applies the In predicate on the "asin" field.
func AsinIn(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldAsin, vs...))
}

// AsinNotIn applies the NotIn predicate on the "asin" field.
func AsinNotIn(vs ...string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldAsin, vs...))
}

// AsinGT applies the GT predicate on the "asin" field.
func AsinGT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldAsin, v))
}

// AsinGTE applies the GTE predicate on the "asin" field.
func AsinGTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldAsin, v))
}

// AsinLT applies the LT predicate on the "asin" field.
func AsinLT(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldAsin, v))
}

// AsinLTE applies the LTE predicate on the "asin" field.
func AsinLTE(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldAsin, v))
}

// AsinContains applies the Contains predicate on the "asin" field.
func AsinContains(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContains(FieldAsin, v))
}

// AsinHasPrefix applies the HasPrefix predicate on the "asin" field.
func AsinHasPrefix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasPrefix(FieldAsin, v))
}

// AsinHasSuffix applies the HasSuffix predicate on the "asin" field.
func AsinHasSuffix(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldHasSuffix(FieldAsin, v))
}

// AsinIsNil applies the IsNil predicate on the "asin" field.
func AsinIsNil() predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIsNull(FieldAsin))
}

// AsinNotNil applies the NotNil predicate on the "asin" field.
func AsinNotNil() predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotNull(FieldAsin))
}

// AsinEqualFold applies the EqualFold predicate on the "asin" field.
func AsinEqualFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEqualFold(FieldAsin, v))
}

// AsinContainsFold applies the ContainsFold predicate on the "asin" field.
func AsinContainsFold(v string) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldContainsFold(FieldAsin, v))
}

// PopularityEQ applies the EQ predicate on the "popularity" field.
func PopularityEQ(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldEQ(FieldPopularity, v))
}

// PopularityNEQ applies the NEQ predicate on the "popularity" field.
func PopularityNEQ(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNEQ(FieldPopularity, v))
}

// PopularityIn applies the In predicate on the "popularity" field.
func PopularityIn(vs ...uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldIn(FieldPopularity, vs...))
}

// PopularityNotIn applies the NotIn predicate on the "popularity" field.
func PopularityNotIn(vs ...uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldNotIn(FieldPopularity, vs...))
}

// PopularityGT applies the GT predicate on the "popularity" field.
func PopularityGT(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGT(FieldPopularity, v))
}

// PopularityGTE applies the GTE predicate on the "popularity" field.
func PopularityGTE(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldGTE(FieldPopularity, v))
}

// PopularityLT applies the LT predicate on the "popularity" field.
func PopularityLT(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLT(FieldPopularity, v))
}

// PopularityLTE applies the LTE predicate on the "popularity" field.
func PopularityLTE(v uint32) predicate.BookEdition {
	return predicate.BookEdition(sql.FieldLTE(FieldPopularity, v))
}

// HasBook applies the HasEdge predicate on the "book" edge.
func HasBook() predicate.BookEdition {
	return predicate.BookEdition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BookTable, BookColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBookWith applies the HasEdge predicate on the "book" edge with a given conditions (other predicates).
func HasBookWith(preds ...predicate.Book) predicate.BookEdition {
	return predicate.BookEdition(func(s *sql.Selector) {
		step := newBookStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BookEdition) predicate.BookEdition {
	return predicate.BookEdition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BookEdition) predicate.BookEdition {
	return predicate.BookEdition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BookEdition) predicate.BookEdition {
	return predicate.BookEdition(sql.NotPredicates(p))
}
