// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datahearth/streamline/ent/album"
	"github.com/datahearth/streamline/ent/artist"
	"github.com/datahearth/streamline/ent/predicate"
)

// ArtistUpdate is the builder for updating Artist entities.
type ArtistUpdate struct {
	config
	hooks     []Hook
	mutation  *ArtistMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ArtistUpdate builder.
func (_u *ArtistUpdate) Where(ps ...predicate.Artist) *ArtistUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ArtistUpdate) SetUpdateTime(v time.Time) *ArtistUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetMbid sets the "mbid" field.
func (_u *ArtistUpdate) SetMbid(v string) *ArtistUpdate {
	_u.mutation.SetMbid(v)
	return _u
}

// SetNillableMbid sets the "mbid" field if the given value is not nil.
func (_u *ArtistUpdate) SetNillableMbid(v *string) *ArtistUpdate {
	if v != nil {
		_u.SetMbid(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ArtistUpdate) SetName(v string) *ArtistUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ArtistUpdate) SetNillableName(v *string) *ArtistUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortName sets the "sort_name" field.
func (_u *ArtistUpdate) SetSortName(v string) *ArtistUpdate {
	_u.mutation.SetSortName(v)
	return _u
}

// SetNillableSortName sets the "sort_name" field if the given value is not nil.
func (_u *ArtistUpdate) SetNillableSortName(v *string) *ArtistUpdate {
	if v != nil {
		_u.SetSortName(*v)
	}
	return _u
}

// ClearSortName clears the value of the "sort_name" field.
func (_u *ArtistUpdate) ClearSortName() *ArtistUpdate {
	_u.mutation.ClearSortName()
	return _u
}

// SetOverview sets the "overview" field.
func (_u *ArtistUpdate) SetOverview(v string) *ArtistUpdate {
	_u.mutation.SetOverview(v)
	return _u
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (_u *ArtistUpdate) SetNillableOverview(v *string) *ArtistUpdate {
	if v != nil {
		_u.SetOverview(*v)
	}
	return _u
}

// ClearOverview clears the value of the "overview" field.
func (_u *ArtistUpdate) ClearOverview() *ArtistUpdate {
	_u.mutation.ClearOverview()
	return _u
}

// SetMonitored sets the "monitored" field.
func (_u *ArtistUpdate) SetMonitored(v bool) *ArtistUpdate {
	_u.mutation.SetMonitored(v)
	return _u
}

// SetNillableMonitored sets the "monitored" field if the given value is not nil.
func (_u *ArtistUpdate) SetNillableMonitored(v *bool) *ArtistUpdate {
	if v != nil {
		_u.SetMonitored(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *ArtistUpdate) SetPath(v string) *ArtistUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ArtistUpdate) SetNillablePath(v *string) *ArtistUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *ArtistUpdate) ClearPath() *ArtistUpdate {
	_u.mutation.ClearPath()
	return _u
}

// SetQualityProfile sets the "quality_profile" field.
func (_u *ArtistUpdate) SetQualityProfile(v string) *ArtistUpdate {
	_u.mutation.SetQualityProfile(v)
	return _u
}

// SetNillableQualityProfile sets the "quality_profile" field if the given value is not nil.
func (_u *ArtistUpdate) SetNillableQualityProfile(v *string) *ArtistUpdate {
	if v != nil {
		_u.SetQualityProfile(*v)
	}
	return _u
}

// ClearQualityProfile clears the value of the "quality_profile" field.
func (_u *ArtistUpdate) ClearQualityProfile() *ArtistUpdate {
	_u.mutation.ClearQualityProfile()
	return _u
}

// SetLastRefreshedAt sets the "last_refreshed_at" field.
func (_u *ArtistUpdate) SetLastRefreshedAt(v time.Time) *ArtistUpdate {
	_u.mutation.SetLastRefreshedAt(v)
	return _u
}

// SetNillableLastRefreshedAt sets the "last_refreshed_at" field if the given value is not nil.
func (_u *ArtistUpdate) SetNillableLastRefreshedAt(v *time.Time) *ArtistUpdate {
	if v != nil {
		_u.SetLastRefreshedAt(*v)
	}
	return _u
}

// ClearLastRefreshedAt clears the value of the "last_refreshed_at" field.
func (_u *ArtistUpdate) ClearLastRefreshedAt() *ArtistUpdate {
	_u.mutation.ClearLastRefreshedAt()
	return _u
}

// AddAlbumIDs adds the "albums" edge to the Album entity by IDs.
func (_u *ArtistUpdate) AddAlbumIDs(ids ...uint32) *ArtistUpdate {
	_u.mutation.AddAlbumIDs(ids...)
	return _u
}

// AddAlbums adds the "albums" edges to the Album entity.
func (_u *ArtistUpdate) AddAlbums(v ...*Album) *ArtistUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlbumIDs(ids...)
}

// Mutation returns the ArtistMutation object of the builder.
func (_u *ArtistUpdate) Mutation() *ArtistMutation {
	return _u.mutation
}

// ClearAlbums clears all "albums" edges to the Album entity.
func (_u *ArtistUpdate) ClearAlbums() *ArtistUpdate {
	_u.mutation.ClearAlbums()
	return _u
}

// RemoveAlbumIDs removes the "albums" edge to Album entities by IDs.
func (_u *ArtistUpdate) RemoveAlbumIDs(ids ...uint32) *ArtistUpdate {
	_u.mutation.RemoveAlbumIDs(ids...)
	return _u
}

// RemoveAlbums removes "albums" edges to Album entities.
func (_u *ArtistUpdate) RemoveAlbums(v ...*Album) *ArtistUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlbumIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArtistUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArtistUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArtistUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArtistUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArtistUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := artist.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArtistUpdate) check() error {
	if v, ok := _u.mutation.Mbid(); ok {
		if err := artist.MbidValidator(v); err != nil {
			return &ValidationError{Name: "mbid", err: fmt.Errorf(`ent: validator failed for field "Artist.mbid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := artist.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Artist.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ArtistUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ArtistUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ArtistUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(artist.Table, artist.Columns, sqlgraph.NewFieldSpec(artist.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(artist.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Mbid(); ok {
		_spec.SetField(artist.FieldMbid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(artist.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortName(); ok {
		_spec.SetField(artist.FieldSortName, field.TypeString, value)
	}
	if _u.mutation.SortNameCleared() {
		_spec.ClearField(artist.FieldSortName, field.TypeString)
	}
	if value, ok := _u.mutation.Overview(); ok {
		_spec.SetField(artist.FieldOverview, field.TypeString, value)
	}
	if _u.mutation.OverviewCleared() {
		_spec.ClearField(artist.FieldOverview, field.TypeString)
	}
	if value, ok := _u.mutation.Monitored(); ok {
		_spec.SetField(artist.FieldMonitored, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(artist.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(artist.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.QualityProfile(); ok {
		_spec.SetField(artist.FieldQualityProfile, field.TypeString, value)
	}
	if _u.mutation.QualityProfileCleared() {
		_spec.ClearField(artist.FieldQualityProfile, field.TypeString)
	}
	if value, ok := _u.mutation.LastRefreshedAt(); ok {
		_spec.SetField(artist.FieldLastRefreshedAt, field.TypeTime, value)
	}
	if _u.mutation.LastRefreshedAtCleared() {
		_spec.ClearField(artist.FieldLastRefreshedAt, field.TypeTime)
	}
	if _u.mutation.AlbumsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   artist.AlbumsTable,
			Columns: []string{artist.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlbumsIDs(); len(nodes) > 0 && !_u.mutation.AlbumsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   artist.AlbumsTable,
			Columns: []string{artist.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlbumsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   artist.AlbumsTable,
			Columns: []string{artist.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{artist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArtistUpdateOne is the builder for updating a single Artist entity.
type ArtistUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ArtistMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *ArtistUpdateOne) SetUpdateTime(v time.Time) *ArtistUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetMbid sets the "mbid" field.
func (_u *ArtistUpdateOne) SetMbid(v string) *ArtistUpdateOne {
	_u.mutation.SetMbid(v)
	return _u
}

// SetNillableMbid sets the "mbid" field if the given value is not nil.
func (_u *ArtistUpdateOne) SetNillableMbid(v *string) *ArtistUpdateOne {
	if v != nil {
		_u.SetMbid(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ArtistUpdateOne) SetName(v string) *ArtistUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ArtistUpdateOne) SetNillableName(v *string) *ArtistUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortName sets the "sort_name" field.
func (_u *ArtistUpdateOne) SetSortName(v string) *ArtistUpdateOne {
	_u.mutation.SetSortName(v)
	return _u
}

// SetNillableSortName sets the "sort_name" field if the given value is not nil.
func (_u *ArtistUpdateOne) SetNillableSortName(v *string) *ArtistUpdateOne {
	if v != nil {
		_u.SetSortName(*v)
	}
	return _u
}

// ClearSortName clears the value of the "sort_name" field.
func (_u *ArtistUpdateOne) ClearSortName() *ArtistUpdateOne {
	_u.mutation.ClearSortName()
	return _u
}

// SetOverview sets the "overview" field.
func (_u *ArtistUpdateOne) SetOverview(v string) *ArtistUpdateOne {
	_u.mutation.SetOverview(v)
	return _u
}

// SetNillableOverview sets the "overview" field if the given value is not nil.
func (_u *ArtistUpdateOne) SetNillableOverview(v *string) *ArtistUpdateOne {
	if v != nil {
		_u.SetOverview(*v)
	}
	return _u
}

// ClearOverview clears the value of the "overview" field.
func (_u *ArtistUpdateOne) ClearOverview() *ArtistUpdateOne {
	_u.mutation.ClearOverview()
	return _u
}

// SetMonitored sets the "monitored" field.
func (_u *ArtistUpdateOne) SetMonitored(v bool) *ArtistUpdateOne {
	_u.mutation.SetMonitored(v)
	return _u
}

// SetNillableMonitored sets the "monitored" field if the given value is not nil.
func (_u *ArtistUpdateOne) SetNillableMonitored(v *bool) *ArtistUpdateOne {
	if v != nil {
		_u.SetMonitored(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *ArtistUpdateOne) SetPath(v string) *ArtistUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ArtistUpdateOne) SetNillablePath(v *string) *ArtistUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *ArtistUpdateOne) ClearPath() *ArtistUpdateOne {
	_u.mutation.ClearPath()
	return _u
}

// SetQualityProfile sets the "quality_profile" field.
func (_u *ArtistUpdateOne) SetQualityProfile(v string) *ArtistUpdateOne {
	_u.mutation.SetQualityProfile(v)
	return _u
}

// SetNillableQualityProfile sets the "quality_profile" field if the given value is not nil.
func (_u *ArtistUpdateOne) SetNillableQualityProfile(v *string) *ArtistUpdateOne {
	if v != nil {
		_u.SetQualityProfile(*v)
	}
	return _u
}

// ClearQualityProfile clears the value of the "quality_profile" field.
func (_u *ArtistUpdateOne) ClearQualityProfile() *ArtistUpdateOne {
	_u.mutation.ClearQualityProfile()
	return _u
}

// SetLastRefreshedAt sets the "last_refreshed_at" field.
func (_u *ArtistUpdateOne) SetLastRefreshedAt(v time.Time) *ArtistUpdateOne {
	_u.mutation.SetLastRefreshedAt(v)
	return _u
}

// SetNillableLastRefreshedAt sets the "last_refreshed_at" field if the given value is not nil.
func (_u *ArtistUpdateOne) SetNillableLastRefreshedAt(v *time.Time) *ArtistUpdateOne {
	if v != nil {
		_u.SetLastRefreshedAt(*v)
	}
	return _u
}

// ClearLastRefreshedAt clears the value of the "last_refreshed_at" field.
func (_u *ArtistUpdateOne) ClearLastRefreshedAt() *ArtistUpdateOne {
	_u.mutation.ClearLastRefreshedAt()
	return _u
}

// AddAlbumIDs adds the "albums" edge to the Album entity by IDs.
func (_u *ArtistUpdateOne) AddAlbumIDs(ids ...uint32) *ArtistUpdateOne {
	_u.mutation.AddAlbumIDs(ids...)
	return _u
}

// AddAlbums adds the "albums" edges to the Album entity.
func (_u *ArtistUpdateOne) AddAlbums(v ...*Album) *ArtistUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlbumIDs(ids...)
}

// Mutation returns the ArtistMutation object of the builder.
func (_u *ArtistUpdateOne) Mutation() *ArtistMutation {
	return _u.mutation
}

// ClearAlbums clears all "albums" edges to the Album entity.
func (_u *ArtistUpdateOne) ClearAlbums() *ArtistUpdateOne {
	_u.mutation.ClearAlbums()
	return _u
}

// RemoveAlbumIDs removes the "albums" edge to Album entities by IDs.
func (_u *ArtistUpdateOne) RemoveAlbumIDs(ids ...uint32) *ArtistUpdateOne {
	_u.mutation.RemoveAlbumIDs(ids...)
	return _u
}

// RemoveAlbums removes "albums" edges to Album entities.
func (_u *ArtistUpdateOne) RemoveAlbums(v ...*Album) *ArtistUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlbumIDs(ids...)
}

// Where appends a list predicates to the ArtistUpdate builder.
func (_u *ArtistUpdateOne) Where(ps ...predicate.Artist) *ArtistUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArtistUpdateOne) Select(field string, fields ...string) *ArtistUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Artist entity.
func (_u *ArtistUpdateOne) Save(ctx context.Context) (*Artist, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArtistUpdateOne) SaveX(ctx context.Context) *Artist {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArtistUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArtistUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArtistUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := artist.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArtistUpdateOne) check() error {
	if v, ok := _u.mutation.Mbid(); ok {
		if err := artist.MbidValidator(v); err != nil {
			return &ValidationError{Name: "mbid", err: fmt.Errorf(`ent: validator failed for field "Artist.mbid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := artist.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Artist.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ArtistUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ArtistUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ArtistUpdateOne) sqlSave(ctx context.Context) (_node *Artist, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(artist.Table, artist.Columns, sqlgraph.NewFieldSpec(artist.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Artist.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, artist.FieldID)
		for _, f := range fields {
			if !artist.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != artist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(artist.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Mbid(); ok {
		_spec.SetField(artist.FieldMbid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(artist.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortName(); ok {
		_spec.SetField(artist.FieldSortName, field.TypeString, value)
	}
	if _u.mutation.SortNameCleared() {
		_spec.ClearField(artist.FieldSortName, field.TypeString)
	}
	if value, ok := _u.mutation.Overview(); ok {
		_spec.SetField(artist.FieldOverview, field.TypeString, value)
	}
	if _u.mutation.OverviewCleared() {
		_spec.ClearField(artist.FieldOverview, field.TypeString)
	}
	if value, ok := _u.mutation.Monitored(); ok {
		_spec.SetField(artist.FieldMonitored, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(artist.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(artist.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.QualityProfile(); ok {
		_spec.SetField(artist.FieldQualityProfile, field.TypeString, value)
	}
	if _u.mutation.QualityProfileCleared() {
		_spec.ClearField(artist.FieldQualityProfile, field.TypeString)
	}
	if value, ok := _u.mutation.LastRefreshedAt(); ok {
		_spec.SetField(artist.FieldLastRefreshedAt, field.TypeTime, value)
	}
	if _u.mutation.LastRefreshedAtCleared() {
		_spec.ClearField(artist.FieldLastRefreshedAt, field.TypeTime)
	}
	if _u.mutation.AlbumsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   artist.AlbumsTable,
			Columns: []string{artist.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlbumsIDs(); len(nodes) > 0 && !_u.mutation.AlbumsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   artist.AlbumsTable,
			Columns: []string{artist.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlbumsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   artist.AlbumsTable,
			Columns: []string{artist.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Artist{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{artist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
