// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datahearth/streamline/ent/book"
	"github.com/datahearth/streamline/ent/bookedition"
	"github.com/datahearth/streamline/ent/predicate"
)

// BookEditionUpdate is the builder for updating BookEdition entities.
type BookEditionUpdate struct {
	config
	hooks     []Hook
	mutation  *BookEditionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BookEditionUpdate builder.
func (_u *BookEditionUpdate) Where(ps ...predicate.BookEdition) *BookEditionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *BookEditionUpdate) SetUpdateTime(v time.Time) *BookEditionUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetHardcoverEditionID sets the "hardcover_edition_id" field.
func (_u *BookEditionUpdate) SetHardcoverEditionID(v uint32) *BookEditionUpdate {
	_u.mutation.ResetHardcoverEditionID()
	_u.mutation.SetHardcoverEditionID(v)
	return _u
}

// SetNillableHardcoverEditionID sets the "hardcover_edition_id" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillableHardcoverEditionID(v *uint32) *BookEditionUpdate {
	if v != nil {
		_u.SetHardcoverEditionID(*v)
	}
	return _u
}

// AddHardcoverEditionID adds value to the "hardcover_edition_id" field.
func (_u *BookEditionUpdate) AddHardcoverEditionID(v int32) *BookEditionUpdate {
	_u.mutation.AddHardcoverEditionID(v)
	return _u
}

// SetLanguage sets the "language" field.
func (_u *BookEditionUpdate) SetLanguage(v string) *BookEditionUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillableLanguage(v *string) *BookEditionUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookEditionUpdate) SetTitle(v string) *BookEditionUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillableTitle(v *string) *BookEditionUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetPublisher sets the "publisher" field.
func (_u *BookEditionUpdate) SetPublisher(v string) *BookEditionUpdate {
	_u.mutation.SetPublisher(v)
	return _u
}

// SetNillablePublisher sets the "publisher" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillablePublisher(v *string) *BookEditionUpdate {
	if v != nil {
		_u.SetPublisher(*v)
	}
	return _u
}

// SetYear sets the "year" field.
func (_u *BookEditionUpdate) SetYear(v uint16) *BookEditionUpdate {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillableYear(v *uint16) *BookEditionUpdate {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *BookEditionUpdate) AddYear(v int16) *BookEditionUpdate {
	_u.mutation.AddYear(v)
	return _u
}

// SetFormat sets the "format" field.
func (_u *BookEditionUpdate) SetFormat(v bookedition.Format) *BookEditionUpdate {
	_u.mutation.SetFormat(v)
	return _u
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillableFormat(v *bookedition.Format) *BookEditionUpdate {
	if v != nil {
		_u.SetFormat(*v)
	}
	return _u
}

// SetOriginal sets the "original" field.
func (_u *BookEditionUpdate) SetOriginal(v bool) *BookEditionUpdate {
	_u.mutation.SetOriginal(v)
	return _u
}

// SetNillableOriginal sets the "original" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillableOriginal(v *bool) *BookEditionUpdate {
	if v != nil {
		_u.SetOriginal(*v)
	}
	return _u
}

// SetPages sets the "pages" field.
func (_u *BookEditionUpdate) SetPages(v uint16) *BookEditionUpdate {
	_u.mutation.ResetPages()
	_u.mutation.SetPages(v)
	return _u
}

// SetNillablePages sets the "pages" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillablePages(v *uint16) *BookEditionUpdate {
	if v != nil {
		_u.SetPages(*v)
	}
	return _u
}

// AddPages adds value to the "pages" field.
func (_u *BookEditionUpdate) AddPages(v int16) *BookEditionUpdate {
	_u.mutation.AddPages(v)
	return _u
}

// ClearPages clears the value of the "pages" field.
func (_u *BookEditionUpdate) ClearPages() *BookEditionUpdate {
	_u.mutation.ClearPages()
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *BookEditionUpdate) SetDurationSeconds(v uint32) *BookEditionUpdate {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillableDurationSeconds(v *uint32) *BookEditionUpdate {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *BookEditionUpdate) AddDurationSeconds(v int32) *BookEditionUpdate {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// ClearDurationSeconds clears the value of the "duration_seconds" field.
func (_u *BookEditionUpdate) ClearDurationSeconds() *BookEditionUpdate {
	_u.mutation.ClearDurationSeconds()
	return _u
}

// SetNarrator sets the "narrator" field.
func (_u *BookEditionUpdate) SetNarrator(v string) *BookEditionUpdate {
	_u.mutation.SetNarrator(v)
	return _u
}

// SetNillableNarrator sets the "narrator" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillableNarrator(v *string) *BookEditionUpdate {
	if v != nil {
		_u.SetNarrator(*v)
	}
	return _u
}

// ClearNarrator clears the value of the "narrator" field.
func (_u *BookEditionUpdate) ClearNarrator() *BookEditionUpdate {
	_u.mutation.ClearNarrator()
	return _u
}

// SetTranslator sets the "translator" field.
func (_u *BookEditionUpdate) SetTranslator(v string) *BookEditionUpdate {
	_u.mutation.SetTranslator(v)
	return _u
}

// SetNillableTranslator sets the "translator" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillableTranslator(v *string) *BookEditionUpdate {
	if v != nil {
		_u.SetTranslator(*v)
	}
	return _u
}

// ClearTranslator clears the value of the "translator" field.
func (_u *BookEditionUpdate) ClearTranslator() *BookEditionUpdate {
	_u.mutation.ClearTranslator()
	return _u
}

// SetIsbn13 sets the "isbn_13" field.
func (_u *BookEditionUpdate) SetIsbn13(v string) *BookEditionUpdate {
	_u.mutation.SetIsbn13(v)
	return _u
}

// SetNillableIsbn13 sets the "isbn_13" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillableIsbn13(v *string) *BookEditionUpdate {
	if v != nil {
		_u.SetIsbn13(*v)
	}
	return _u
}

// ClearIsbn13 clears the value of the "isbn_13" field.
func (_u *BookEditionUpdate) ClearIsbn13() *BookEditionUpdate {
	_u.mutation.ClearIsbn13()
	return _u
}

// SetAsin sets the "asin" field.
func (_u *BookEditionUpdate) SetAsin(v string) *BookEditionUpdate {
	_u.mutation.SetAsin(v)
	return _u
}

// SetNillableAsin sets the "asin" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillableAsin(v *string) *BookEditionUpdate {
	if v != nil {
		_u.SetAsin(*v)
	}
	return _u
}

// ClearAsin clears the value of the "asin" field.
func (_u *BookEditionUpdate) ClearAsin() *BookEditionUpdate {
	_u.mutation.ClearAsin()
	return _u
}

// SetPopularity sets the "popularity" field.
func (_u *BookEditionUpdate) SetPopularity(v uint32) *BookEditionUpdate {
	_u.mutation.ResetPopularity()
	_u.mutation.SetPopularity(v)
	return _u
}

// SetNillablePopularity sets the "popularity" field if the given value is not nil.
func (_u *BookEditionUpdate) SetNillablePopularity(v *uint32) *BookEditionUpdate {
	if v != nil {
		_u.SetPopularity(*v)
	}
	return _u
}

// AddPopularity adds value to the "popularity" field.
func (_u *BookEditionUpdate) AddPopularity(v int32) *BookEditionUpdate {
	_u.mutation.AddPopularity(v)
	return _u
}

// SetBookID sets the "book" edge to the Book entity by ID.
func (_u *BookEditionUpdate) SetBookID(id uint32) *BookEditionUpdate {
	_u.mutation.SetBookID(id)
	return _u
}

// SetBook sets the "book" edge to the Book entity.
func (_u *BookEditionUpdate) SetBook(v *Book) *BookEditionUpdate {
	return _u.SetBookID(v.ID)
}

// Mutation returns the BookEditionMutation object of the builder.
func (_u *BookEditionUpdate) Mutation() *BookEditionMutation {
	return _u.mutation
}

// ClearBook clears the "book" edge to the Book entity.
func (_u *BookEditionUpdate) ClearBook() *BookEditionUpdate {
	_u.mutation.ClearBook()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookEditionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookEditionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookEditionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookEditionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookEditionUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := bookedition.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookEditionUpdate) check() error {
	if v, ok := _u.mutation.Language(); ok {
		if err := bookedition.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "BookEdition.language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := bookedition.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "BookEdition.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Format(); ok {
		if err := bookedition.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "BookEdition.format": %w`, err)}
		}
	}
	if _u.mutation.BookCleared() && len(_u.mutation.BookIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BookEdition.book"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BookEditionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BookEditionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BookEditionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bookedition.Table, bookedition.Columns, sqlgraph.NewFieldSpec(bookedition.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(bookedition.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HardcoverEditionID(); ok {
		_spec.SetField(bookedition.FieldHardcoverEditionID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedHardcoverEditionID(); ok {
		_spec.AddField(bookedition.FieldHardcoverEditionID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(bookedition.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(bookedition.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Publisher(); ok {
		_spec.SetField(bookedition.FieldPublisher, field.TypeString, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(bookedition.FieldYear, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(bookedition.FieldYear, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.Format(); ok {
		_spec.SetField(bookedition.FieldFormat, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Original(); ok {
		_spec.SetField(bookedition.FieldOriginal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Pages(); ok {
		_spec.SetField(bookedition.FieldPages, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedPages(); ok {
		_spec.AddField(bookedition.FieldPages, field.TypeUint16, value)
	}
	if _u.mutation.PagesCleared() {
		_spec.ClearField(bookedition.FieldPages, field.TypeUint16)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(bookedition.FieldDurationSeconds, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(bookedition.FieldDurationSeconds, field.TypeUint32, value)
	}
	if _u.mutation.DurationSecondsCleared() {
		_spec.ClearField(bookedition.FieldDurationSeconds, field.TypeUint32)
	}
	if value, ok := _u.mutation.Narrator(); ok {
		_spec.SetField(bookedition.FieldNarrator, field.TypeString, value)
	}
	if _u.mutation.NarratorCleared() {
		_spec.ClearField(bookedition.FieldNarrator, field.TypeString)
	}
	if value, ok := _u.mutation.Translator(); ok {
		_spec.SetField(bookedition.FieldTranslator, field.TypeString, value)
	}
	if _u.mutation.TranslatorCleared() {
		_spec.ClearField(bookedition.FieldTranslator, field.TypeString)
	}
	if value, ok := _u.mutation.Isbn13(); ok {
		_spec.SetField(bookedition.FieldIsbn13, field.TypeString, value)
	}
	if _u.mutation.Isbn13Cleared() {
		_spec.ClearField(bookedition.FieldIsbn13, field.TypeString)
	}
	if value, ok := _u.mutation.Asin(); ok {
		_spec.SetField(bookedition.FieldAsin, field.TypeString, value)
	}
	if _u.mutation.AsinCleared() {
		_spec.ClearField(bookedition.FieldAsin, field.TypeString)
	}
	if value, ok := _u.mutation.Popularity(); ok {
		_spec.SetField(bookedition.FieldPopularity, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPopularity(); ok {
		_spec.AddField(bookedition.FieldPopularity, field.TypeUint32, value)
	}
	if _u.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bookedition.BookTable,
			Columns: []string{bookedition.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bookedition.BookTable,
			Columns: []string{bookedition.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookedition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookEditionUpdateOne is the builder for updating a single BookEdition entity.
type BookEditionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BookEditionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *BookEditionUpdateOne) SetUpdateTime(v time.Time) *BookEditionUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetHardcoverEditionID sets the "hardcover_edition_id" field.
func (_u *BookEditionUpdateOne) SetHardcoverEditionID(v uint32) *BookEditionUpdateOne {
	_u.mutation.ResetHardcoverEditionID()
	_u.mutation.SetHardcoverEditionID(v)
	return _u
}

// SetNillableHardcoverEditionID sets the "hardcover_edition_id" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillableHardcoverEditionID(v *uint32) *BookEditionUpdateOne {
	if v != nil {
		_u.SetHardcoverEditionID(*v)
	}
	return _u
}

// AddHardcoverEditionID adds value to the "hardcover_edition_id" field.
func (_u *BookEditionUpdateOne) AddHardcoverEditionID(v int32) *BookEditionUpdateOne {
	_u.mutation.AddHardcoverEditionID(v)
	return _u
}

// SetLanguage sets the "language" field.
func (_u *BookEditionUpdateOne) SetLanguage(v string) *BookEditionUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillableLanguage(v *string) *BookEditionUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookEditionUpdateOne) SetTitle(v string) *BookEditionUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillableTitle(v *string) *BookEditionUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetPublisher sets the "publisher" field.
func (_u *BookEditionUpdateOne) SetPublisher(v string) *BookEditionUpdateOne {
	_u.mutation.SetPublisher(v)
	return _u
}

// SetNillablePublisher sets the "publisher" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillablePublisher(v *string) *BookEditionUpdateOne {
	if v != nil {
		_u.SetPublisher(*v)
	}
	return _u
}

// SetYear sets the "year" field.
func (_u *BookEditionUpdateOne) SetYear(v uint16) *BookEditionUpdateOne {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillableYear(v *uint16) *BookEditionUpdateOne {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *BookEditionUpdateOne) AddYear(v int16) *BookEditionUpdateOne {
	_u.mutation.AddYear(v)
	return _u
}

// SetFormat sets the "format" field.
func (_u *BookEditionUpdateOne) SetFormat(v bookedition.Format) *BookEditionUpdateOne {
	_u.mutation.SetFormat(v)
	return _u
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillableFormat(v *bookedition.Format) *BookEditionUpdateOne {
	if v != nil {
		_u.SetFormat(*v)
	}
	return _u
}

// SetOriginal sets the "original" field.
func (_u *BookEditionUpdateOne) SetOriginal(v bool) *BookEditionUpdateOne {
	_u.mutation.SetOriginal(v)
	return _u
}

// SetNillableOriginal sets the "original" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillableOriginal(v *bool) *BookEditionUpdateOne {
	if v != nil {
		_u.SetOriginal(*v)
	}
	return _u
}

// SetPages sets the "pages" field.
func (_u *BookEditionUpdateOne) SetPages(v uint16) *BookEditionUpdateOne {
	_u.mutation.ResetPages()
	_u.mutation.SetPages(v)
	return _u
}

// SetNillablePages sets the "pages" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillablePages(v *uint16) *BookEditionUpdateOne {
	if v != nil {
		_u.SetPages(*v)
	}
	return _u
}

// AddPages adds value to the "pages" field.
func (_u *BookEditionUpdateOne) AddPages(v int16) *BookEditionUpdateOne {
	_u.mutation.AddPages(v)
	return _u
}

// ClearPages clears the value of the "pages" field.
func (_u *BookEditionUpdateOne) ClearPages() *BookEditionUpdateOne {
	_u.mutation.ClearPages()
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *BookEditionUpdateOne) SetDurationSeconds(v uint32) *BookEditionUpdateOne {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillableDurationSeconds(v *uint32) *BookEditionUpdateOne {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *BookEditionUpdateOne) AddDurationSeconds(v int32) *BookEditionUpdateOne {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// ClearDurationSeconds clears the value of the "duration_seconds" field.
func (_u *BookEditionUpdateOne) ClearDurationSeconds() *BookEditionUpdateOne {
	_u.mutation.ClearDurationSeconds()
	return _u
}

// SetNarrator sets the "narrator" field.
func (_u *BookEditionUpdateOne) SetNarrator(v string) *BookEditionUpdateOne {
	_u.mutation.SetNarrator(v)
	return _u
}

// SetNillableNarrator sets the "narrator" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillableNarrator(v *string) *BookEditionUpdateOne {
	if v != nil {
		_u.SetNarrator(*v)
	}
	return _u
}

// ClearNarrator clears the value of the "narrator" field.
func (_u *BookEditionUpdateOne) ClearNarrator() *BookEditionUpdateOne {
	_u.mutation.ClearNarrator()
	return _u
}

// SetTranslator sets the "translator" field.
func (_u *BookEditionUpdateOne) SetTranslator(v string) *BookEditionUpdateOne {
	_u.mutation.SetTranslator(v)
	return _u
}

// SetNillableTranslator sets the "translator" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillableTranslator(v *string) *BookEditionUpdateOne {
	if v != nil {
		_u.SetTranslator(*v)
	}
	return _u
}

// ClearTranslator clears the value of the "translator" field.
func (_u *BookEditionUpdateOne) ClearTranslator() *BookEditionUpdateOne {
	_u.mutation.ClearTranslator()
	return _u
}

// SetIsbn13 sets the "isbn_13" field.
func (_u *BookEditionUpdateOne) SetIsbn13(v string) *BookEditionUpdateOne {
	_u.mutation.SetIsbn13(v)
	return _u
}

// SetNillableIsbn13 sets the "isbn_13" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillableIsbn13(v *string) *BookEditionUpdateOne {
	if v != nil {
		_u.SetIsbn13(*v)
	}
	return _u
}

// ClearIsbn13 clears the value of the "isbn_13" field.
func (_u *BookEditionUpdateOne) ClearIsbn13() *BookEditionUpdateOne {
	_u.mutation.ClearIsbn13()
	return _u
}

// SetAsin sets the "asin" field.
func (_u *BookEditionUpdateOne) SetAsin(v string) *BookEditionUpdateOne {
	_u.mutation.SetAsin(v)
	return _u
}

// SetNillableAsin sets the "asin" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillableAsin(v *string) *BookEditionUpdateOne {
	if v != nil {
		_u.SetAsin(*v)
	}
	return _u
}

// ClearAsin clears the value of the "asin" field.
func (_u *BookEditionUpdateOne) ClearAsin() *BookEditionUpdateOne {
	_u.mutation.ClearAsin()
	return _u
}

// SetPopularity sets the "popularity" field.
func (_u *BookEditionUpdateOne) SetPopularity(v uint32) *BookEditionUpdateOne {
	_u.mutation.ResetPopularity()
	_u.mutation.SetPopularity(v)
	return _u
}

// SetNillablePopularity sets the "popularity" field if the given value is not nil.
func (_u *BookEditionUpdateOne) SetNillablePopularity(v *uint32) *BookEditionUpdateOne {
	if v != nil {
		_u.SetPopularity(*v)
	}
	return _u
}

// AddPopularity adds value to the "popularity" field.
func (_u *BookEditionUpdateOne) AddPopularity(v int32) *BookEditionUpdateOne {
	_u.mutation.AddPopularity(v)
	return _u
}

// SetBookID sets the "book" edge to the Book entity by ID.
func (_u *BookEditionUpdateOne) SetBookID(id uint32) *BookEditionUpdateOne {
	_u.mutation.SetBookID(id)
	return _u
}

// SetBook sets the "book" edge to the Book entity.
func (_u *BookEditionUpdateOne) SetBook(v *Book) *BookEditionUpdateOne {
	return _u.SetBookID(v.ID)
}

// Mutation returns the BookEditionMutation object of the builder.
func (_u *BookEditionUpdateOne) Mutation() *BookEditionMutation {
	return _u.mutation
}

// ClearBook clears the "book" edge to the Book entity.
func (_u *BookEditionUpdateOne) ClearBook() *BookEditionUpdateOne {
	_u.mutation.ClearBook()
	return _u
}

// Where appends a list predicates to the BookEditionUpdate builder.
func (_u *BookEditionUpdateOne) Where(ps ...predicate.BookEdition) *BookEditionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookEditionUpdateOne) Select(field string, fields ...string) *BookEditionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BookEdition entity.
func (_u *BookEditionUpdateOne) Save(ctx context.Context) (*BookEdition, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookEditionUpdateOne) SaveX(ctx context.Context) *BookEdition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookEditionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookEditionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookEditionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := bookedition.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookEditionUpdateOne) check() error {
	if v, ok := _u.mutation.Language(); ok {
		if err := bookedition.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "BookEdition.language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := bookedition.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "BookEdition.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Format(); ok {
		if err := bookedition.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "BookEdition.format": %w`, err)}
		}
	}
	if _u.mutation.BookCleared() && len(_u.mutation.BookIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BookEdition.book"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BookEditionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BookEditionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BookEditionUpdateOne) sqlSave(ctx context.Context) (_node *BookEdition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bookedition.Table, bookedition.Columns, sqlgraph.NewFieldSpec(bookedition.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BookEdition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bookedition.FieldID)
		for _, f := range fields {
			if !bookedition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bookedition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(bookedition.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HardcoverEditionID(); ok {
		_spec.SetField(bookedition.FieldHardcoverEditionID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedHardcoverEditionID(); ok {
		_spec.AddField(bookedition.FieldHardcoverEditionID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(bookedition.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(bookedition.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Publisher(); ok {
		_spec.SetField(bookedition.FieldPublisher, field.TypeString, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(bookedition.FieldYear, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(bookedition.FieldYear, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.Format(); ok {
		_spec.SetField(bookedition.FieldFormat, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Original(); ok {
		_spec.SetField(bookedition.FieldOriginal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Pages(); ok {
		_spec.SetField(bookedition.FieldPages, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedPages(); ok {
		_spec.AddField(bookedition.FieldPages, field.TypeUint16, value)
	}
	if _u.mutation.PagesCleared() {
		_spec.ClearField(bookedition.FieldPages, field.TypeUint16)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(bookedition.FieldDurationSeconds, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(bookedition.FieldDurationSeconds, field.TypeUint32, value)
	}
	if _u.mutation.DurationSecondsCleared() {
		_spec.ClearField(bookedition.FieldDurationSeconds, field.TypeUint32)
	}
	if value, ok := _u.mutation.Narrator(); ok {
		_spec.SetField(bookedition.FieldNarrator, field.TypeString, value)
	}
	if _u.mutation.NarratorCleared() {
		_spec.ClearField(bookedition.FieldNarrator, field.TypeString)
	}
	if value, ok := _u.mutation.Translator(); ok {
		_spec.SetField(bookedition.FieldTranslator, field.TypeString, value)
	}
	if _u.mutation.TranslatorCleared() {
		_spec.ClearField(bookedition.FieldTranslator, field.TypeString)
	}
	if value, ok := _u.mutation.Isbn13(); ok {
		_spec.SetField(bookedition.FieldIsbn13, field.TypeString, value)
	}
	if _u.mutation.Isbn13Cleared() {
		_spec.ClearField(bookedition.FieldIsbn13, field.TypeString)
	}
	if value, ok := _u.mutation.Asin(); ok {
		_spec.SetField(bookedition.FieldAsin, field.TypeString, value)
	}
	if _u.mutation.AsinCleared() {
		_spec.ClearField(bookedition.FieldAsin, field.TypeString)
	}
	if value, ok := _u.mutation.Popularity(); ok {
		_spec.SetField(bookedition.FieldPopularity, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPopularity(); ok {
		_spec.AddField(bookedition.FieldPopularity, field.TypeUint32, value)
	}
	if _u.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bookedition.BookTable,
			Columns: []string{bookedition.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bookedition.BookTable,
			Columns: []string{bookedition.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &BookEdition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookedition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
