// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datahearth/streamline/ent/author"
	"github.com/datahearth/streamline/ent/book"
	"github.com/datahearth/streamline/ent/bookcontribution"
	"github.com/datahearth/streamline/ent/bookseries"
	"github.com/datahearth/streamline/ent/predicate"
)

// BookContributionQuery is the builder for querying BookContribution entities.
type BookContributionQuery struct {
	config
	ctx        *QueryContext
	order      []bookcontribution.OrderOption
	inters     []Interceptor
	predicates []predicate.BookContribution
	withAuthor *AuthorQuery
	withBook   *BookQuery
	withSeries *BookSeriesQuery
	withFKs    bool
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BookContributionQuery builder.
func (_q *BookContributionQuery) Where(ps ...predicate.BookContribution) *BookContributionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BookContributionQuery) Limit(limit int) *BookContributionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BookContributionQuery) Offset(offset int) *BookContributionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BookContributionQuery) Unique(unique bool) *BookContributionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BookContributionQuery) Order(o ...bookcontribution.OrderOption) *BookContributionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAuthor chains the current query on the "author" edge.
func (_q *BookContributionQuery) QueryAuthor() *AuthorQuery {
	query := (&AuthorClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bookcontribution.Table, bookcontribution.FieldID, selector),
			sqlgraph.To(author.Table, author.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, bookcontribution.AuthorTable, bookcontribution.AuthorColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBook chains the current query on the "book" edge.
func (_q *BookContributionQuery) QueryBook() *BookQuery {
	query := (&BookClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bookcontribution.Table, bookcontribution.FieldID, selector),
			sqlgraph.To(book.Table, book.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, bookcontribution.BookTable, bookcontribution.BookColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySeries chains the current query on the "series" edge.
func (_q *BookContributionQuery) QuerySeries() *BookSeriesQuery {
	query := (&BookSeriesClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bookcontribution.Table, bookcontribution.FieldID, selector),
			sqlgraph.To(bookseries.Table, bookseries.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, bookcontribution.SeriesTable, bookcontribution.SeriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BookContribution entity from the query.
// Returns a *NotFoundError when no BookContribution was found.
func (_q *BookContributionQuery) First(ctx context.Context) (*BookContribution, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bookcontribution.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BookContributionQuery) FirstX(ctx context.Context) *BookContribution {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BookContribution ID from the query.
// Returns a *NotFoundError when no BookContribution ID was found.
func (_q *BookContributionQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bookcontribution.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BookContributionQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BookContribution entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BookContribution entity is found.
// Returns a *NotFoundError when no BookContribution entities are found.
func (_q *BookContributionQuery) Only(ctx context.Context) (*BookContribution, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bookcontribution.Label}
	default:
		return nil, &NotSingularError{bookcontribution.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BookContributionQuery) OnlyX(ctx context.Context) *BookContribution {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BookContribution ID in the query.
// Returns a *NotSingularError when more than one BookContribution ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BookContributionQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bookcontribution.Label}
	default:
		err = &NotSingularError{bookcontribution.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BookContributionQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BookContributions.
func (_q *BookContributionQuery) All(ctx context.Context) ([]*BookContribution, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BookContribution, *BookContributionQuery]()
	return withInterceptors[[]*BookContribution](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BookContributionQuery) AllX(ctx context.Context) []*BookContribution {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BookContribution IDs.
func (_q *BookContributionQuery) IDs(ctx context.Context) (ids []uint32, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(bookcontribution.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BookContributionQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BookContributionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BookContributionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BookContributionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BookContributionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BookContributionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BookContributionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BookContributionQuery) Clone() *BookContributionQuery {
	if _q == nil {
		return nil
	}
	return &BookContributionQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]bookcontribution.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.BookContribution{}, _q.predicates...),
		withAuthor: _q.withAuthor.Clone(),
		withBook:   _q.withBook.Clone(),
		withSeries: _q.withSeries.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithAuthor tells the query-builder to eager-load the nodes that are connected to
// the "author" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BookContributionQuery) WithAuthor(opts ...func(*AuthorQuery)) *BookContributionQuery {
	query := (&AuthorClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAuthor = query
	return _q
}

// WithBook tells the query-builder to eager-load the nodes that are connected to
// the "book" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BookContributionQuery) WithBook(opts ...func(*BookQuery)) *BookContributionQuery {
	query := (&BookClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBook = query
	return _q
}

// WithSeries tells the query-builder to eager-load the nodes that are connected to
// the "series" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BookContributionQuery) WithSeries(opts ...func(*BookSeriesQuery)) *BookContributionQuery {
	query := (&BookSeriesClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSeries = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BookContribution.Query().
//		GroupBy(bookcontribution.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *BookContributionQuery) GroupBy(field string, fields ...string) *BookContributionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BookContributionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = bookcontribution.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.BookContribution.Query().
//		Select(bookcontribution.FieldCreateTime).
//		Scan(ctx, &v)
func (_q *BookContributionQuery) Select(fields ...string) *BookContributionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BookContributionSelect{BookContributionQuery: _q}
	sbuild.label = bookcontribution.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BookContributionSelect configured with the given aggregations.
func (_q *BookContributionQuery) Aggregate(fns ...AggregateFunc) *BookContributionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BookContributionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !bookcontribution.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BookContributionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BookContribution, error) {
	var (
		nodes       = []*BookContribution{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withAuthor != nil,
			_q.withBook != nil,
			_q.withSeries != nil,
		}
	)
	if _q.withAuthor != nil || _q.withBook != nil || _q.withSeries != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, bookcontribution.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BookContribution).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BookContribution{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAuthor; query != nil {
		if err := _q.loadAuthor(ctx, query, nodes, nil,
			func(n *BookContribution, e *Author) { n.Edges.Author = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBook; query != nil {
		if err := _q.loadBook(ctx, query, nodes, nil,
			func(n *BookContribution, e *Book) { n.Edges.Book = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSeries; query != nil {
		if err := _q.loadSeries(ctx, query, nodes, nil,
			func(n *BookContribution, e *BookSeries) { n.Edges.Series = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *BookContributionQuery) loadAuthor(ctx context.Context, query *AuthorQuery, nodes []*BookContribution, init func(*BookContribution), assign func(*BookContribution, *Author)) error {
	ids := make([]uint32, 0, len(nodes))
	nodeids := make(map[uint32][]*BookContribution)
	for i := range nodes {
		if nodes[i].author_contributions == nil {
			continue
		}
		fk := *nodes[i].author_contributions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(author.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "author_contributions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *BookContributionQuery) loadBook(ctx context.Context, query *BookQuery, nodes []*BookContribution, init func(*BookContribution), assign func(*BookContribution, *Book)) error {
	ids := make([]uint32, 0, len(nodes))
	nodeids := make(map[uint32][]*BookContribution)
	for i := range nodes {
		if nodes[i].book_contributions == nil {
			continue
		}
		fk := *nodes[i].book_contributions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(book.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "book_contributions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *BookContributionQuery) loadSeries(ctx context.Context, query *BookSeriesQuery, nodes []*BookContribution, init func(*BookContribution), assign func(*BookContribution, *BookSeries)) error {
	ids := make([]uint32, 0, len(nodes))
	nodeids := make(map[uint32][]*BookContribution)
	for i := range nodes {
		if nodes[i].book_series_contributions == nil {
			continue
		}
		fk := *nodes[i].book_series_contributions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(bookseries.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "book_series_contributions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *BookContributionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BookContributionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(bookcontribution.Table, bookcontribution.Columns, sqlgraph.NewFieldSpec(bookcontribution.FieldID, field.TypeUint32))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bookcontribution.FieldID)
		for i := range fields {
			if fields[i] != bookcontribution.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BookContributionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(bookcontribution.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = bookcontribution.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *BookContributionQuery) Modify(modifiers ...func(s *sql.Selector)) *BookContributionSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// BookContributionGroupBy is the group-by builder for BookContribution entities.
type BookContributionGroupBy struct {
	selector
	build *BookContributionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BookContributionGroupBy) Aggregate(fns ...AggregateFunc) *BookContributionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BookContributionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BookContributionQuery, *BookContributionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BookContributionGroupBy) sqlScan(ctx context.Context, root *BookContributionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BookContributionSelect is the builder for selecting fields of BookContribution entities.
type BookContributionSelect struct {
	*BookContributionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BookContributionSelect) Aggregate(fns ...AggregateFunc) *BookContributionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BookContributionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BookContributionQuery, *BookContributionSelect](ctx, _s.BookContributionQuery, _s, _s.inters, v)
}

func (_s *BookContributionSelect) sqlScan(ctx context.Context, root *BookContributionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *BookContributionSelect) Modify(modifiers ...func(s *sql.Selector)) *BookContributionSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
