// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datahearth/streamline/ent/downloadrecord"
	"github.com/datahearth/streamline/ent/episode"
	"github.com/datahearth/streamline/ent/movie"
	"github.com/datahearth/streamline/ent/predicate"
)

// DownloadRecordUpdate is the builder for updating DownloadRecord entities.
type DownloadRecordUpdate struct {
	config
	hooks    []Hook
	mutation *DownloadRecordMutation
}

// Where appends a list predicates to the DownloadRecordUpdate builder.
func (_u *DownloadRecordUpdate) Where(ps ...predicate.DownloadRecord) *DownloadRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *DownloadRecordUpdate) SetUpdateTime(v time.Time) *DownloadRecordUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *DownloadRecordUpdate) SetTitle(v string) *DownloadRecordUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableTitle(v *string) *DownloadRecordUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetQuality sets the "quality" field.
func (_u *DownloadRecordUpdate) SetQuality(v string) *DownloadRecordUpdate {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableQuality(v *string) *DownloadRecordUpdate {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// ClearQuality clears the value of the "quality" field.
func (_u *DownloadRecordUpdate) ClearQuality() *DownloadRecordUpdate {
	_u.mutation.ClearQuality()
	return _u
}

// SetSize sets the "size" field.
func (_u *DownloadRecordUpdate) SetSize(v int64) *DownloadRecordUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableSize(v *int64) *DownloadRecordUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *DownloadRecordUpdate) AddSize(v int64) *DownloadRecordUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// ClearSize clears the value of the "size" field.
func (_u *DownloadRecordUpdate) ClearSize() *DownloadRecordUpdate {
	_u.mutation.ClearSize()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DownloadRecordUpdate) SetStatus(v downloadrecord.Status) *DownloadRecordUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableStatus(v *downloadrecord.Status) *DownloadRecordUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTorrentHash sets the "torrent_hash" field.
func (_u *DownloadRecordUpdate) SetTorrentHash(v string) *DownloadRecordUpdate {
	_u.mutation.SetTorrentHash(v)
	return _u
}

// SetNillableTorrentHash sets the "torrent_hash" field if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableTorrentHash(v *string) *DownloadRecordUpdate {
	if v != nil {
		_u.SetTorrentHash(*v)
	}
	return _u
}

// ClearTorrentHash clears the value of the "torrent_hash" field.
func (_u *DownloadRecordUpdate) ClearTorrentHash() *DownloadRecordUpdate {
	_u.mutation.ClearTorrentHash()
	return _u
}

// SetReleaseGroup sets the "release_group" field.
func (_u *DownloadRecordUpdate) SetReleaseGroup(v string) *DownloadRecordUpdate {
	_u.mutation.SetReleaseGroup(v)
	return _u
}

// SetNillableReleaseGroup sets the "release_group" field if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableReleaseGroup(v *string) *DownloadRecordUpdate {
	if v != nil {
		_u.SetReleaseGroup(*v)
	}
	return _u
}

// ClearReleaseGroup clears the value of the "release_group" field.
func (_u *DownloadRecordUpdate) ClearReleaseGroup() *DownloadRecordUpdate {
	_u.mutation.ClearReleaseGroup()
	return _u
}

// SetSavePath sets the "save_path" field.
func (_u *DownloadRecordUpdate) SetSavePath(v string) *DownloadRecordUpdate {
	_u.mutation.SetSavePath(v)
	return _u
}

// SetNillableSavePath sets the "save_path" field if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableSavePath(v *string) *DownloadRecordUpdate {
	if v != nil {
		_u.SetSavePath(*v)
	}
	return _u
}

// ClearSavePath clears the value of the "save_path" field.
func (_u *DownloadRecordUpdate) ClearSavePath() *DownloadRecordUpdate {
	_u.mutation.ClearSavePath()
	return _u
}

// SetImportAttempts sets the "import_attempts" field.
func (_u *DownloadRecordUpdate) SetImportAttempts(v uint8) *DownloadRecordUpdate {
	_u.mutation.ResetImportAttempts()
	_u.mutation.SetImportAttempts(v)
	return _u
}

// SetNillableImportAttempts sets the "import_attempts" field if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableImportAttempts(v *uint8) *DownloadRecordUpdate {
	if v != nil {
		_u.SetImportAttempts(*v)
	}
	return _u
}

// AddImportAttempts adds value to the "import_attempts" field.
func (_u *DownloadRecordUpdate) AddImportAttempts(v int8) *DownloadRecordUpdate {
	_u.mutation.AddImportAttempts(v)
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *DownloadRecordUpdate) SetFailureReason(v string) *DownloadRecordUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableFailureReason(v *string) *DownloadRecordUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *DownloadRecordUpdate) ClearFailureReason() *DownloadRecordUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetImportedAt sets the "imported_at" field.
func (_u *DownloadRecordUpdate) SetImportedAt(v time.Time) *DownloadRecordUpdate {
	_u.mutation.SetImportedAt(v)
	return _u
}

// SetNillableImportedAt sets the "imported_at" field if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableImportedAt(v *time.Time) *DownloadRecordUpdate {
	if v != nil {
		_u.SetImportedAt(*v)
	}
	return _u
}

// ClearImportedAt clears the value of the "imported_at" field.
func (_u *DownloadRecordUpdate) ClearImportedAt() *DownloadRecordUpdate {
	_u.mutation.ClearImportedAt()
	return _u
}

// SetIndexerName sets the "indexer_name" field.
func (_u *DownloadRecordUpdate) SetIndexerName(v string) *DownloadRecordUpdate {
	_u.mutation.SetIndexerName(v)
	return _u
}

// SetNillableIndexerName sets the "indexer_name" field if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableIndexerName(v *string) *DownloadRecordUpdate {
	if v != nil {
		_u.SetIndexerName(*v)
	}
	return _u
}

// ClearIndexerName clears the value of the "indexer_name" field.
func (_u *DownloadRecordUpdate) ClearIndexerName() *DownloadRecordUpdate {
	_u.mutation.ClearIndexerName()
	return _u
}

// SetDownloadClientName sets the "download_client_name" field.
func (_u *DownloadRecordUpdate) SetDownloadClientName(v string) *DownloadRecordUpdate {
	_u.mutation.SetDownloadClientName(v)
	return _u
}

// SetNillableDownloadClientName sets the "download_client_name" field if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableDownloadClientName(v *string) *DownloadRecordUpdate {
	if v != nil {
		_u.SetDownloadClientName(*v)
	}
	return _u
}

// ClearDownloadClientName clears the value of the "download_client_name" field.
func (_u *DownloadRecordUpdate) ClearDownloadClientName() *DownloadRecordUpdate {
	_u.mutation.ClearDownloadClientName()
	return _u
}

// SetReplaceExisting sets the "replace_existing" field.
func (_u *DownloadRecordUpdate) SetReplaceExisting(v bool) *DownloadRecordUpdate {
	_u.mutation.SetReplaceExisting(v)
	return _u
}

// SetNillableReplaceExisting sets the "replace_existing" field if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableReplaceExisting(v *bool) *DownloadRecordUpdate {
	if v != nil {
		_u.SetReplaceExisting(*v)
	}
	return _u
}

// SetMovieID sets the "movie" edge to the Movie entity by ID.
func (_u *DownloadRecordUpdate) SetMovieID(id uint32) *DownloadRecordUpdate {
	_u.mutation.SetMovieID(id)
	return _u
}

// SetNillableMovieID sets the "movie" edge to the Movie entity by ID if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableMovieID(id *uint32) *DownloadRecordUpdate {
	if id != nil {
		_u = _u.SetMovieID(*id)
	}
	return _u
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_u *DownloadRecordUpdate) SetMovie(v *Movie) *DownloadRecordUpdate {
	return _u.SetMovieID(v.ID)
}

// SetEpisodeID sets the "episode" edge to the Episode entity by ID.
func (_u *DownloadRecordUpdate) SetEpisodeID(id uint32) *DownloadRecordUpdate {
	_u.mutation.SetEpisodeID(id)
	return _u
}

// SetNillableEpisodeID sets the "episode" edge to the Episode entity by ID if the given value is not nil.
func (_u *DownloadRecordUpdate) SetNillableEpisodeID(id *uint32) *DownloadRecordUpdate {
	if id != nil {
		_u = _u.SetEpisodeID(*id)
	}
	return _u
}

// SetEpisode sets the "episode" edge to the Episode entity.
func (_u *DownloadRecordUpdate) SetEpisode(v *Episode) *DownloadRecordUpdate {
	return _u.SetEpisodeID(v.ID)
}

// Mutation returns the DownloadRecordMutation object of the builder.
func (_u *DownloadRecordUpdate) Mutation() *DownloadRecordMutation {
	return _u.mutation
}

// ClearMovie clears the "movie" edge to the Movie entity.
func (_u *DownloadRecordUpdate) ClearMovie() *DownloadRecordUpdate {
	_u.mutation.ClearMovie()
	return _u
}

// ClearEpisode clears the "episode" edge to the Episode entity.
func (_u *DownloadRecordUpdate) ClearEpisode() *DownloadRecordUpdate {
	_u.mutation.ClearEpisode()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DownloadRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DownloadRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DownloadRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DownloadRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DownloadRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := downloadrecord.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DownloadRecordUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := downloadrecord.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "DownloadRecord.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := downloadrecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DownloadRecord.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DownloadRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(downloadrecord.Table, downloadrecord.Columns, sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(downloadrecord.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(downloadrecord.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(downloadrecord.FieldQuality, field.TypeString, value)
	}
	if _u.mutation.QualityCleared() {
		_spec.ClearField(downloadrecord.FieldQuality, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(downloadrecord.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(downloadrecord.FieldSize, field.TypeInt64, value)
	}
	if _u.mutation.SizeCleared() {
		_spec.ClearField(downloadrecord.FieldSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(downloadrecord.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TorrentHash(); ok {
		_spec.SetField(downloadrecord.FieldTorrentHash, field.TypeString, value)
	}
	if _u.mutation.TorrentHashCleared() {
		_spec.ClearField(downloadrecord.FieldTorrentHash, field.TypeString)
	}
	if value, ok := _u.mutation.ReleaseGroup(); ok {
		_spec.SetField(downloadrecord.FieldReleaseGroup, field.TypeString, value)
	}
	if _u.mutation.ReleaseGroupCleared() {
		_spec.ClearField(downloadrecord.FieldReleaseGroup, field.TypeString)
	}
	if value, ok := _u.mutation.SavePath(); ok {
		_spec.SetField(downloadrecord.FieldSavePath, field.TypeString, value)
	}
	if _u.mutation.SavePathCleared() {
		_spec.ClearField(downloadrecord.FieldSavePath, field.TypeString)
	}
	if value, ok := _u.mutation.ImportAttempts(); ok {
		_spec.SetField(downloadrecord.FieldImportAttempts, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedImportAttempts(); ok {
		_spec.AddField(downloadrecord.FieldImportAttempts, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(downloadrecord.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(downloadrecord.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.ImportedAt(); ok {
		_spec.SetField(downloadrecord.FieldImportedAt, field.TypeTime, value)
	}
	if _u.mutation.ImportedAtCleared() {
		_spec.ClearField(downloadrecord.FieldImportedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IndexerName(); ok {
		_spec.SetField(downloadrecord.FieldIndexerName, field.TypeString, value)
	}
	if _u.mutation.IndexerNameCleared() {
		_spec.ClearField(downloadrecord.FieldIndexerName, field.TypeString)
	}
	if value, ok := _u.mutation.DownloadClientName(); ok {
		_spec.SetField(downloadrecord.FieldDownloadClientName, field.TypeString, value)
	}
	if _u.mutation.DownloadClientNameCleared() {
		_spec.ClearField(downloadrecord.FieldDownloadClientName, field.TypeString)
	}
	if value, ok := _u.mutation.ReplaceExisting(); ok {
		_spec.SetField(downloadrecord.FieldReplaceExisting, field.TypeBool, value)
	}
	if _u.mutation.MovieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadrecord.MovieTable,
			Columns: []string{downloadrecord.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadrecord.MovieTable,
			Columns: []string{downloadrecord.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EpisodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadrecord.EpisodeTable,
			Columns: []string{downloadrecord.EpisodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EpisodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadrecord.EpisodeTable,
			Columns: []string{downloadrecord.EpisodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{downloadrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DownloadRecordUpdateOne is the builder for updating a single DownloadRecord entity.
type DownloadRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DownloadRecordMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *DownloadRecordUpdateOne) SetUpdateTime(v time.Time) *DownloadRecordUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *DownloadRecordUpdateOne) SetTitle(v string) *DownloadRecordUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableTitle(v *string) *DownloadRecordUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetQuality sets the "quality" field.
func (_u *DownloadRecordUpdateOne) SetQuality(v string) *DownloadRecordUpdateOne {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableQuality(v *string) *DownloadRecordUpdateOne {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// ClearQuality clears the value of the "quality" field.
func (_u *DownloadRecordUpdateOne) ClearQuality() *DownloadRecordUpdateOne {
	_u.mutation.ClearQuality()
	return _u
}

// SetSize sets the "size" field.
func (_u *DownloadRecordUpdateOne) SetSize(v int64) *DownloadRecordUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableSize(v *int64) *DownloadRecordUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *DownloadRecordUpdateOne) AddSize(v int64) *DownloadRecordUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// ClearSize clears the value of the "size" field.
func (_u *DownloadRecordUpdateOne) ClearSize() *DownloadRecordUpdateOne {
	_u.mutation.ClearSize()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DownloadRecordUpdateOne) SetStatus(v downloadrecord.Status) *DownloadRecordUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableStatus(v *downloadrecord.Status) *DownloadRecordUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTorrentHash sets the "torrent_hash" field.
func (_u *DownloadRecordUpdateOne) SetTorrentHash(v string) *DownloadRecordUpdateOne {
	_u.mutation.SetTorrentHash(v)
	return _u
}

// SetNillableTorrentHash sets the "torrent_hash" field if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableTorrentHash(v *string) *DownloadRecordUpdateOne {
	if v != nil {
		_u.SetTorrentHash(*v)
	}
	return _u
}

// ClearTorrentHash clears the value of the "torrent_hash" field.
func (_u *DownloadRecordUpdateOne) ClearTorrentHash() *DownloadRecordUpdateOne {
	_u.mutation.ClearTorrentHash()
	return _u
}

// SetReleaseGroup sets the "release_group" field.
func (_u *DownloadRecordUpdateOne) SetReleaseGroup(v string) *DownloadRecordUpdateOne {
	_u.mutation.SetReleaseGroup(v)
	return _u
}

// SetNillableReleaseGroup sets the "release_group" field if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableReleaseGroup(v *string) *DownloadRecordUpdateOne {
	if v != nil {
		_u.SetReleaseGroup(*v)
	}
	return _u
}

// ClearReleaseGroup clears the value of the "release_group" field.
func (_u *DownloadRecordUpdateOne) ClearReleaseGroup() *DownloadRecordUpdateOne {
	_u.mutation.ClearReleaseGroup()
	return _u
}

// SetSavePath sets the "save_path" field.
func (_u *DownloadRecordUpdateOne) SetSavePath(v string) *DownloadRecordUpdateOne {
	_u.mutation.SetSavePath(v)
	return _u
}

// SetNillableSavePath sets the "save_path" field if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableSavePath(v *string) *DownloadRecordUpdateOne {
	if v != nil {
		_u.SetSavePath(*v)
	}
	return _u
}

// ClearSavePath clears the value of the "save_path" field.
func (_u *DownloadRecordUpdateOne) ClearSavePath() *DownloadRecordUpdateOne {
	_u.mutation.ClearSavePath()
	return _u
}

// SetImportAttempts sets the "import_attempts" field.
func (_u *DownloadRecordUpdateOne) SetImportAttempts(v uint8) *DownloadRecordUpdateOne {
	_u.mutation.ResetImportAttempts()
	_u.mutation.SetImportAttempts(v)
	return _u
}

// SetNillableImportAttempts sets the "import_attempts" field if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableImportAttempts(v *uint8) *DownloadRecordUpdateOne {
	if v != nil {
		_u.SetImportAttempts(*v)
	}
	return _u
}

// AddImportAttempts adds value to the "import_attempts" field.
func (_u *DownloadRecordUpdateOne) AddImportAttempts(v int8) *DownloadRecordUpdateOne {
	_u.mutation.AddImportAttempts(v)
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *DownloadRecordUpdateOne) SetFailureReason(v string) *DownloadRecordUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableFailureReason(v *string) *DownloadRecordUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *DownloadRecordUpdateOne) ClearFailureReason() *DownloadRecordUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetImportedAt sets the "imported_at" field.
func (_u *DownloadRecordUpdateOne) SetImportedAt(v time.Time) *DownloadRecordUpdateOne {
	_u.mutation.SetImportedAt(v)
	return _u
}

// SetNillableImportedAt sets the "imported_at" field if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableImportedAt(v *time.Time) *DownloadRecordUpdateOne {
	if v != nil {
		_u.SetImportedAt(*v)
	}
	return _u
}

// ClearImportedAt clears the value of the "imported_at" field.
func (_u *DownloadRecordUpdateOne) ClearImportedAt() *DownloadRecordUpdateOne {
	_u.mutation.ClearImportedAt()
	return _u
}

// SetIndexerName sets the "indexer_name" field.
func (_u *DownloadRecordUpdateOne) SetIndexerName(v string) *DownloadRecordUpdateOne {
	_u.mutation.SetIndexerName(v)
	return _u
}

// SetNillableIndexerName sets the "indexer_name" field if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableIndexerName(v *string) *DownloadRecordUpdateOne {
	if v != nil {
		_u.SetIndexerName(*v)
	}
	return _u
}

// ClearIndexerName clears the value of the "indexer_name" field.
func (_u *DownloadRecordUpdateOne) ClearIndexerName() *DownloadRecordUpdateOne {
	_u.mutation.ClearIndexerName()
	return _u
}

// SetDownloadClientName sets the "download_client_name" field.
func (_u *DownloadRecordUpdateOne) SetDownloadClientName(v string) *DownloadRecordUpdateOne {
	_u.mutation.SetDownloadClientName(v)
	return _u
}

// SetNillableDownloadClientName sets the "download_client_name" field if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableDownloadClientName(v *string) *DownloadRecordUpdateOne {
	if v != nil {
		_u.SetDownloadClientName(*v)
	}
	return _u
}

// ClearDownloadClientName clears the value of the "download_client_name" field.
func (_u *DownloadRecordUpdateOne) ClearDownloadClientName() *DownloadRecordUpdateOne {
	_u.mutation.ClearDownloadClientName()
	return _u
}

// SetReplaceExisting sets the "replace_existing" field.
func (_u *DownloadRecordUpdateOne) SetReplaceExisting(v bool) *DownloadRecordUpdateOne {
	_u.mutation.SetReplaceExisting(v)
	return _u
}

// SetNillableReplaceExisting sets the "replace_existing" field if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableReplaceExisting(v *bool) *DownloadRecordUpdateOne {
	if v != nil {
		_u.SetReplaceExisting(*v)
	}
	return _u
}

// SetMovieID sets the "movie" edge to the Movie entity by ID.
func (_u *DownloadRecordUpdateOne) SetMovieID(id uint32) *DownloadRecordUpdateOne {
	_u.mutation.SetMovieID(id)
	return _u
}

// SetNillableMovieID sets the "movie" edge to the Movie entity by ID if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableMovieID(id *uint32) *DownloadRecordUpdateOne {
	if id != nil {
		_u = _u.SetMovieID(*id)
	}
	return _u
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_u *DownloadRecordUpdateOne) SetMovie(v *Movie) *DownloadRecordUpdateOne {
	return _u.SetMovieID(v.ID)
}

// SetEpisodeID sets the "episode" edge to the Episode entity by ID.
func (_u *DownloadRecordUpdateOne) SetEpisodeID(id uint32) *DownloadRecordUpdateOne {
	_u.mutation.SetEpisodeID(id)
	return _u
}

// SetNillableEpisodeID sets the "episode" edge to the Episode entity by ID if the given value is not nil.
func (_u *DownloadRecordUpdateOne) SetNillableEpisodeID(id *uint32) *DownloadRecordUpdateOne {
	if id != nil {
		_u = _u.SetEpisodeID(*id)
	}
	return _u
}

// SetEpisode sets the "episode" edge to the Episode entity.
func (_u *DownloadRecordUpdateOne) SetEpisode(v *Episode) *DownloadRecordUpdateOne {
	return _u.SetEpisodeID(v.ID)
}

// Mutation returns the DownloadRecordMutation object of the builder.
func (_u *DownloadRecordUpdateOne) Mutation() *DownloadRecordMutation {
	return _u.mutation
}

// ClearMovie clears the "movie" edge to the Movie entity.
func (_u *DownloadRecordUpdateOne) ClearMovie() *DownloadRecordUpdateOne {
	_u.mutation.ClearMovie()
	return _u
}

// ClearEpisode clears the "episode" edge to the Episode entity.
func (_u *DownloadRecordUpdateOne) ClearEpisode() *DownloadRecordUpdateOne {
	_u.mutation.ClearEpisode()
	return _u
}

// Where appends a list predicates to the DownloadRecordUpdate builder.
func (_u *DownloadRecordUpdateOne) Where(ps ...predicate.DownloadRecord) *DownloadRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DownloadRecordUpdateOne) Select(field string, fields ...string) *DownloadRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DownloadRecord entity.
func (_u *DownloadRecordUpdateOne) Save(ctx context.Context) (*DownloadRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DownloadRecordUpdateOne) SaveX(ctx context.Context) *DownloadRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DownloadRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DownloadRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DownloadRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := downloadrecord.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DownloadRecordUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := downloadrecord.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "DownloadRecord.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := downloadrecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DownloadRecord.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DownloadRecordUpdateOne) sqlSave(ctx context.Context) (_node *DownloadRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(downloadrecord.Table, downloadrecord.Columns, sqlgraph.NewFieldSpec(downloadrecord.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DownloadRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, downloadrecord.FieldID)
		for _, f := range fields {
			if !downloadrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != downloadrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(downloadrecord.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(downloadrecord.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(downloadrecord.FieldQuality, field.TypeString, value)
	}
	if _u.mutation.QualityCleared() {
		_spec.ClearField(downloadrecord.FieldQuality, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(downloadrecord.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(downloadrecord.FieldSize, field.TypeInt64, value)
	}
	if _u.mutation.SizeCleared() {
		_spec.ClearField(downloadrecord.FieldSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(downloadrecord.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TorrentHash(); ok {
		_spec.SetField(downloadrecord.FieldTorrentHash, field.TypeString, value)
	}
	if _u.mutation.TorrentHashCleared() {
		_spec.ClearField(downloadrecord.FieldTorrentHash, field.TypeString)
	}
	if value, ok := _u.mutation.ReleaseGroup(); ok {
		_spec.SetField(downloadrecord.FieldReleaseGroup, field.TypeString, value)
	}
	if _u.mutation.ReleaseGroupCleared() {
		_spec.ClearField(downloadrecord.FieldReleaseGroup, field.TypeString)
	}
	if value, ok := _u.mutation.SavePath(); ok {
		_spec.SetField(downloadrecord.FieldSavePath, field.TypeString, value)
	}
	if _u.mutation.SavePathCleared() {
		_spec.ClearField(downloadrecord.FieldSavePath, field.TypeString)
	}
	if value, ok := _u.mutation.ImportAttempts(); ok {
		_spec.SetField(downloadrecord.FieldImportAttempts, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedImportAttempts(); ok {
		_spec.AddField(downloadrecord.FieldImportAttempts, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(downloadrecord.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(downloadrecord.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.ImportedAt(); ok {
		_spec.SetField(downloadrecord.FieldImportedAt, field.TypeTime, value)
	}
	if _u.mutation.ImportedAtCleared() {
		_spec.ClearField(downloadrecord.FieldImportedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IndexerName(); ok {
		_spec.SetField(downloadrecord.FieldIndexerName, field.TypeString, value)
	}
	if _u.mutation.IndexerNameCleared() {
		_spec.ClearField(downloadrecord.FieldIndexerName, field.TypeString)
	}
	if value, ok := _u.mutation.DownloadClientName(); ok {
		_spec.SetField(downloadrecord.FieldDownloadClientName, field.TypeString, value)
	}
	if _u.mutation.DownloadClientNameCleared() {
		_spec.ClearField(downloadrecord.FieldDownloadClientName, field.TypeString)
	}
	if value, ok := _u.mutation.ReplaceExisting(); ok {
		_spec.SetField(downloadrecord.FieldReplaceExisting, field.TypeBool, value)
	}
	if _u.mutation.MovieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadrecord.MovieTable,
			Columns: []string{downloadrecord.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadrecord.MovieTable,
			Columns: []string{downloadrecord.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EpisodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadrecord.EpisodeTable,
			Columns: []string{downloadrecord.EpisodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EpisodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadrecord.EpisodeTable,
			Columns: []string{downloadrecord.EpisodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DownloadRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{downloadrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
