// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datahearth/streamline/ent/episode"
	"github.com/datahearth/streamline/ent/mediaevent"
	"github.com/datahearth/streamline/ent/movie"
	"github.com/datahearth/streamline/ent/tvshow"
)

// MediaEventCreate is the builder for creating a MediaEvent entity.
type MediaEventCreate struct {
	config
	mutation *MediaEventMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *MediaEventCreate) SetCreateTime(v time.Time) *MediaEventCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *MediaEventCreate) SetNillableCreateTime(v *time.Time) *MediaEventCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *MediaEventCreate) SetUpdateTime(v time.Time) *MediaEventCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *MediaEventCreate) SetNillableUpdateTime(v *time.Time) *MediaEventCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *MediaEventCreate) SetType(v mediaevent.Type) *MediaEventCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *MediaEventCreate) SetPayload(v map[string]interface{}) *MediaEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MediaEventCreate) SetID(v uint32) *MediaEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetMovieID sets the "movie" edge to the Movie entity by ID.
func (_c *MediaEventCreate) SetMovieID(id uint32) *MediaEventCreate {
	_c.mutation.SetMovieID(id)
	return _c
}

// SetNillableMovieID sets the "movie" edge to the Movie entity by ID if the given value is not nil.
func (_c *MediaEventCreate) SetNillableMovieID(id *uint32) *MediaEventCreate {
	if id != nil {
		_c = _c.SetMovieID(*id)
	}
	return _c
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_c *MediaEventCreate) SetMovie(v *Movie) *MediaEventCreate {
	return _c.SetMovieID(v.ID)
}

// SetEpisodeID sets the "episode" edge to the Episode entity by ID.
func (_c *MediaEventCreate) SetEpisodeID(id uint32) *MediaEventCreate {
	_c.mutation.SetEpisodeID(id)
	return _c
}

// SetNillableEpisodeID sets the "episode" edge to the Episode entity by ID if the given value is not nil.
func (_c *MediaEventCreate) SetNillableEpisodeID(id *uint32) *MediaEventCreate {
	if id != nil {
		_c = _c.SetEpisodeID(*id)
	}
	return _c
}

// SetEpisode sets the "episode" edge to the Episode entity.
func (_c *MediaEventCreate) SetEpisode(v *Episode) *MediaEventCreate {
	return _c.SetEpisodeID(v.ID)
}

// SetTvShowID sets the "tv_show" edge to the TVShow entity by ID.
func (_c *MediaEventCreate) SetTvShowID(id uint32) *MediaEventCreate {
	_c.mutation.SetTvShowID(id)
	return _c
}

// SetNillableTvShowID sets the "tv_show" edge to the TVShow entity by ID if the given value is not nil.
func (_c *MediaEventCreate) SetNillableTvShowID(id *uint32) *MediaEventCreate {
	if id != nil {
		_c = _c.SetTvShowID(*id)
	}
	return _c
}

// SetTvShow sets the "tv_show" edge to the TVShow entity.
func (_c *MediaEventCreate) SetTvShow(v *TVShow) *MediaEventCreate {
	return _c.SetTvShowID(v.ID)
}

// Mutation returns the MediaEventMutation object of the builder.
func (_c *MediaEventCreate) Mutation() *MediaEventMutation {
	return _c.mutation
}

// Save creates the MediaEvent in the database.
func (_c *MediaEventCreate) Save(ctx context.Context) (*MediaEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaEventCreate) SaveX(ctx context.Context) *MediaEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaEventCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := mediaevent.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := mediaevent.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaEventCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "MediaEvent.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "MediaEvent.update_time"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "MediaEvent.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := mediaevent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "MediaEvent.type": %w`, err)}
		}
	}
	return nil
}

func (_c *MediaEventCreate) sqlSave(ctx context.Context) (*MediaEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaEventCreate) createSpec() (*MediaEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediaevent.Table, sqlgraph.NewFieldSpec(mediaevent.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(mediaevent.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(mediaevent.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(mediaevent.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(mediaevent.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if nodes := _c.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaevent.MovieTable,
			Columns: []string{mediaevent.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.movie_events = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EpisodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaevent.EpisodeTable,
			Columns: []string{mediaevent.EpisodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.episode_events = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TvShowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaevent.TvShowTable,
			Columns: []string{mediaevent.TvShowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tvshow.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tv_show_events = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MediaEventCreateBulk is the builder for creating many MediaEvent entities in bulk.
type MediaEventCreateBulk struct {
	config
	err      error
	builders []*MediaEventCreate
}

// Save creates the MediaEvent entities in the database.
func (_c *MediaEventCreateBulk) Save(ctx context.Context) ([]*MediaEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaEventCreateBulk) SaveX(ctx context.Context) []*MediaEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
