// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datahearth/streamline/ent/credit"
	"github.com/datahearth/streamline/ent/person"
)

// PersonCreate is the builder for creating a Person entity.
type PersonCreate struct {
	config
	mutation *PersonMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *PersonCreate) SetCreateTime(v time.Time) *PersonCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *PersonCreate) SetNillableCreateTime(v *time.Time) *PersonCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *PersonCreate) SetUpdateTime(v time.Time) *PersonCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *PersonCreate) SetNillableUpdateTime(v *time.Time) *PersonCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetTmdbID sets the "tmdb_id" field.
func (_c *PersonCreate) SetTmdbID(v uint32) *PersonCreate {
	_c.mutation.SetTmdbID(v)
	return _c
}

// SetNillableTmdbID sets the "tmdb_id" field if the given value is not nil.
func (_c *PersonCreate) SetNillableTmdbID(v *uint32) *PersonCreate {
	if v != nil {
		_c.SetTmdbID(*v)
	}
	return _c
}

// SetTvdbID sets the "tvdb_id" field.
func (_c *PersonCreate) SetTvdbID(v uint32) *PersonCreate {
	_c.mutation.SetTvdbID(v)
	return _c
}

// SetNillableTvdbID sets the "tvdb_id" field if the given value is not nil.
func (_c *PersonCreate) SetNillableTvdbID(v *uint32) *PersonCreate {
	if v != nil {
		_c.SetTvdbID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PersonCreate) SetName(v string) *PersonCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetProfileURL sets the "profile_url" field.
func (_c *PersonCreate) SetProfileURL(v string) *PersonCreate {
	_c.mutation.SetProfileURL(v)
	return _c
}

// SetNillableProfileURL sets the "profile_url" field if the given value is not nil.
func (_c *PersonCreate) SetNillableProfileURL(v *string) *PersonCreate {
	if v != nil {
		_c.SetProfileURL(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PersonCreate) SetID(v uint32) *PersonCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddCreditIDs adds the "credits" edge to the Credit entity by IDs.
func (_c *PersonCreate) AddCreditIDs(ids ...uint32) *PersonCreate {
	_c.mutation.AddCreditIDs(ids...)
	return _c
}

// AddCredits adds the "credits" edges to the Credit entity.
func (_c *PersonCreate) AddCredits(v ...*Credit) *PersonCreate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCreditIDs(ids...)
}

// Mutation returns the PersonMutation object of the builder.
func (_c *PersonCreate) Mutation() *PersonMutation {
	return _c.mutation
}

// Save creates the Person in the database.
func (_c *PersonCreate) Save(ctx context.Context) (*Person, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PersonCreate) SaveX(ctx context.Context) *Person {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PersonCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := person.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := person.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.TmdbID(); !ok {
		v := person.DefaultTmdbID
		_c.mutation.SetTmdbID(v)
	}
	if _, ok := _c.mutation.TvdbID(); !ok {
		v := person.DefaultTvdbID
		_c.mutation.SetTvdbID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PersonCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Person.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Person.update_time"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Person.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := person.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Person.name": %w`, err)}
		}
	}
	return nil
}

func (_c *PersonCreate) sqlSave(ctx context.Context) (*Person, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PersonCreate) createSpec() (*Person, *sqlgraph.CreateSpec) {
	var (
		_node = &Person{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(person.Table, sqlgraph.NewFieldSpec(person.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(person.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(person.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.TmdbID(); ok {
		_spec.SetField(person.FieldTmdbID, field.TypeUint32, value)
		_node.TmdbID = value
	}
	if value, ok := _c.mutation.TvdbID(); ok {
		_spec.SetField(person.FieldTvdbID, field.TypeUint32, value)
		_node.TvdbID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(person.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ProfileURL(); ok {
		_spec.SetField(person.FieldProfileURL, field.TypeString, value)
		_node.ProfileURL = value
	}
	if nodes := _c.mutation.CreditsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.CreditsTable,
			Columns: []string{person.CreditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credit.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PersonCreateBulk is the builder for creating many Person entities in bulk.
type PersonCreateBulk struct {
	config
	err      error
	builders []*PersonCreate
}

// Save creates the Person entities in the database.
func (_c *PersonCreateBulk) Save(ctx context.Context) ([]*Person, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Person, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PersonMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PersonCreateBulk) SaveX(ctx context.Context) []*Person {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
