// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datahearth/streamline/ent/credit"
	"github.com/datahearth/streamline/ent/person"
	"github.com/datahearth/streamline/ent/predicate"
)

// PersonUpdate is the builder for updating Person entities.
type PersonUpdate struct {
	config
	hooks     []Hook
	mutation  *PersonMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PersonUpdate builder.
func (_u *PersonUpdate) Where(ps ...predicate.Person) *PersonUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *PersonUpdate) SetUpdateTime(v time.Time) *PersonUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTmdbID sets the "tmdb_id" field.
func (_u *PersonUpdate) SetTmdbID(v uint32) *PersonUpdate {
	_u.mutation.ResetTmdbID()
	_u.mutation.SetTmdbID(v)
	return _u
}

// SetNillableTmdbID sets the "tmdb_id" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableTmdbID(v *uint32) *PersonUpdate {
	if v != nil {
		_u.SetTmdbID(*v)
	}
	return _u
}

// AddTmdbID adds value to the "tmdb_id" field.
func (_u *PersonUpdate) AddTmdbID(v int32) *PersonUpdate {
	_u.mutation.AddTmdbID(v)
	return _u
}

// ClearTmdbID clears the value of the "tmdb_id" field.
func (_u *PersonUpdate) ClearTmdbID() *PersonUpdate {
	_u.mutation.ClearTmdbID()
	return _u
}

// SetTvdbID sets the "tvdb_id" field.
func (_u *PersonUpdate) SetTvdbID(v uint32) *PersonUpdate {
	_u.mutation.ResetTvdbID()
	_u.mutation.SetTvdbID(v)
	return _u
}

// SetNillableTvdbID sets the "tvdb_id" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableTvdbID(v *uint32) *PersonUpdate {
	if v != nil {
		_u.SetTvdbID(*v)
	}
	return _u
}

// AddTvdbID adds value to the "tvdb_id" field.
func (_u *PersonUpdate) AddTvdbID(v int32) *PersonUpdate {
	_u.mutation.AddTvdbID(v)
	return _u
}

// ClearTvdbID clears the value of the "tvdb_id" field.
func (_u *PersonUpdate) ClearTvdbID() *PersonUpdate {
	_u.mutation.ClearTvdbID()
	return _u
}

// SetName sets the "name" field.
func (_u *PersonUpdate) SetName(v string) *PersonUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableName(v *string) *PersonUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProfileURL sets the "profile_url" field.
func (_u *PersonUpdate) SetProfileURL(v string) *PersonUpdate {
	_u.mutation.SetProfileURL(v)
	return _u
}

// SetNillableProfileURL sets the "profile_url" field if the given value is not nil.
func (_u *PersonUpdate) SetNillableProfileURL(v *string) *PersonUpdate {
	if v != nil {
		_u.SetProfileURL(*v)
	}
	return _u
}

// ClearProfileURL clears the value of the "profile_url" field.
func (_u *PersonUpdate) ClearProfileURL() *PersonUpdate {
	_u.mutation.ClearProfileURL()
	return _u
}

// AddCreditIDs adds the "credits" edge to the Credit entity by IDs.
func (_u *PersonUpdate) AddCreditIDs(ids ...uint32) *PersonUpdate {
	_u.mutation.AddCreditIDs(ids...)
	return _u
}

// AddCredits adds the "credits" edges to the Credit entity.
func (_u *PersonUpdate) AddCredits(v ...*Credit) *PersonUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreditIDs(ids...)
}

// Mutation returns the PersonMutation object of the builder.
func (_u *PersonUpdate) Mutation() *PersonMutation {
	return _u.mutation
}

// ClearCredits clears all "credits" edges to the Credit entity.
func (_u *PersonUpdate) ClearCredits() *PersonUpdate {
	_u.mutation.ClearCredits()
	return _u
}

// RemoveCreditIDs removes the "credits" edge to Credit entities by IDs.
func (_u *PersonUpdate) RemoveCreditIDs(ids ...uint32) *PersonUpdate {
	_u.mutation.RemoveCreditIDs(ids...)
	return _u
}

// RemoveCredits removes "credits" edges to Credit entities.
func (_u *PersonUpdate) RemoveCredits(v ...*Credit) *PersonUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreditIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PersonUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PersonUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PersonUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := person.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := person.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Person.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PersonUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PersonUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PersonUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(person.Table, person.Columns, sqlgraph.NewFieldSpec(person.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(person.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TmdbID(); ok {
		_spec.SetField(person.FieldTmdbID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTmdbID(); ok {
		_spec.AddField(person.FieldTmdbID, field.TypeUint32, value)
	}
	if _u.mutation.TmdbIDCleared() {
		_spec.ClearField(person.FieldTmdbID, field.TypeUint32)
	}
	if value, ok := _u.mutation.TvdbID(); ok {
		_spec.SetField(person.FieldTvdbID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTvdbID(); ok {
		_spec.AddField(person.FieldTvdbID, field.TypeUint32, value)
	}
	if _u.mutation.TvdbIDCleared() {
		_spec.ClearField(person.FieldTvdbID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(person.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfileURL(); ok {
		_spec.SetField(person.FieldProfileURL, field.TypeString, value)
	}
	if _u.mutation.ProfileURLCleared() {
		_spec.ClearField(person.FieldProfileURL, field.TypeString)
	}
	if _u.mutation.CreditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.CreditsTable,
			Columns: []string{person.CreditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credit.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreditsIDs(); len(nodes) > 0 && !_u.mutation.CreditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.CreditsTable,
			Columns: []string{person.CreditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credit.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreditsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.CreditsTable,
			Columns: []string{person.CreditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credit.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{person.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PersonUpdateOne is the builder for updating a single Person entity.
type PersonUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PersonMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *PersonUpdateOne) SetUpdateTime(v time.Time) *PersonUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTmdbID sets the "tmdb_id" field.
func (_u *PersonUpdateOne) SetTmdbID(v uint32) *PersonUpdateOne {
	_u.mutation.ResetTmdbID()
	_u.mutation.SetTmdbID(v)
	return _u
}

// SetNillableTmdbID sets the "tmdb_id" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableTmdbID(v *uint32) *PersonUpdateOne {
	if v != nil {
		_u.SetTmdbID(*v)
	}
	return _u
}

// AddTmdbID adds value to the "tmdb_id" field.
func (_u *PersonUpdateOne) AddTmdbID(v int32) *PersonUpdateOne {
	_u.mutation.AddTmdbID(v)
	return _u
}

// ClearTmdbID clears the value of the "tmdb_id" field.
func (_u *PersonUpdateOne) ClearTmdbID() *PersonUpdateOne {
	_u.mutation.ClearTmdbID()
	return _u
}

// SetTvdbID sets the "tvdb_id" field.
func (_u *PersonUpdateOne) SetTvdbID(v uint32) *PersonUpdateOne {
	_u.mutation.ResetTvdbID()
	_u.mutation.SetTvdbID(v)
	return _u
}

// SetNillableTvdbID sets the "tvdb_id" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableTvdbID(v *uint32) *PersonUpdateOne {
	if v != nil {
		_u.SetTvdbID(*v)
	}
	return _u
}

// AddTvdbID adds value to the "tvdb_id" field.
func (_u *PersonUpdateOne) AddTvdbID(v int32) *PersonUpdateOne {
	_u.mutation.AddTvdbID(v)
	return _u
}

// ClearTvdbID clears the value of the "tvdb_id" field.
func (_u *PersonUpdateOne) ClearTvdbID() *PersonUpdateOne {
	_u.mutation.ClearTvdbID()
	return _u
}

// SetName sets the "name" field.
func (_u *PersonUpdateOne) SetName(v string) *PersonUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableName(v *string) *PersonUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProfileURL sets the "profile_url" field.
func (_u *PersonUpdateOne) SetProfileURL(v string) *PersonUpdateOne {
	_u.mutation.SetProfileURL(v)
	return _u
}

// SetNillableProfileURL sets the "profile_url" field if the given value is not nil.
func (_u *PersonUpdateOne) SetNillableProfileURL(v *string) *PersonUpdateOne {
	if v != nil {
		_u.SetProfileURL(*v)
	}
	return _u
}

// ClearProfileURL clears the value of the "profile_url" field.
func (_u *PersonUpdateOne) ClearProfileURL() *PersonUpdateOne {
	_u.mutation.ClearProfileURL()
	return _u
}

// AddCreditIDs adds the "credits" edge to the Credit entity by IDs.
func (_u *PersonUpdateOne) AddCreditIDs(ids ...uint32) *PersonUpdateOne {
	_u.mutation.AddCreditIDs(ids...)
	return _u
}

// AddCredits adds the "credits" edges to the Credit entity.
func (_u *PersonUpdateOne) AddCredits(v ...*Credit) *PersonUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreditIDs(ids...)
}

// Mutation returns the PersonMutation object of the builder.
func (_u *PersonUpdateOne) Mutation() *PersonMutation {
	return _u.mutation
}

// ClearCredits clears all "credits" edges to the Credit entity.
func (_u *PersonUpdateOne) ClearCredits() *PersonUpdateOne {
	_u.mutation.ClearCredits()
	return _u
}

// RemoveCreditIDs removes the "credits" edge to Credit entities by IDs.
func (_u *PersonUpdateOne) RemoveCreditIDs(ids ...uint32) *PersonUpdateOne {
	_u.mutation.RemoveCreditIDs(ids...)
	return _u
}

// RemoveCredits removes "credits" edges to Credit entities.
func (_u *PersonUpdateOne) RemoveCredits(v ...*Credit) *PersonUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreditIDs(ids...)
}

// Where appends a list predicates to the PersonUpdate builder.
func (_u *PersonUpdateOne) Where(ps ...predicate.Person) *PersonUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PersonUpdateOne) Select(field string, fields ...string) *PersonUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Person entity.
func (_u *PersonUpdateOne) Save(ctx context.Context) (*Person, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonUpdateOne) SaveX(ctx context.Context) *Person {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PersonUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PersonUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := person.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := person.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Person.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PersonUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PersonUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PersonUpdateOne) sqlSave(ctx context.Context) (_node *Person, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(person.Table, person.Columns, sqlgraph.NewFieldSpec(person.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Person.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, person.FieldID)
		for _, f := range fields {
			if !person.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != person.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(person.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TmdbID(); ok {
		_spec.SetField(person.FieldTmdbID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTmdbID(); ok {
		_spec.AddField(person.FieldTmdbID, field.TypeUint32, value)
	}
	if _u.mutation.TmdbIDCleared() {
		_spec.ClearField(person.FieldTmdbID, field.TypeUint32)
	}
	if value, ok := _u.mutation.TvdbID(); ok {
		_spec.SetField(person.FieldTvdbID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTvdbID(); ok {
		_spec.AddField(person.FieldTvdbID, field.TypeUint32, value)
	}
	if _u.mutation.TvdbIDCleared() {
		_spec.ClearField(person.FieldTvdbID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(person.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfileURL(); ok {
		_spec.SetField(person.FieldProfileURL, field.TypeString, value)
	}
	if _u.mutation.ProfileURLCleared() {
		_spec.ClearField(person.FieldProfileURL, field.TypeString)
	}
	if _u.mutation.CreditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.CreditsTable,
			Columns: []string{person.CreditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credit.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreditsIDs(); len(nodes) > 0 && !_u.mutation.CreditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.CreditsTable,
			Columns: []string{person.CreditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credit.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreditsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.CreditsTable,
			Columns: []string{person.CreditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credit.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Person{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{person.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
