// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/datahearth/streamline/ent/person"
)

// Person is the model entity for the Person schema.
type Person struct {
	config `json:"-"`
	// ID of the ent.
	ID uint32 `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// TmdbID holds the value of the "tmdb_id" field.
	TmdbID uint32 `json:"tmdb_id,omitempty"`
	// TvdbID holds the value of the "tvdb_id" field.
	TvdbID uint32 `json:"tvdb_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ProfileURL holds the value of the "profile_url" field.
	ProfileURL string `json:"profile_url,omitempty"`
	// Biography holds the value of the "biography" field.
	Biography string `json:"biography,omitempty"`
	// KnownFor holds the value of the "known_for" field.
	KnownFor string `json:"known_for,omitempty"`
	// Birthday holds the value of the "birthday" field.
	Birthday string `json:"birthday,omitempty"`
	// Deathday holds the value of the "deathday" field.
	Deathday string `json:"deathday,omitempty"`
	// PlaceOfBirth holds the value of the "place_of_birth" field.
	PlaceOfBirth string `json:"place_of_birth,omitempty"`
	// ImdbID holds the value of the "imdb_id" field.
	ImdbID string `json:"imdb_id,omitempty"`
	// InstagramID holds the value of the "instagram_id" field.
	InstagramID string `json:"instagram_id,omitempty"`
	// TwitterID holds the value of the "twitter_id" field.
	TwitterID string `json:"twitter_id,omitempty"`
	// DetailsFetchedAt holds the value of the "details_fetched_at" field.
	DetailsFetchedAt *time.Time `json:"details_fetched_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PersonQuery when eager-loading is set.
	Edges        PersonEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PersonEdges holds the relations/edges for other nodes in the graph.
type PersonEdges struct {
	// Credits holds the value of the credits edge.
	Credits []*Credit `json:"credits,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CreditsOrErr returns the Credits value or an error if the edge
// was not loaded in eager-loading.
func (e PersonEdges) CreditsOrErr() ([]*Credit, error) {
	if e.loadedTypes[0] {
		return e.Credits, nil
	}
	return nil, &NotLoadedError{edge: "credits"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Person) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case person.FieldID, person.FieldTmdbID, person.FieldTvdbID:
			values[i] = new(sql.NullInt64)
		case person.FieldName, person.FieldProfileURL, person.FieldBiography, person.FieldKnownFor, person.FieldBirthday, person.FieldDeathday, person.FieldPlaceOfBirth, person.FieldImdbID, person.FieldInstagramID, person.FieldTwitterID:
			values[i] = new(sql.NullString)
		case person.FieldCreateTime, person.FieldUpdateTime, person.FieldDetailsFetchedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Person fields.
func (_m *Person) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case person.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case person.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case person.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case person.FieldTmdbID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tmdb_id", values[i])
			} else if value.Valid {
				_m.TmdbID = uint32(value.Int64)
			}
		case person.FieldTvdbID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tvdb_id", values[i])
			} else if value.Valid {
				_m.TvdbID = uint32(value.Int64)
			}
		case person.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case person.FieldProfileURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_url", values[i])
			} else if value.Valid {
				_m.ProfileURL = value.String
			}
		case person.FieldBiography:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field biography", values[i])
			} else if value.Valid {
				_m.Biography = value.String
			}
		case person.FieldKnownFor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field known_for", values[i])
			} else if value.Valid {
				_m.KnownFor = value.String
			}
		case person.FieldBirthday:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field birthday", values[i])
			} else if value.Valid {
				_m.Birthday = value.String
			}
		case person.FieldDeathday:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deathday", values[i])
			} else if value.Valid {
				_m.Deathday = value.String
			}
		case person.FieldPlaceOfBirth:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field place_of_birth", values[i])
			} else if value.Valid {
				_m.PlaceOfBirth = value.String
			}
		case person.FieldImdbID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field imdb_id", values[i])
			} else if value.Valid {
				_m.ImdbID = value.String
			}
		case person.FieldInstagramID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field instagram_id", values[i])
			} else if value.Valid {
				_m.InstagramID = value.String
			}
		case person.FieldTwitterID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field twitter_id", values[i])
			} else if value.Valid {
				_m.TwitterID = value.String
			}
		case person.FieldDetailsFetchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field details_fetched_at", values[i])
			} else if value.Valid {
				_m.DetailsFetchedAt = new(time.Time)
				*_m.DetailsFetchedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Person.
// This includes values selected through modifiers, order, etc.
func (_m *Person) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCredits queries the "credits" edge of the Person entity.
func (_m *Person) QueryCredits() *CreditQuery {
	return NewPersonClient(_m.config).QueryCredits(_m)
}

// Update returns a builder for updating this Person.
// Note that you need to call Person.Unwrap() before calling this method if this Person
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Person) Update() *PersonUpdateOne {
	return NewPersonClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Person entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Person) Unwrap() *Person {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Person is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Person) String() string {
	var builder strings.Builder
	builder.WriteString("Person(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tmdb_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TmdbID))
	builder.WriteString(", ")
	builder.WriteString("tvdb_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TvdbID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("profile_url=")
	builder.WriteString(_m.ProfileURL)
	builder.WriteString(", ")
	builder.WriteString("biography=")
	builder.WriteString(_m.Biography)
	builder.WriteString(", ")
	builder.WriteString("known_for=")
	builder.WriteString(_m.KnownFor)
	builder.WriteString(", ")
	builder.WriteString("birthday=")
	builder.WriteString(_m.Birthday)
	builder.WriteString(", ")
	builder.WriteString("deathday=")
	builder.WriteString(_m.Deathday)
	builder.WriteString(", ")
	builder.WriteString("place_of_birth=")
	builder.WriteString(_m.PlaceOfBirth)
	builder.WriteString(", ")
	builder.WriteString("imdb_id=")
	builder.WriteString(_m.ImdbID)
	builder.WriteString(", ")
	builder.WriteString("instagram_id=")
	builder.WriteString(_m.InstagramID)
	builder.WriteString(", ")
	builder.WriteString("twitter_id=")
	builder.WriteString(_m.TwitterID)
	builder.WriteString(", ")
	if v := _m.DetailsFetchedAt; v != nil {
		builder.WriteString("details_fetched_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Persons is a parsable slice of Person.
type Persons []*Person
