// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/datahearth/streamline/ent/scheduledjob"
)

// ScheduledJob is the model entity for the ScheduledJob schema.
type ScheduledJob struct {
	config `json:"-"`
	// ID of the ent.
	ID uint32 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Paused holds the value of the "paused" field.
	Paused bool `json:"paused,omitempty"`
	// LastStartedAt holds the value of the "last_started_at" field.
	LastStartedAt *time.Time `json:"last_started_at,omitempty"`
	// LastFinishedAt holds the value of the "last_finished_at" field.
	LastFinishedAt *time.Time `json:"last_finished_at,omitempty"`
	// LastStatus holds the value of the "last_status" field.
	LastStatus scheduledjob.LastStatus `json:"last_status,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// LastDurationMs holds the value of the "last_duration_ms" field.
	LastDurationMs uint32 `json:"last_duration_ms,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScheduledJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case scheduledjob.FieldPaused:
			values[i] = new(sql.NullBool)
		case scheduledjob.FieldID, scheduledjob.FieldLastDurationMs:
			values[i] = new(sql.NullInt64)
		case scheduledjob.FieldName, scheduledjob.FieldLastStatus, scheduledjob.FieldLastError:
			values[i] = new(sql.NullString)
		case scheduledjob.FieldLastStartedAt, scheduledjob.FieldLastFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScheduledJob fields.
func (_m *ScheduledJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scheduledjob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case scheduledjob.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case scheduledjob.FieldPaused:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field paused", values[i])
			} else if value.Valid {
				_m.Paused = value.Bool
			}
		case scheduledjob.FieldLastStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_started_at", values[i])
			} else if value.Valid {
				_m.LastStartedAt = new(time.Time)
				*_m.LastStartedAt = value.Time
			}
		case scheduledjob.FieldLastFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_finished_at", values[i])
			} else if value.Valid {
				_m.LastFinishedAt = new(time.Time)
				*_m.LastFinishedAt = value.Time
			}
		case scheduledjob.FieldLastStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_status", values[i])
			} else if value.Valid {
				_m.LastStatus = scheduledjob.LastStatus(value.String)
			}
		case scheduledjob.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case scheduledjob.FieldLastDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_duration_ms", values[i])
			} else if value.Valid {
				_m.LastDurationMs = uint32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScheduledJob.
// This includes values selected through modifiers, order, etc.
func (_m *ScheduledJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ScheduledJob.
// Note that you need to call ScheduledJob.Unwrap() before calling this method if this ScheduledJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScheduledJob) Update() *ScheduledJobUpdateOne {
	return NewScheduledJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScheduledJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScheduledJob) Unwrap() *ScheduledJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScheduledJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScheduledJob) String() string {
	var builder strings.Builder
	builder.WriteString("ScheduledJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("paused=")
	builder.WriteString(fmt.Sprintf("%v", _m.Paused))
	builder.WriteString(", ")
	if v := _m.LastStartedAt; v != nil {
		builder.WriteString("last_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastFinishedAt; v != nil {
		builder.WriteString("last_finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastStatus))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("last_duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastDurationMs))
	builder.WriteByte(')')
	return builder.String()
}

// ScheduledJobs is a parsable slice of ScheduledJob.
type ScheduledJobs []*ScheduledJob
