// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/datahearth/streamline/ent/torrentsession"
)

// TorrentSessionCreate is the builder for creating a TorrentSession entity.
type TorrentSessionCreate struct {
	config
	mutation *TorrentSessionMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *TorrentSessionCreate) SetCreateTime(v time.Time) *TorrentSessionCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *TorrentSessionCreate) SetNillableCreateTime(v *time.Time) *TorrentSessionCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *TorrentSessionCreate) SetUpdateTime(v time.Time) *TorrentSessionCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *TorrentSessionCreate) SetNillableUpdateTime(v *time.Time) *TorrentSessionCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetInfoHash sets the "info_hash" field.
func (_c *TorrentSessionCreate) SetInfoHash(v string) *TorrentSessionCreate {
	_c.mutation.SetInfoHash(v)
	return _c
}

// SetName sets the "name" field.
func (_c *TorrentSessionCreate) SetName(v string) *TorrentSessionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *TorrentSessionCreate) SetNillableName(v *string) *TorrentSessionCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetSavePath sets the "save_path" field.
func (_c *TorrentSessionCreate) SetSavePath(v string) *TorrentSessionCreate {
	_c.mutation.SetSavePath(v)
	return _c
}

// SetSourceMagnet sets the "source_magnet" field.
func (_c *TorrentSessionCreate) SetSourceMagnet(v string) *TorrentSessionCreate {
	_c.mutation.SetSourceMagnet(v)
	return _c
}

// SetNillableSourceMagnet sets the "source_magnet" field if the given value is not nil.
func (_c *TorrentSessionCreate) SetNillableSourceMagnet(v *string) *TorrentSessionCreate {
	if v != nil {
		_c.SetSourceMagnet(*v)
	}
	return _c
}

// SetSourceTorrent sets the "source_torrent" field.
func (_c *TorrentSessionCreate) SetSourceTorrent(v []byte) *TorrentSessionCreate {
	_c.mutation.SetSourceTorrent(v)
	return _c
}

// SetPaused sets the "paused" field.
func (_c *TorrentSessionCreate) SetPaused(v bool) *TorrentSessionCreate {
	_c.mutation.SetPaused(v)
	return _c
}

// SetNillablePaused sets the "paused" field if the given value is not nil.
func (_c *TorrentSessionCreate) SetNillablePaused(v *bool) *TorrentSessionCreate {
	if v != nil {
		_c.SetPaused(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *TorrentSessionCreate) SetCompletedAt(v time.Time) *TorrentSessionCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *TorrentSessionCreate) SetNillableCompletedAt(v *time.Time) *TorrentSessionCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetSeedStopped sets the "seed_stopped" field.
func (_c *TorrentSessionCreate) SetSeedStopped(v bool) *TorrentSessionCreate {
	_c.mutation.SetSeedStopped(v)
	return _c
}

// SetNillableSeedStopped sets the "seed_stopped" field if the given value is not nil.
func (_c *TorrentSessionCreate) SetNillableSeedStopped(v *bool) *TorrentSessionCreate {
	if v != nil {
		_c.SetSeedStopped(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TorrentSessionCreate) SetID(v uint32) *TorrentSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TorrentSessionMutation object of the builder.
func (_c *TorrentSessionCreate) Mutation() *TorrentSessionMutation {
	return _c.mutation
}

// Save creates the TorrentSession in the database.
func (_c *TorrentSessionCreate) Save(ctx context.Context) (*TorrentSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TorrentSessionCreate) SaveX(ctx context.Context) *TorrentSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TorrentSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TorrentSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TorrentSessionCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := torrentsession.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := torrentsession.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Paused(); !ok {
		v := torrentsession.DefaultPaused
		_c.mutation.SetPaused(v)
	}
	if _, ok := _c.mutation.SeedStopped(); !ok {
		v := torrentsession.DefaultSeedStopped
		_c.mutation.SetSeedStopped(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TorrentSessionCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "TorrentSession.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "TorrentSession.update_time"`)}
	}
	if _, ok := _c.mutation.InfoHash(); !ok {
		return &ValidationError{Name: "info_hash", err: errors.New(`ent: missing required field "TorrentSession.info_hash"`)}
	}
	if v, ok := _c.mutation.InfoHash(); ok {
		if err := torrentsession.InfoHashValidator(v); err != nil {
			return &ValidationError{Name: "info_hash", err: fmt.Errorf(`ent: validator failed for field "TorrentSession.info_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SavePath(); !ok {
		return &ValidationError{Name: "save_path", err: errors.New(`ent: missing required field "TorrentSession.save_path"`)}
	}
	if v, ok := _c.mutation.SavePath(); ok {
		if err := torrentsession.SavePathValidator(v); err != nil {
			return &ValidationError{Name: "save_path", err: fmt.Errorf(`ent: validator failed for field "TorrentSession.save_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Paused(); !ok {
		return &ValidationError{Name: "paused", err: errors.New(`ent: missing required field "TorrentSession.paused"`)}
	}
	if _, ok := _c.mutation.SeedStopped(); !ok {
		return &ValidationError{Name: "seed_stopped", err: errors.New(`ent: missing required field "TorrentSession.seed_stopped"`)}
	}
	return nil
}

func (_c *TorrentSessionCreate) sqlSave(ctx context.Context) (*TorrentSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TorrentSessionCreate) createSpec() (*TorrentSession, *sqlgraph.CreateSpec) {
	var (
		_node = &TorrentSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(torrentsession.Table, sqlgraph.NewFieldSpec(torrentsession.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(torrentsession.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(torrentsession.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.InfoHash(); ok {
		_spec.SetField(torrentsession.FieldInfoHash, field.TypeString, value)
		_node.InfoHash = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(torrentsession.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SavePath(); ok {
		_spec.SetField(torrentsession.FieldSavePath, field.TypeString, value)
		_node.SavePath = value
	}
	if value, ok := _c.mutation.SourceMagnet(); ok {
		_spec.SetField(torrentsession.FieldSourceMagnet, field.TypeString, value)
		_node.SourceMagnet = value
	}
	if value, ok := _c.mutation.SourceTorrent(); ok {
		_spec.SetField(torrentsession.FieldSourceTorrent, field.TypeBytes, value)
		_node.SourceTorrent = value
	}
	if value, ok := _c.mutation.Paused(); ok {
		_spec.SetField(torrentsession.FieldPaused, field.TypeBool, value)
		_node.Paused = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(torrentsession.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.SeedStopped(); ok {
		_spec.SetField(torrentsession.FieldSeedStopped, field.TypeBool, value)
		_node.SeedStopped = value
	}
	return _node, _spec
}

// TorrentSessionCreateBulk is the builder for creating many TorrentSession entities in bulk.
type TorrentSessionCreateBulk struct {
	config
	err      error
	builders []*TorrentSessionCreate
}

// Save creates the TorrentSession entities in the database.
func (_c *TorrentSessionCreateBulk) Save(ctx context.Context) ([]*TorrentSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TorrentSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TorrentSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TorrentSessionCreateBulk) SaveX(ctx context.Context) []*TorrentSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TorrentSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TorrentSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
