// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/datahearth/streamline/internal/indexer"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Feed provides a mock function for the type MockClient
func (_mock *MockClient) Feed(ctx context.Context) ([]indexer.SearchResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Feed")
	}

	var r0 []indexer.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]indexer.SearchResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []indexer.SearchResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]indexer.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Feed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Feed'
type MockClient_Feed_Call struct {
	*mock.Call
}

// Feed is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Feed(ctx any) *MockClient_Feed_Call {
	return &MockClient_Feed_Call{Call: _e.mock.On("Feed", ctx)}
}

func (_c *MockClient_Feed_Call) Run(run func(ctx context.Context)) *MockClient_Feed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Feed_Call) Return(searchResults []indexer.SearchResult, err error) *MockClient_Feed_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *MockClient_Feed_Call) RunAndReturn(run func(ctx context.Context) ([]indexer.SearchResult, error)) *MockClient_Feed_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockClient
func (_mock *MockClient) Search(ctx context.Context, params indexer.SearchParams) ([]indexer.SearchResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []indexer.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, indexer.SearchParams) ([]indexer.SearchResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, indexer.SearchParams) []indexer.SearchResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]indexer.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, indexer.SearchParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockClient_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - params indexer.SearchParams
func (_e *MockClient_Expecter) Search(ctx any, params any) *MockClient_Search_Call {
	return &MockClient_Search_Call{Call: _e.mock.On("Search", ctx, params)}
}

func (_c *MockClient_Search_Call) Run(run func(ctx context.Context, params indexer.SearchParams)) *MockClient_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 indexer.SearchParams
		if args[1] != nil {
			arg1 = args[1].(indexer.SearchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Search_Call) Return(searchResults []indexer.SearchResult, err error) *MockClient_Search_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *MockClient_Search_Call) RunAndReturn(run func(ctx context.Context, params indexer.SearchParams) ([]indexer.SearchResult, error)) *MockClient_Search_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function for the type MockClient
func (_mock *MockClient) TestConnection(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type MockClient_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) TestConnection(ctx any) *MockClient_TestConnection_Call {
	return &MockClient_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx)}
}

func (_c *MockClient_TestConnection_Call) Run(run func(ctx context.Context)) *MockClient_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_TestConnection_Call) Return(err error) *MockClient_TestConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_TestConnection_Call) RunAndReturn(run func(ctx context.Context) error) *MockClient_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}
