package auth

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"log/slog"
	"sync"
	"sync/atomic"
	"time"

	"github.com/datahearth/streamline/ent"
	"github.com/datahearth/streamline/ent/user"
	"github.com/datahearth/streamline/internal/config"
	"github.com/datahearth/streamline/internal/db"
	"github.com/datahearth/streamline/internal/otelx"
	approle "github.com/datahearth/streamline/internal/role"
	"github.com/golang-jwt/jwt/v5"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"
	"golang.org/x/crypto/bcrypt"
)

var (
	tracer = otel.Tracer("github.com/datahearth/streamline/internal/auth")
	meter  = otel.Meter("github.com/datahearth/streamline/internal/auth")

	logins        metric.Int64Counter
	registrations metric.Int64Counter
	apiKeys       metric.Int64Counter
	oidcLogins    metric.Int64Counter
)

func init() {
	logins = otelx.Must(meter.Int64Counter(
		"streamline.auth.logins",
		metric.WithDescription("Login attempts by method + outcome"),
	))
	registrations = otelx.Must(meter.Int64Counter(
		"streamline.auth.registrations",
		metric.WithDescription("User registrations by method + outcome"),
	))
	apiKeys = otelx.Must(meter.Int64Counter(
		"streamline.auth.api_keys_created",
		metric.WithDescription("Number of API keys created"),
	))
	oidcLogins = otelx.Must(meter.Int64Counter(
		"streamline.auth.oidc.logins",
		metric.WithDescription("OIDC login outcomes by provider"),
	))

	ctx := context.Background()
	logins.Add(ctx, 0)
	registrations.Add(ctx, 0)
	apiKeys.Add(ctx, 0)
	oidcLogins.Add(ctx, 0)
}

// Claims embedded in JWT tokens.
//
// JTI (JWT ID) is the per-session handle. It maps 1:1 to a row in the
// sessions table so the server can revoke the session without rotating the
// signing secret. Generated by issueToken; validated by middleware on every
// request against the sessions table.
type Claims struct {
	UserID      uint32 `json:"user_id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name,omitempty"`
	Role        string `json:"role"`
	JTI         string `json:"jti,omitempty"`
	jwt.RegisteredClaims
}

// Manager is the consumer-facing surface used by HTTP handlers, the auth
// middleware, the scheduler, and the composition root.
type Manager interface {
	// Service: core auth + JWT + API key
	Login(
		ctx context.Context,
		email, password string,
		meta SessionMeta,
	) (string, error)
	ValidateToken(token string) (*Claims, error)
	ValidateAPIKey(ctx context.Context, key string) (*ent.User, error)
	GetUserByID(ctx context.Context, id uint32) (*ent.User, error)
	CreateAPIKey(
		ctx context.Context,
		userID uint32,
		name string,
	) (string, *ent.ApiKey, error)
	RotateJWTSecret(ctx context.Context, callerID uint32) (string, error)
	PrepareJWTRotation(ctx context.Context, callerID uint32) (string, error)
	ConfirmJWTRotation(ctx context.Context, callerID uint32) (string, error)

	// Account: profile + own credentials/keys
	UpdateProfile(
		ctx context.Context,
		userID uint32,
		displayName string,
	) (*ent.User, error)
	ChangePassword(
		ctx context.Context,
		userID uint32,
		current, newPassword, keepJTI string,
	) error
	ListAPIKeys(ctx context.Context, userID uint32) ([]*ent.ApiKey, error)
	RevokeAPIKeyByID(ctx context.Context, userID, keyID uint32) error

	// OIDC
	LoginOIDC(
		ctx context.Context,
		provider, subject, email, displayName string,
		emailVerified bool,
		claims map[string]any,
		meta SessionMeta,
	) (*ent.User, string, error)

	// Admin: user CRUD + admin actions
	ListUsers(ctx context.Context, f UserFilter) ([]*ent.User, int, error)
	CreateUserDirect(
		ctx context.Context,
		email, password, role, displayName string,
	) (*ent.User, error)
	GetUserDetail(
		ctx context.Context,
		id uint32,
	) (*ent.User, []*ent.ApiKey, []*ent.Session, error)
	UpdateUser(ctx context.Context, id uint32, p UserPatch) error
	DeleteUser(ctx context.Context, id, requesterID uint32) error
	AdminResetPassword(ctx context.Context, id uint32, newPassword string) error
	AdminRevokeAPIKey(ctx context.Context, userID, keyID uint32) error
	AdminRevokeSession(ctx context.Context, userID, sessionID uint32) error
	Unlock(ctx context.Context, email string, mode UnlockMode) error
	AdminUnlock(ctx context.Context, id uint32) error

	// Invites
	CreateInvite(
		ctx context.Context,
		createdByID uint32,
		email, role string,
		ttl time.Duration,
	) (string, *ent.Invite, error)
	LookupInviteForPrefill(ctx context.Context, rawToken string) (*ent.Invite, error)
	ListInvites(ctx context.Context) ([]*ent.Invite, error)
	RevokeInvite(ctx context.Context, id uint32) error
	RegisterWithInvite(
		ctx context.Context,
		rawToken, email, password, displayName string,
		meta SessionMeta,
	) (*ent.User, string, error)

	// Bootstrap + open registration
	BootstrapSeedAdmin(ctx context.Context) error
	RegisterOpen(
		ctx context.Context,
		email, password, displayName, defaultRole string,
		meta SessionMeta,
	) (*ent.User, string, error)

	// Sessions
	ValidateSession(ctx context.Context, jti string) error
	TouchSessionAsync(jti string)
	Shutdown(ctx context.Context) error
	RevokeSession(ctx context.Context, jti string) error
	RevokeSessionByID(ctx context.Context, userID, sessionID uint32) error
	ListUserSessions(ctx context.Context, userID uint32) ([]*ent.Session, error)
	PurgeExpiredSessions(ctx context.Context, before time.Time) (int, error)
}

// auth handles user authentication and API key management. jwtSecret is held
// in an atomic.Pointer so RotateJWTSecret can swap it lock-free under the hot
// ValidateToken/issueToken paths.
type auth struct {
	db        db.Store
	jwtSecret atomic.Pointer[[]byte]
	jwtTTL    time.Duration

	// bg tracks detached goroutines spawned by the service (e.g. async
	// session touches) so Shutdown can wait for them before the caller
	// tears down the DB. Without this, in-flight writes race DB.Close
	// and can leave SQLite WAL/SHM files dangling.
	bg sync.WaitGroup

	// touches keeps last_seen_at writes off the per-request path; see
	// touchDebounce for why minutes of resolution are enough.
	touches *touchDebounce

	// pendingRotations holds callerID -> pendingRotation for the read-only
	// two-step rotate. Deliberately in-memory only: an unconfirmed candidate
	// dying with the process is the correct outcome.
	pendingRotations sync.Map
}

// New constructs a Manager using session credentials from the process-wide
// config singleton. Returns an error if auth.session_ttl fails to parse.
func New(store db.Store) (Manager, error) {
	cfg := config.Get()
	ttl, err := time.ParseDuration(cfg.Auth.SessionTTL)
	if err != nil {
		return nil, fmt.Errorf("parse auth.session_ttl: %w", err)
	}
	a := &auth{db: store, jwtTTL: ttl, touches: newTouchDebounce()}
	secret := []byte(
		config.SecretValue(cfg.Auth.SessionSecret, cfg.Auth.SessionSecretFile),
	)
	a.jwtSecret.Store(&secret)
	return a, nil
}

// Register creates a new user with a bcrypt-hashed password
// and returns a signed JWT so the user is logged in immediately.
func (s *auth) Register(
	ctx context.Context,
	email, password, role string,
	meta SessionMeta,
) (*ent.User, string, error) {
	ctx, span := tracer.Start(ctx, "auth.register",
		trace.WithAttributes(
			semconv.UserEmail(email),
			semconv.UserRoles(role),
			attribute.String("auth.method", "local"),
		),
	)
	defer span.End()

	outcome := "success"
	defer func() {
		registrations.Add(ctx, 1, metric.WithAttributes(
			attribute.String("auth.method", "local"),
			attribute.String("outcome", outcome),
		))
	}()

	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		outcome = "hash_failed"
		return nil, "", otelx.RecordSpanError(
			span,
			fmt.Errorf("hash password: %w", err),
		)
	}

	u, err := s.db.CreateUser(ctx, db.CreateUserParams{
		Email:        email,
		PasswordHash: string(hash),
		Role:         approle.SelfRegistered(user.Role(role)),
		AuthMethod:   user.AuthMethodLocal,
	})
	if err != nil {
		outcome = "create_failed"
		return nil, "", otelx.RecordSpanError(
			span,
			fmt.Errorf("create user: %w", err),
		)
	}
	span.SetAttributes(semconv.UserID(fmt.Sprint(u.ID)))

	token, err := s.issueToken(ctx, u, meta)
	if err != nil {
		outcome = "token_failed"
		return nil, "", otelx.RecordSpanError(span, err)
	}

	slog.InfoContext(ctx, "user registered", "email", email, "role", role)
	return u, token, nil
}

// dummyPasswordHash is what equalizeLoginCost compares against. Hashing a
// random password at init costs the same as a real comparison while
// guaranteeing nothing a caller can send will ever match it.
var dummyPasswordHash = otelx.Must(
	bcrypt.GenerateFromPassword([]byte(rand.Text()), bcrypt.DefaultCost),
)

// loweredCostHashes[c] is dummyPasswordHash with its two cost digits rewritten
// to c, for every c below bcrypt.DefaultCost. The rewrite leaves a hash whose
// tail no longer matches its own salt, which is exactly as useful:
// CompareHashAndPassword still runs all 1<<c key expansions before it can
// discover the mismatch, and the expansions are the only thing wanted here.
// Deriving them from the one hash keeps package init at a single
// GenerateFromPassword rather than one per cost.
var loweredCostHashes = func() [bcrypt.DefaultCost][]byte {
	var out [bcrypt.DefaultCost][]byte
	for c := bcrypt.MinCost; c < bcrypt.DefaultCost; c++ {
		h := bytes.Clone(dummyPasswordHash)
		h[4], h[5] = byte('0'+c/10), byte('0'+c%10)
		out[c] = h
	}
	return out
}()

// equalizeLoginCost spends one default-cost bcrypt comparison. Login calls it
// on the paths that reject before reaching a usable hash — unknown email,
// locked account — and comparePassword calls it whenever the stored hash is one
// bcrypt cannot answer for in exactly this much work, so all of them cost what a
// wrong password costs. Answering those in microseconds where a live, unlocked
// account takes tens of milliseconds tells an attacker which emails exist and
// which are locked, however uniform the response body.
//
// It does not equalize everything: a rejected login for an address that exists
// still runs applyFailedAttempt's SQLite transaction, which an unknown address
// skips. Six runs of 150 interleaved samples per case, each against a freshly
// restarted server and timed over HTTP, put the known address between 0.17ms
// faster and 0.92ms slower at the median, and between 0.11ms faster and 0.42ms
// slower at the minimum — the estimator a remote attacker would use, the
// minimum being the sample least polluted by scheduling noise. Both bands
// straddle zero and both flip sign run to run, so what they size is the
// resolution of the measurement, not the leak: read them as the interval a
// repeat should land in, not as a difference of known magnitude, and re-measure
// rather than trusting the endpoints.
//
// Sampling at that length needs a fresh source address per request, since five
// attempts per IP per 15 minutes throttles anything longer — which is the same
// reason the difference is left standing rather than papered over with a
// transaction on a user that does not exist. No attacker gets near the sample
// count it would take to pull a fraction of a millisecond out of the bcrypt
// floor it hides behind — ~47ms in that run.
//
// Every absolute figure in this file is the machine that sampled it, not a
// constant: comparePassword's runs put the same floor at 41-43ms and at
// 42.8-45.0ms, and a different host moves all three together. What carries
// across hardware is the ratio to the floor — the 149-176x, the 3.97-4.07x,
// the 0.99x-1.08x — so re-measure the floor on the box in front of you rather
// than reading the milliseconds here as a target.
func equalizeLoginCost(password string) {
	_ = bcrypt.CompareHashAndPassword(dummyPasswordHash, []byte(password))
}

// spendCostShortfall spends the key expansions a comparison against a hash
// below bcrypt.DefaultCost did not. One comparison at each cost from cost up to
// DefaultCost-1 runs (1<<DefaultCost)-(1<<cost) of them, which is exactly what
// the cheap hash skipped; a hash at the default enters the loop zero times, and
// comparePassword never lets a costlier one reach here.
//
// Spending one whole default-cost comparison instead is the obvious version and
// is wrong in the other direction: it overshoots by the cheap comparison, which
// is only negligible at the cheap end. Measured over HTTP that put a cost-4
// account 0.34-0.94ms and a cost-9 account 20.6-22.9ms *slower* than every other
// account — the second half the size of the floor it was supposed to hide
// inside, and one-sided in all three runs. Topping up by the shortfall instead
// leaves both inside a -0.78 to +1.33ms spread around the unknown-email floor
// across six runs of 150 interleaved samples: a band that contains zero, whose
// sign flips run to run, and which is not a bound on anything.
//
// cost only reaches here from a header bcrypt.Cost accepted and comparePassword
// did not refuse, so it is inside [bcrypt.MinCost, maxUsableHashCost] and never
// indexes a nil entry.
func spendCostShortfall(cost int, password string) {
	for c := cost; c < bcrypt.DefaultCost; c++ {
		_ = bcrypt.CompareHashAndPassword(loweredCostHashes[c], []byte(password))
	}
}

// maxUsableHashCost is the highest cost comparePassword will let a stored hash
// run at. It is bcrypt.DefaultCost because that is the only amount of work this
// package can spend on demand: equalizeLoginCost spends 1<<bcrypt.DefaultCost
// key expansions and spendCostShortfall tops a cheaper hash up to the same
// number. There is no operation in the other direction — a comparison cannot be
// made to cost less than its own cost — so covering a costlier hash would mean
// raising the equalizer, and every login on the instance would then pay the
// higher cost forever, twice over for the accounts that do not need it.
const maxUsableHashCost = bcrypt.DefaultCost

// errHashCostAboveCeiling is what comparePassword returns instead of running a
// stored hash whose cost exceeds maxUsableHashCost. Login treats it like any
// other failed comparison, so it never reaches a caller.
var errHashCostAboveCeiling = errors.New(
	"stored password hash costs more than a login may spend",
)

// comparePassword checks a candidate password against a stored hash and spends
// one default-cost bcrypt comparison — 1<<bcrypt.DefaultCost key expansions —
// whatever shape the stored hash is in. Not "at least" that: a hash bcrypt would
// answer for less is topped up to it, and a hash that would cost more is refused
// rather than run, so no stored hash moves the answer in either direction.
//
// Whether bcrypt did the work is decided on what CompareHashAndPassword
// returned, never on what the stored hash looks like. Exactly one outcome means
// it ran the rounds and the password was wrong —
// bcrypt.ErrMismatchedHashAndPassword — so that is the one this enumerates.
// Every other error means it gave up before spending anything, and the ways it
// can do that are deliberately not listed: a list covers what it names and
// silently misses the rest, including whatever x/crypto adds next.
//
// Gating usability on bcrypt.Cost is the version of that list which looks total
// and is not. Cost checks the length, the version prefix and the two cost
// digits, and never looks at the salt — so "$2a$10$" over a 22-character salt
// window carrying one byte outside ./A-Za-z0-9 passes it, and the compare then
// dies in expensiveBlowfishSetup's base64 decode before a single round. Measured
// over HTTP, 150 interleaved attempts per case, three runs, that hash answered
// in 0.24-0.29ms against a 41-43ms unknown-email floor — 149-176x faster, enough
// to name the account from one request. Deciding on the result puts every one of
// those cases back inside 1.5ms of the floor.
//
// Cost is still read, but only to refuse. The header is an upper bound on the
// work the compare will do — bcrypt either runs 1<<cost expansions or gives up
// earlier — so refusing on the header alone can never let an expensive
// comparison through, which is the one thing a header can be trusted for. What
// it cannot do is promise the work happens, and nothing here asks it to:
// everything it accepts still has to prove itself by the result.
//
// password_hash is optional on the user schema and LoginOIDC creates SSO
// accounts without one, so the empty string reaches here in normal operation;
// every other shape arrives from a hand-edited row, a restored backup or a
// migration off another system. Nothing this app writes is touched by the
// ceiling: every hash it stores comes from GenerateFromPassword at
// bcrypt.DefaultCost, and a cheaper one still authenticates after paying its
// shortfall.
//
// A costlier one no longer authenticates at all. It answers exactly like an SSO
// account with no password. Stating what that costs the account precisely,
// because "unusable" overstates one half of it and understates the other: the
// password is what stops working, not the account. An OIDC-linked identity
// still signs in through its provider — LoginOIDC never reads password_hash —
// and that sign-in does not clear the ceiling, it just walks around it. What no
// longer works is every path that has to verify the stored password, and that
// is both of them: Login and ChangePassword run the same comparison, so the
// account cannot rewrite its own hash down to a runnable cost by supplying the
// current password. Only AdminResetPassword can, rotating the hash at the
// default cost without verifying the old one.
//
// That both paths compare here is what makes the paragraph above true, and it
// is load-bearing rather than tidy. While ChangePassword called bcrypt
// directly, a genuine $2a$11$ hash gave one credential two answers: POST
// /auth/login with the correct password returned 401 in 48.8ms, and POST
// /api/v1/auth/password with that same correct password as current_password
// returned 204 in 142.2ms, rewrote the row to $2a$10$, and the account logged
// in on its new password immediately after. Any comparison against a stored
// hash added later belongs here for the same reason.
//
// That is the deliberate cost of the ceiling, and it buys two things. A
// comparison the app cannot pad is a one-request oracle in the same way the bad
// salt was, only slower rather than faster: measured over HTTP, 150 interleaved
// attempts per case, three runs, a cost-12 account answered in 173.0-183.3ms
// against a 42.8-45.0ms unknown-email floor — 3.97-4.07x, +130 to +138ms, no
// statistics needed. And an unpadded comparison is unbounded work inside one
// request: "$2a$31$" over a *valid* salt is 2^31 key expansions, and one such
// POST /auth/login held a core at 98% for the full minute a client waited on it
// and still had not answered. With the ceiling in place all eleven
// shapes measured — cost 4, 9, 12, 14 and 31, the empty, truncated and bad-salt
// hashes, a good password and an unknown address — answer inside 0.99x to 1.08x
// of the floor.
func comparePassword(ctx context.Context, hash, password string) error {
	cost, costErr := bcrypt.Cost([]byte(hash))
	if costErr == nil && cost > maxUsableHashCost {
		slog.WarnContext(ctx, "stored password hash is too costly to run; "+
			"this account cannot log in until its password is reset",
			"password_hash.cost", cost,
			"password_hash.max_cost", maxUsableHashCost,
		)
		equalizeLoginCost(password)
		return errHashCostAboveCeiling
	}

	err := bcrypt.CompareHashAndPassword([]byte(hash), []byte(password))
	if err != nil && !errors.Is(err, bcrypt.ErrMismatchedHashAndPassword) {
		equalizeLoginCost(password)
		return err
	}
	if costErr == nil {
		spendCostShortfall(cost, password)
	}
	return err
}

// Login verifies credentials and returns a signed JWT. Account lockout state
// is checked before the password. On password mismatch the failed-attempt
// counter is incremented inside a transaction so concurrent attempts can't
// race the increment.
func (s *auth) Login(
	ctx context.Context,
	email, password string,
	meta SessionMeta,
) (string, error) {
	ctx, span := tracer.Start(ctx, "auth.login",
		trace.WithAttributes(
			semconv.UserEmail(email),
			attribute.String("auth.method", "local"),
		),
	)
	defer span.End()

	outcome := "success"
	defer func() {
		logins.Add(ctx, 1, metric.WithAttributes(
			attribute.String("auth.method", "local"),
			attribute.String("outcome", outcome),
		))
	}()

	u, err := s.db.FindUserByEmail(ctx, email)
	if err != nil {
		equalizeLoginCost(password)
		outcome = "invalid_credentials"
		return "", otelx.RecordSpanError(span, fmt.Errorf("invalid credentials"))
	}

	now := time.Now()
	state := LockoutState{
		FailedCount:  u.FailedLoginCount,
		LastFailedAt: u.LastFailedLoginAt,
		LockedUntil:  u.LockedUntil,
	}
	if locked, until := IsLocked(state, now); locked {
		equalizeLoginCost(password)
		span.SetAttributes(attribute.Bool("auth.lockout.locked", true))
		outcome = "locked"
		return "", otelx.RecordSpanError(span, ErrAccountLockedT{LockedUntil: until})
	}

	if err := comparePassword(ctx, u.PasswordHash, password); err != nil {
		next, locked, until, txErr := s.applyFailedAttempt(ctx, u.ID, now)
		if txErr != nil {
			outcome = "invalid_credentials"
			return "", otelx.RecordSpanError(span, txErr)
		}
		span.SetAttributes(
			attribute.Int("auth.lockout.failed_count", int(next.FailedCount)),
		)
		if locked {
			span.SetAttributes(attribute.Bool("auth.lockout.locked", true))
			slog.WarnContext(ctx, "auth.account_locked",
				"user.id", u.ID,
				"user.email", u.Email,
				"lockout.duration", until.Sub(now).String(),
			)
			outcome = "locked"
			return "", otelx.RecordSpanError(
				span,
				ErrAccountLockedT{LockedUntil: until},
			)
		}
		outcome = "invalid_credentials"
		return "", otelx.RecordSpanError(span, fmt.Errorf("invalid credentials"))
	}
	span.SetAttributes(semconv.UserID(fmt.Sprint(u.ID)))

	if u.FailedLoginCount > 0 || u.LastFailedLoginAt != nil || u.LockedUntil != nil {
		if err := s.clearLockoutState(ctx, u.ID); err != nil {
			slog.WarnContext(ctx, "auth.lockout_clear_failed",
				"user.id", u.ID, "error", err)
		}
	}

	token, err := s.issueToken(ctx, u, meta)
	if err != nil {
		outcome = "token_failed"
		return "", otelx.RecordSpanError(span, err)
	}

	slog.InfoContext(ctx, "user logged in", "email", email)
	return token, nil
}

// applyFailedAttempt re-fetches the user inside a transaction, applies the
// lockout policy, persists the new counter/timestamps, and returns the new
// state. Read-modify-write under tx serialization.
func (s *auth) applyFailedAttempt(
	ctx context.Context,
	id uint32,
	now time.Time,
) (LockoutState, bool, time.Time, error) {
	tx, err := s.db.Tx(ctx)
	if err != nil {
		return LockoutState{}, false, time.Time{}, fmt.Errorf("begin tx: %w", err)
	}

	cur, err := tx.FindUserByID(ctx, id)
	if err != nil {
		tx.Rollback()
		return LockoutState{}, false, time.Time{}, fmt.Errorf("reload user: %w", err)
	}
	pol := s.lockoutPolicy()
	prev := LockoutState{
		FailedCount:  cur.FailedLoginCount,
		LastFailedAt: cur.LastFailedLoginAt,
		LockedUntil:  cur.LockedUntil,
	}
	next := OnFailedAttempt(prev, now, pol)
	count := next.FailedCount
	params := db.UpdateUserParams{
		FailedLoginCount:  &count,
		LastFailedLoginAt: next.LastFailedAt,
	}
	if next.LockedUntil != nil {
		params.LockedUntil = next.LockedUntil
	}
	if _, err := tx.UpdateUser(ctx, id, params); err != nil {
		tx.Rollback()
		return LockoutState{}, false, time.Time{}, fmt.Errorf(
			"update lockout: %w",
			err,
		)
	}
	if err := tx.Commit(); err != nil {
		return LockoutState{}, false, time.Time{}, fmt.Errorf(
			"commit lockout: %w",
			err,
		)
	}
	locked := next.LockedUntil != nil
	until := time.Time{}
	if locked {
		until = *next.LockedUntil
	}
	return next, locked, until, nil
}

// clearLockoutState wipes the three lockout fields outside a tx (single-row
// idempotent UPDATE — race-safe enough).
func (s *auth) clearLockoutState(ctx context.Context, id uint32) error {
	zero := uint8(0)
	_, err := s.db.UpdateUser(ctx, id, db.UpdateUserParams{
		FailedLoginCount:       &zero,
		ClearLastFailedLoginAt: true,
		ClearLockedUntil:       true,
	})
	return err
}

// lockoutPolicy reads the current LockoutConfig fresh on every login attempt
// so admins can tune without restarting. Falls back to safe defaults if
// parsing fails (mirrors the SessionTTL pattern in issueToken).
func (s *auth) lockoutPolicy() LockoutPolicy {
	cfg := config.Get()
	if cfg == nil {
		return LockoutPolicy{
			Threshold: 10,
			Window:    15 * time.Minute,
			Duration:  15 * time.Minute,
		}
	}
	pol := LockoutPolicy{
		Threshold: cfg.Auth.Lockout.Threshold,
		Window:    15 * time.Minute,
		Duration:  15 * time.Minute,
	}
	if d, err := time.ParseDuration(cfg.Auth.Lockout.Window); err == nil && d > 0 {
		pol.Window = d
	}
	if d, err := time.ParseDuration(cfg.Auth.Lockout.Duration); err == nil && d > 0 {
		pol.Duration = d
	}
	if pol.Threshold == 0 {
		pol.Threshold = 10
	}
	return pol
}

// issueToken generates a new JWT for u and persists the matching session
// row before returning. The session row MUST exist before the caller hands
// the token to the client, otherwise the first authenticated request races
// CreateSession and 401s.
func (s *auth) issueToken(
	ctx context.Context,
	u *ent.User,
	meta SessionMeta,
) (string, error) {
	jti, err := generateJTI()
	if err != nil {
		return "", fmt.Errorf("generate jti: %w", err)
	}

	// Re-read session_ttl from the config singleton on every issue so an
	// admin PATCH /config/auth takes effect without restarting the process.
	// Falls back to the boot-time value on missing/unparseable config (e.g.
	// unit tests that don't load a singleton).
	ttl := s.jwtTTL
	if cfg := config.Get(); cfg != nil {
		if parsed, err := time.ParseDuration(
			cfg.Auth.SessionTTL,
		); err == nil &&
			parsed > 0 {
			ttl = parsed
		}
	}

	// Persist the session row first; if the DB insert fails we don't want a
	// signed bearer token floating around with no backing record.
	if _, err := s.CreateSession(ctx, u.ID, jti, ttl, meta); err != nil {
		return "", err
	}

	now := time.Now()
	claims := Claims{
		UserID:      u.ID,
		Email:       u.Email,
		DisplayName: u.DisplayName,
		Role:        string(u.Role),
		JTI:         jti,
		RegisteredClaims: jwt.RegisteredClaims{
			IssuedAt:  jwt.NewNumericDate(now),
			ExpiresAt: jwt.NewNumericDate(now.Add(ttl)),
			Issuer:    "streamline",
			ID:        jti,
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	signed, err := token.SignedString(*s.jwtSecret.Load())
	if err != nil {
		return "", fmt.Errorf("sign token: %w", err)
	}
	return signed, nil
}

// generateJTI returns 128 bits of crypto/rand hex — same pattern as
// generateToken but at a fixed width so JWT "jti" / sessions.jti stay
// predictable in length across deployments.
func generateJTI() (string, error) {
	return generateToken(16)
}

// ValidateToken parses and validates a JWT, returning the claims.
func (s *auth) ValidateToken(tokenString string) (*Claims, error) {
	token, err := jwt.ParseWithClaims(
		tokenString,
		&Claims{},
		func(token *jwt.Token) (any, error) {
			if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
				return nil, fmt.Errorf(
					"unexpected signing method: %v",
					token.Header["alg"],
				)
			}
			return *s.jwtSecret.Load(), nil
		},
	)
	if err != nil {
		return nil, err
	}

	claims, ok := token.Claims.(*Claims)
	if !ok || !token.Valid {
		return nil, fmt.Errorf("invalid token")
	}

	return claims, nil
}

// ValidateAPIKey checks an API key against stored SHA-256 hashes.
func (s *auth) ValidateAPIKey(
	ctx context.Context,
	key string,
) (*ent.User, error) {
	hash := hashAPIKey(key)

	ak, err := s.db.FindAPIKeyByHash(ctx, hash)
	if err != nil {
		return nil, fmt.Errorf("invalid API key")
	}

	// Best-effort: a failed stamp must not reject an otherwise valid key.
	// Debounced like the session touch — this one is synchronous, on the
	// request path, so a bulk consumer used to pay a full row rewrite per
	// request for a column nothing branches on. At one write per
	// touchInterval it is rare enough not to be worth detaching.
	if s.touches.allow(fmt.Sprintf("apikey:%d", ak.ID), time.Now()) {
		if err := s.db.TouchAPIKey(ctx, ak.ID, time.Now()); err != nil {
			slog.WarnContext(ctx, "failed to record API key usage",
				"api_key.id", ak.ID, "error", err)
		}
	}

	return ak.Edges.Owner, nil
}

// GetUserByID returns the user with the given id. Returns ErrUserNotFound when
// the row is missing so handlers can map the result to a 404 without importing
// ent's not-found check.
func (s *auth) GetUserByID(
	ctx context.Context,
	id uint32,
) (*ent.User, error) {
	u, err := s.db.FindUserByID(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrUserNotFound
		}
		return nil, err
	}
	return u, nil
}

// CreateAPIKey generates a new API key for a user.
// Returns the raw key (shown once to the user) plus the persisted record —
// only the hash is stored. Callers surface rec.ID/CreatedAt in UI responses;
// the raw key is shown to the user exactly once.
func (s *auth) CreateAPIKey(
	ctx context.Context,
	userID uint32,
	name string,
) (string, *ent.ApiKey, error) {
	count, err := s.db.CountAPIKeysByUser(ctx, userID)
	if err != nil {
		return "", nil, fmt.Errorf("count API keys: %w", err)
	}
	if count >= maxAPIKeysPerUser {
		return "", nil, ErrAPIKeyQuotaExceeded
	}

	key, err := generateToken(32)
	if err != nil {
		return "", nil, fmt.Errorf("generate API key: %w", err)
	}

	rec, err := s.db.CreateAPIKey(ctx, db.CreateAPIKeyParams{
		Name:    name,
		KeyHash: hashAPIKey(key),
		OwnerID: userID,
	})
	if err != nil {
		return "", nil, fmt.Errorf("create API key: %w", err)
	}

	apiKeys.Add(ctx, 1)
	slog.InfoContext(ctx, "API key created", "user_id", userID, "name", name)
	return key, rec, nil
}

func generateToken(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func hashAPIKey(key string) string {
	h := sha256.Sum256([]byte(key))
	return hex.EncodeToString(h[:])
}
