package auth

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"log/slog"
	"sync"
	"sync/atomic"
	"time"

	"github.com/datahearth/streamline/ent"
	"github.com/datahearth/streamline/ent/user"
	"github.com/datahearth/streamline/internal/config"
	"github.com/datahearth/streamline/internal/db"
	"github.com/datahearth/streamline/internal/otelx"
	"github.com/golang-jwt/jwt/v5"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"
	"golang.org/x/crypto/bcrypt"
)

var (
	tracer = otel.Tracer("github.com/datahearth/streamline/internal/auth")
	meter  = otel.Meter("github.com/datahearth/streamline/internal/auth")

	logins        metric.Int64Counter
	registrations metric.Int64Counter
	apiKeys       metric.Int64Counter
	oidcLogins    metric.Int64Counter
)

func init() {
	logins = otelx.Must(meter.Int64Counter(
		"streamline.auth.logins",
		metric.WithDescription("Login attempts by method + outcome"),
	))
	registrations = otelx.Must(meter.Int64Counter(
		"streamline.auth.registrations",
		metric.WithDescription("User registrations by method + outcome"),
	))
	apiKeys = otelx.Must(meter.Int64Counter(
		"streamline.auth.api_keys_created",
		metric.WithDescription("Number of API keys created"),
	))
	oidcLogins = otelx.Must(meter.Int64Counter(
		"streamline.auth.oidc.logins",
		metric.WithDescription("OIDC login outcomes by provider"),
	))

	ctx := context.Background()
	logins.Add(ctx, 0)
	registrations.Add(ctx, 0)
	apiKeys.Add(ctx, 0)
	oidcLogins.Add(ctx, 0)
}

// Claims embedded in JWT tokens.
//
// JTI (JWT ID) is the per-session handle. It maps 1:1 to a row in the
// sessions table so the server can revoke the session without rotating the
// signing secret. Generated by issueToken; validated by middleware on every
// request against the sessions table.
type Claims struct {
	UserID      uint32 `json:"user_id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name,omitempty"`
	Role        string `json:"role"`
	JTI         string `json:"jti,omitempty"`
	jwt.RegisteredClaims
}

// Manager is the consumer-facing surface used by HTTP handlers, the auth
// middleware, the scheduler, and the composition root.
type Manager interface {
	// Service: core auth + JWT + API key
	Login(
		ctx context.Context,
		email, password string,
		meta SessionMeta,
	) (string, error)
	ValidateToken(token string) (*Claims, error)
	ValidateAPIKey(ctx context.Context, key string) (*ent.User, error)
	GetUserByID(ctx context.Context, id uint32) (*ent.User, error)
	CreateAPIKey(
		ctx context.Context,
		userID uint32,
		name string,
	) (string, *ent.ApiKey, error)
	RotateJWTSecret(ctx context.Context, callerID uint32) (string, error)

	// Account: profile + own credentials/keys
	UpdateProfile(
		ctx context.Context,
		userID uint32,
		displayName string,
	) (*ent.User, error)
	ChangePassword(
		ctx context.Context,
		userID uint32,
		current, newPassword, keepJTI string,
	) error
	ListAPIKeys(ctx context.Context, userID uint32) ([]*ent.ApiKey, error)
	RevokeAPIKeyByID(ctx context.Context, userID, keyID uint32) error

	// OIDC
	LoginOIDC(
		ctx context.Context,
		provider, subject, email, displayName string,
		emailVerified bool,
		claims map[string]any,
		meta SessionMeta,
	) (*ent.User, string, error)

	// Admin: user CRUD + admin actions
	ListUsers(ctx context.Context, f UserFilter) ([]*ent.User, int, error)
	CreateUserDirect(
		ctx context.Context,
		email, password, role, displayName string,
	) (*ent.User, error)
	GetUserDetail(
		ctx context.Context,
		id uint32,
	) (*ent.User, []*ent.ApiKey, []*ent.Session, error)
	UpdateUser(ctx context.Context, id uint32, p UserPatch) error
	DeleteUser(ctx context.Context, id, requesterID uint32) error
	AdminResetPassword(ctx context.Context, id uint32, newPassword string) error
	AdminRevokeAPIKey(ctx context.Context, userID, keyID uint32) error
	AdminRevokeSession(ctx context.Context, userID, sessionID uint32) error
	Unlock(ctx context.Context, email string, mode UnlockMode) error
	AdminUnlock(ctx context.Context, id uint32) error

	// Invites
	CreateInvite(
		ctx context.Context,
		createdByID uint32,
		email, role string,
		ttl time.Duration,
	) (string, *ent.Invite, error)
	LookupInviteForPrefill(ctx context.Context, rawToken string) (*ent.Invite, error)
	ListInvites(ctx context.Context) ([]*ent.Invite, error)
	RevokeInvite(ctx context.Context, id uint32) error
	RegisterWithInvite(
		ctx context.Context,
		rawToken, email, password, displayName string,
		meta SessionMeta,
	) (*ent.User, string, error)

	// Bootstrap + open registration
	BootstrapSeedAdmin(ctx context.Context) error
	RegisterOpen(
		ctx context.Context,
		email, password, displayName, defaultRole string,
		meta SessionMeta,
	) (*ent.User, string, error)

	// Sessions
	ValidateSession(ctx context.Context, jti string) error
	TouchSessionAsync(jti string)
	Shutdown(ctx context.Context) error
	RevokeSession(ctx context.Context, jti string) error
	RevokeSessionByID(ctx context.Context, userID, sessionID uint32) error
	ListUserSessions(ctx context.Context, userID uint32) ([]*ent.Session, error)
	PurgeExpiredSessions(ctx context.Context, before time.Time) (int, error)
}

// auth handles user authentication and API key management. jwtSecret is held
// in an atomic.Pointer so RotateJWTSecret can swap it lock-free under the hot
// ValidateToken/issueToken paths.
type auth struct {
	db        db.Store
	jwtSecret atomic.Pointer[[]byte]
	jwtTTL    time.Duration

	// bg tracks detached goroutines spawned by the service (e.g. async
	// session touches) so Shutdown can wait for them before the caller
	// tears down the DB. Without this, in-flight writes race DB.Close
	// and can leave SQLite WAL/SHM files dangling.
	bg sync.WaitGroup
}

// New constructs a Manager using session credentials from the process-wide
// config singleton. Returns an error if auth.session_ttl fails to parse.
func New(store db.Store) (Manager, error) {
	cfg := config.Get()
	ttl, err := time.ParseDuration(cfg.Auth.SessionTTL)
	if err != nil {
		return nil, fmt.Errorf("parse auth.session_ttl: %w", err)
	}
	a := &auth{db: store, jwtTTL: ttl}
	secret := []byte(
		config.SecretValue(cfg.Auth.SessionSecret, cfg.Auth.SessionSecretFile),
	)
	a.jwtSecret.Store(&secret)
	return a, nil
}

// Register creates a new user with a bcrypt-hashed password
// and returns a signed JWT so the user is logged in immediately.
func (s *auth) Register(
	ctx context.Context,
	email, password, role string,
	meta SessionMeta,
) (*ent.User, string, error) {
	ctx, span := tracer.Start(ctx, "auth.register",
		trace.WithAttributes(
			semconv.UserEmail(email),
			semconv.UserRoles(role),
			attribute.String("auth.method", "local"),
		),
	)
	defer span.End()

	outcome := "success"
	defer func() {
		registrations.Add(ctx, 1, metric.WithAttributes(
			attribute.String("auth.method", "local"),
			attribute.String("outcome", outcome),
		))
	}()

	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		outcome = "hash_failed"
		return nil, "", otelx.RecordSpanError(
			span,
			fmt.Errorf("hash password: %w", err),
		)
	}

	u, err := s.db.CreateUser(ctx, db.CreateUserParams{
		Email:        email,
		PasswordHash: string(hash),
		Role:         user.Role(role),
		AuthMethod:   user.AuthMethodLocal,
	})
	if err != nil {
		outcome = "create_failed"
		return nil, "", otelx.RecordSpanError(
			span,
			fmt.Errorf("create user: %w", err),
		)
	}
	span.SetAttributes(semconv.UserID(fmt.Sprint(u.ID)))

	token, err := s.issueToken(ctx, u, meta)
	if err != nil {
		outcome = "token_failed"
		return nil, "", otelx.RecordSpanError(span, err)
	}

	slog.InfoContext(ctx, "user registered", "email", email, "role", role)
	return u, token, nil
}

// Login verifies credentials and returns a signed JWT. Account lockout state
// is checked first (locked → ErrAccountLockedT bypasses bcrypt). On password
// mismatch the failed-attempt counter is incremented inside a transaction so
// concurrent attempts can't race the increment.
func (s *auth) Login(
	ctx context.Context,
	email, password string,
	meta SessionMeta,
) (string, error) {
	ctx, span := tracer.Start(ctx, "auth.login",
		trace.WithAttributes(
			semconv.UserEmail(email),
			attribute.String("auth.method", "local"),
		),
	)
	defer span.End()

	outcome := "success"
	defer func() {
		logins.Add(ctx, 1, metric.WithAttributes(
			attribute.String("auth.method", "local"),
			attribute.String("outcome", outcome),
		))
	}()

	u, err := s.db.FindUserByEmail(ctx, email)
	if err != nil {
		outcome = "invalid_credentials"
		return "", otelx.RecordSpanError(span, fmt.Errorf("invalid credentials"))
	}

	now := time.Now()
	state := LockoutState{
		FailedCount:  u.FailedLoginCount,
		LastFailedAt: u.LastFailedLoginAt,
		LockedUntil:  u.LockedUntil,
	}
	if locked, until := IsLocked(state, now); locked {
		span.SetAttributes(attribute.Bool("auth.lockout.locked", true))
		outcome = "locked"
		return "", otelx.RecordSpanError(span, ErrAccountLockedT{LockedUntil: until})
	}

	if err := bcrypt.CompareHashAndPassword(
		[]byte(u.PasswordHash),
		[]byte(password),
	); err != nil {
		next, locked, until, txErr := s.applyFailedAttempt(ctx, u.ID, now)
		if txErr != nil {
			outcome = "invalid_credentials"
			return "", otelx.RecordSpanError(span, txErr)
		}
		span.SetAttributes(
			attribute.Int("auth.lockout.failed_count", int(next.FailedCount)),
		)
		if locked {
			span.SetAttributes(attribute.Bool("auth.lockout.locked", true))
			slog.WarnContext(ctx, "auth.account_locked",
				"user.id", u.ID,
				"user.email", u.Email,
				"lockout.duration", until.Sub(now).String(),
			)
			outcome = "locked"
			return "", otelx.RecordSpanError(
				span,
				ErrAccountLockedT{LockedUntil: until},
			)
		}
		outcome = "invalid_credentials"
		return "", otelx.RecordSpanError(span, fmt.Errorf("invalid credentials"))
	}
	span.SetAttributes(semconv.UserID(fmt.Sprint(u.ID)))

	if u.FailedLoginCount > 0 || u.LastFailedLoginAt != nil || u.LockedUntil != nil {
		if err := s.clearLockoutState(ctx, u.ID); err != nil {
			slog.WarnContext(ctx, "auth.lockout_clear_failed",
				"user.id", u.ID, "error", err)
		}
	}

	token, err := s.issueToken(ctx, u, meta)
	if err != nil {
		outcome = "token_failed"
		return "", otelx.RecordSpanError(span, err)
	}

	slog.InfoContext(ctx, "user logged in", "email", email)
	return token, nil
}

// applyFailedAttempt re-fetches the user inside a transaction, applies the
// lockout policy, persists the new counter/timestamps, and returns the new
// state. Read-modify-write under tx serialization.
func (s *auth) applyFailedAttempt(
	ctx context.Context,
	id uint32,
	now time.Time,
) (LockoutState, bool, time.Time, error) {
	tx, err := s.db.Tx(ctx)
	if err != nil {
		return LockoutState{}, false, time.Time{}, fmt.Errorf("begin tx: %w", err)
	}

	cur, err := tx.FindUserByID(ctx, id)
	if err != nil {
		tx.Rollback()
		return LockoutState{}, false, time.Time{}, fmt.Errorf("reload user: %w", err)
	}
	pol := s.lockoutPolicy()
	prev := LockoutState{
		FailedCount:  cur.FailedLoginCount,
		LastFailedAt: cur.LastFailedLoginAt,
		LockedUntil:  cur.LockedUntil,
	}
	next := OnFailedAttempt(prev, now, pol)
	count := next.FailedCount
	params := db.UpdateUserParams{
		FailedLoginCount:  &count,
		LastFailedLoginAt: next.LastFailedAt,
	}
	if next.LockedUntil != nil {
		params.LockedUntil = next.LockedUntil
	}
	if _, err := tx.UpdateUser(ctx, id, params); err != nil {
		tx.Rollback()
		return LockoutState{}, false, time.Time{}, fmt.Errorf(
			"update lockout: %w",
			err,
		)
	}
	if err := tx.Commit(); err != nil {
		return LockoutState{}, false, time.Time{}, fmt.Errorf(
			"commit lockout: %w",
			err,
		)
	}
	locked := next.LockedUntil != nil
	until := time.Time{}
	if locked {
		until = *next.LockedUntil
	}
	return next, locked, until, nil
}

// clearLockoutState wipes the three lockout fields outside a tx (single-row
// idempotent UPDATE — race-safe enough).
func (s *auth) clearLockoutState(ctx context.Context, id uint32) error {
	zero := uint8(0)
	_, err := s.db.UpdateUser(ctx, id, db.UpdateUserParams{
		FailedLoginCount:       &zero,
		ClearLastFailedLoginAt: true,
		ClearLockedUntil:       true,
	})
	return err
}

// lockoutPolicy reads the current LockoutConfig fresh on every login attempt
// so admins can tune without restarting. Falls back to safe defaults if
// parsing fails (mirrors the SessionTTL pattern in issueToken).
func (s *auth) lockoutPolicy() LockoutPolicy {
	cfg := config.Get()
	if cfg == nil {
		return LockoutPolicy{
			Threshold: 10,
			Window:    15 * time.Minute,
			Duration:  15 * time.Minute,
		}
	}
	pol := LockoutPolicy{
		Threshold: cfg.Auth.Lockout.Threshold,
		Window:    15 * time.Minute,
		Duration:  15 * time.Minute,
	}
	if d, err := time.ParseDuration(cfg.Auth.Lockout.Window); err == nil && d > 0 {
		pol.Window = d
	}
	if d, err := time.ParseDuration(cfg.Auth.Lockout.Duration); err == nil && d > 0 {
		pol.Duration = d
	}
	if pol.Threshold == 0 {
		pol.Threshold = 10
	}
	return pol
}

// issueToken generates a new JWT for u and persists the matching session
// row before returning. The session row MUST exist before the caller hands
// the token to the client, otherwise the first authenticated request races
// CreateSession and 401s.
func (s *auth) issueToken(
	ctx context.Context,
	u *ent.User,
	meta SessionMeta,
) (string, error) {
	jti, err := generateJTI()
	if err != nil {
		return "", fmt.Errorf("generate jti: %w", err)
	}

	// Re-read session_ttl from the config singleton on every issue so an
	// admin PATCH /config/auth takes effect without restarting the process.
	// Falls back to the boot-time value on missing/unparseable config (e.g.
	// unit tests that don't load a singleton).
	ttl := s.jwtTTL
	if cfg := config.Get(); cfg != nil {
		if parsed, err := time.ParseDuration(
			cfg.Auth.SessionTTL,
		); err == nil &&
			parsed > 0 {
			ttl = parsed
		}
	}

	// Persist the session row first; if the DB insert fails we don't want a
	// signed bearer token floating around with no backing record.
	if _, err := s.CreateSession(ctx, u.ID, jti, ttl, meta); err != nil {
		return "", err
	}

	now := time.Now()
	claims := Claims{
		UserID:      u.ID,
		Email:       u.Email,
		DisplayName: u.DisplayName,
		Role:        string(u.Role),
		JTI:         jti,
		RegisteredClaims: jwt.RegisteredClaims{
			IssuedAt:  jwt.NewNumericDate(now),
			ExpiresAt: jwt.NewNumericDate(now.Add(ttl)),
			Issuer:    "streamline",
			ID:        jti,
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	signed, err := token.SignedString(*s.jwtSecret.Load())
	if err != nil {
		return "", fmt.Errorf("sign token: %w", err)
	}
	return signed, nil
}

// generateJTI returns 128 bits of crypto/rand hex — same pattern as
// generateToken but at a fixed width so JWT "jti" / sessions.jti stay
// predictable in length across deployments.
func generateJTI() (string, error) {
	return generateToken(16)
}

// ValidateToken parses and validates a JWT, returning the claims.
func (s *auth) ValidateToken(tokenString string) (*Claims, error) {
	token, err := jwt.ParseWithClaims(
		tokenString,
		&Claims{},
		func(token *jwt.Token) (any, error) {
			if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
				return nil, fmt.Errorf(
					"unexpected signing method: %v",
					token.Header["alg"],
				)
			}
			return *s.jwtSecret.Load(), nil
		},
	)
	if err != nil {
		return nil, err
	}

	claims, ok := token.Claims.(*Claims)
	if !ok || !token.Valid {
		return nil, fmt.Errorf("invalid token")
	}

	return claims, nil
}

// ValidateAPIKey checks an API key against stored SHA-256 hashes.
func (s *auth) ValidateAPIKey(
	ctx context.Context,
	key string,
) (*ent.User, error) {
	hash := hashAPIKey(key)

	ak, err := s.db.FindAPIKeyByHash(ctx, hash)
	if err != nil {
		return nil, fmt.Errorf("invalid API key")
	}

	return ak.Edges.Owner, nil
}

// GetUserByID returns the user with the given id. Returns ErrUserNotFound when
// the row is missing so handlers can map the result to a 404 without importing
// ent's not-found check.
func (s *auth) GetUserByID(
	ctx context.Context,
	id uint32,
) (*ent.User, error) {
	u, err := s.db.FindUserByID(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrUserNotFound
		}
		return nil, err
	}
	return u, nil
}

// CreateAPIKey generates a new API key for a user.
// Returns the raw key (shown once to the user) plus the persisted record —
// only the hash is stored. Callers surface rec.ID/CreatedAt in UI responses;
// the raw key is shown to the user exactly once.
func (s *auth) CreateAPIKey(
	ctx context.Context,
	userID uint32,
	name string,
) (string, *ent.ApiKey, error) {
	key, err := generateToken(32)
	if err != nil {
		return "", nil, fmt.Errorf("generate API key: %w", err)
	}

	rec, err := s.db.CreateAPIKey(ctx, db.CreateAPIKeyParams{
		Name:    name,
		KeyHash: hashAPIKey(key),
		OwnerID: userID,
	})
	if err != nil {
		return "", nil, fmt.Errorf("create API key: %w", err)
	}

	apiKeys.Add(ctx, 1)
	slog.InfoContext(ctx, "API key created", "user_id", userID, "name", name)
	return key, rec, nil
}

func generateToken(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func hashAPIKey(key string) string {
	h := sha256.Sum256([]byte(key))
	return hex.EncodeToString(h[:])
}
