// Code generated by ent, DO NOT EDIT.

package book

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/datahearth/streamline/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldUpdateTime, v))
}

// HardcoverID applies equality check predicate on the "hardcover_id" field. It's identical to HardcoverIDEQ.
func HardcoverID(v uint32) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldHardcoverID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldTitle, v))
}

// SortTitle applies equality check predicate on the "sort_title" field. It's identical to SortTitleEQ.
func SortTitle(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldSortTitle, v))
}

// ReleaseDate applies equality check predicate on the "release_date" field. It's identical to ReleaseDateEQ.
func ReleaseDate(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldReleaseDate, v))
}

// Overview applies equality check predicate on the "overview" field. It's identical to OverviewEQ.
func Overview(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldOverview, v))
}

// SeriesName applies equality check predicate on the "series_name" field. It's identical to SeriesNameEQ.
func SeriesName(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldSeriesName, v))
}

// SeriesPosition applies equality check predicate on the "series_position" field. It's identical to SeriesPositionEQ.
func SeriesPosition(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldSeriesPosition, v))
}

// EbookMonitored applies equality check predicate on the "ebook_monitored" field. It's identical to EbookMonitoredEQ.
func EbookMonitored(v bool) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldEbookMonitored, v))
}

// EbookGrabFailures applies equality check predicate on the "ebook_grab_failures" field. It's identical to EbookGrabFailuresEQ.
func EbookGrabFailures(v uint8) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldEbookGrabFailures, v))
}

// EbookLastSearchAt applies equality check predicate on the "ebook_last_search_at" field. It's identical to EbookLastSearchAtEQ.
func EbookLastSearchAt(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldEbookLastSearchAt, v))
}

// AudiobookMonitored applies equality check predicate on the "audiobook_monitored" field. It's identical to AudiobookMonitoredEQ.
func AudiobookMonitored(v bool) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldAudiobookMonitored, v))
}

// AudiobookGrabFailures applies equality check predicate on the "audiobook_grab_failures" field. It's identical to AudiobookGrabFailuresEQ.
func AudiobookGrabFailures(v uint8) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldAudiobookGrabFailures, v))
}

// AudiobookLastSearchAt applies equality check predicate on the "audiobook_last_search_at" field. It's identical to AudiobookLastSearchAtEQ.
func AudiobookLastSearchAt(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldAudiobookLastSearchAt, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldUpdateTime, v))
}

// HardcoverIDEQ applies the EQ predicate on the "hardcover_id" field.
func HardcoverIDEQ(v uint32) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldHardcoverID, v))
}

// HardcoverIDNEQ applies the NEQ predicate on the "hardcover_id" field.
func HardcoverIDNEQ(v uint32) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldHardcoverID, v))
}

// HardcoverIDIn applies the In predicate on the "hardcover_id" field.
func HardcoverIDIn(vs ...uint32) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldHardcoverID, vs...))
}

// HardcoverIDNotIn applies the NotIn predicate on the "hardcover_id" field.
func HardcoverIDNotIn(vs ...uint32) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldHardcoverID, vs...))
}

// HardcoverIDGT applies the GT predicate on the "hardcover_id" field.
func HardcoverIDGT(v uint32) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldHardcoverID, v))
}

// HardcoverIDGTE applies the GTE predicate on the "hardcover_id" field.
func HardcoverIDGTE(v uint32) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldHardcoverID, v))
}

// HardcoverIDLT applies the LT predicate on the "hardcover_id" field.
func HardcoverIDLT(v uint32) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldHardcoverID, v))
}

// HardcoverIDLTE applies the LTE predicate on the "hardcover_id" field.
func HardcoverIDLTE(v uint32) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldHardcoverID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Book {
	return predicate.Book(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Book {
	return predicate.Book(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Book {
	return predicate.Book(sql.FieldContainsFold(FieldTitle, v))
}

// SortTitleEQ applies the EQ predicate on the "sort_title" field.
func SortTitleEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldSortTitle, v))
}

// SortTitleNEQ applies the NEQ predicate on the "sort_title" field.
func SortTitleNEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldSortTitle, v))
}

// SortTitleIn applies the In predicate on the "sort_title" field.
func SortTitleIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldSortTitle, vs...))
}

// SortTitleNotIn applies the NotIn predicate on the "sort_title" field.
func SortTitleNotIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldSortTitle, vs...))
}

// SortTitleGT applies the GT predicate on the "sort_title" field.
func SortTitleGT(v string) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldSortTitle, v))
}

// SortTitleGTE applies the GTE predicate on the "sort_title" field.
func SortTitleGTE(v string) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldSortTitle, v))
}

// SortTitleLT applies the LT predicate on the "sort_title" field.
func SortTitleLT(v string) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldSortTitle, v))
}

// SortTitleLTE applies the LTE predicate on the "sort_title" field.
func SortTitleLTE(v string) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldSortTitle, v))
}

// SortTitleContains applies the Contains predicate on the "sort_title" field.
func SortTitleContains(v string) predicate.Book {
	return predicate.Book(sql.FieldContains(FieldSortTitle, v))
}

// SortTitleHasPrefix applies the HasPrefix predicate on the "sort_title" field.
func SortTitleHasPrefix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasPrefix(FieldSortTitle, v))
}

// SortTitleHasSuffix applies the HasSuffix predicate on the "sort_title" field.
func SortTitleHasSuffix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasSuffix(FieldSortTitle, v))
}

// SortTitleIsNil applies the IsNil predicate on the "sort_title" field.
func SortTitleIsNil() predicate.Book {
	return predicate.Book(sql.FieldIsNull(FieldSortTitle))
}

// SortTitleNotNil applies the NotNil predicate on the "sort_title" field.
func SortTitleNotNil() predicate.Book {
	return predicate.Book(sql.FieldNotNull(FieldSortTitle))
}

// SortTitleEqualFold applies the EqualFold predicate on the "sort_title" field.
func SortTitleEqualFold(v string) predicate.Book {
	return predicate.Book(sql.FieldEqualFold(FieldSortTitle, v))
}

// SortTitleContainsFold applies the ContainsFold predicate on the "sort_title" field.
func SortTitleContainsFold(v string) predicate.Book {
	return predicate.Book(sql.FieldContainsFold(FieldSortTitle, v))
}

// ReleaseDateEQ applies the EQ predicate on the "release_date" field.
func ReleaseDateEQ(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldReleaseDate, v))
}

// ReleaseDateNEQ applies the NEQ predicate on the "release_date" field.
func ReleaseDateNEQ(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldReleaseDate, v))
}

// ReleaseDateIn applies the In predicate on the "release_date" field.
func ReleaseDateIn(vs ...time.Time) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldReleaseDate, vs...))
}

// ReleaseDateNotIn applies the NotIn predicate on the "release_date" field.
func ReleaseDateNotIn(vs ...time.Time) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldReleaseDate, vs...))
}

// ReleaseDateGT applies the GT predicate on the "release_date" field.
func ReleaseDateGT(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldReleaseDate, v))
}

// ReleaseDateGTE applies the GTE predicate on the "release_date" field.
func ReleaseDateGTE(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldReleaseDate, v))
}

// ReleaseDateLT applies the LT predicate on the "release_date" field.
func ReleaseDateLT(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldReleaseDate, v))
}

// ReleaseDateLTE applies the LTE predicate on the "release_date" field.
func ReleaseDateLTE(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldReleaseDate, v))
}

// ReleaseDateIsNil applies the IsNil predicate on the "release_date" field.
func ReleaseDateIsNil() predicate.Book {
	return predicate.Book(sql.FieldIsNull(FieldReleaseDate))
}

// ReleaseDateNotNil applies the NotNil predicate on the "release_date" field.
func ReleaseDateNotNil() predicate.Book {
	return predicate.Book(sql.FieldNotNull(FieldReleaseDate))
}

// OverviewEQ applies the EQ predicate on the "overview" field.
func OverviewEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldOverview, v))
}

// OverviewNEQ applies the NEQ predicate on the "overview" field.
func OverviewNEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldOverview, v))
}

// OverviewIn applies the In predicate on the "overview" field.
func OverviewIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldOverview, vs...))
}

// OverviewNotIn applies the NotIn predicate on the "overview" field.
func OverviewNotIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldOverview, vs...))
}

// OverviewGT applies the GT predicate on the "overview" field.
func OverviewGT(v string) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldOverview, v))
}

// OverviewGTE applies the GTE predicate on the "overview" field.
func OverviewGTE(v string) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldOverview, v))
}

// OverviewLT applies the LT predicate on the "overview" field.
func OverviewLT(v string) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldOverview, v))
}

// OverviewLTE applies the LTE predicate on the "overview" field.
func OverviewLTE(v string) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldOverview, v))
}

// OverviewContains applies the Contains predicate on the "overview" field.
func OverviewContains(v string) predicate.Book {
	return predicate.Book(sql.FieldContains(FieldOverview, v))
}

// OverviewHasPrefix applies the HasPrefix predicate on the "overview" field.
func OverviewHasPrefix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasPrefix(FieldOverview, v))
}

// OverviewHasSuffix applies the HasSuffix predicate on the "overview" field.
func OverviewHasSuffix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasSuffix(FieldOverview, v))
}

// OverviewIsNil applies the IsNil predicate on the "overview" field.
func OverviewIsNil() predicate.Book {
	return predicate.Book(sql.FieldIsNull(FieldOverview))
}

// OverviewNotNil applies the NotNil predicate on the "overview" field.
func OverviewNotNil() predicate.Book {
	return predicate.Book(sql.FieldNotNull(FieldOverview))
}

// OverviewEqualFold applies the EqualFold predicate on the "overview" field.
func OverviewEqualFold(v string) predicate.Book {
	return predicate.Book(sql.FieldEqualFold(FieldOverview, v))
}

// OverviewContainsFold applies the ContainsFold predicate on the "overview" field.
func OverviewContainsFold(v string) predicate.Book {
	return predicate.Book(sql.FieldContainsFold(FieldOverview, v))
}

// SeriesNameEQ applies the EQ predicate on the "series_name" field.
func SeriesNameEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldSeriesName, v))
}

// SeriesNameNEQ applies the NEQ predicate on the "series_name" field.
func SeriesNameNEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldSeriesName, v))
}

// SeriesNameIn applies the In predicate on the "series_name" field.
func SeriesNameIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldSeriesName, vs...))
}

// SeriesNameNotIn applies the NotIn predicate on the "series_name" field.
func SeriesNameNotIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldSeriesName, vs...))
}

// SeriesNameGT applies the GT predicate on the "series_name" field.
func SeriesNameGT(v string) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldSeriesName, v))
}

// SeriesNameGTE applies the GTE predicate on the "series_name" field.
func SeriesNameGTE(v string) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldSeriesName, v))
}

// SeriesNameLT applies the LT predicate on the "series_name" field.
func SeriesNameLT(v string) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldSeriesName, v))
}

// SeriesNameLTE applies the LTE predicate on the "series_name" field.
func SeriesNameLTE(v string) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldSeriesName, v))
}

// SeriesNameContains applies the Contains predicate on the "series_name" field.
func SeriesNameContains(v string) predicate.Book {
	return predicate.Book(sql.FieldContains(FieldSeriesName, v))
}

// SeriesNameHasPrefix applies the HasPrefix predicate on the "series_name" field.
func SeriesNameHasPrefix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasPrefix(FieldSeriesName, v))
}

// SeriesNameHasSuffix applies the HasSuffix predicate on the "series_name" field.
func SeriesNameHasSuffix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasSuffix(FieldSeriesName, v))
}

// SeriesNameIsNil applies the IsNil predicate on the "series_name" field.
func SeriesNameIsNil() predicate.Book {
	return predicate.Book(sql.FieldIsNull(FieldSeriesName))
}

// SeriesNameNotNil applies the NotNil predicate on the "series_name" field.
func SeriesNameNotNil() predicate.Book {
	return predicate.Book(sql.FieldNotNull(FieldSeriesName))
}

// SeriesNameEqualFold applies the EqualFold predicate on the "series_name" field.
func SeriesNameEqualFold(v string) predicate.Book {
	return predicate.Book(sql.FieldEqualFold(FieldSeriesName, v))
}

// SeriesNameContainsFold applies the ContainsFold predicate on the "series_name" field.
func SeriesNameContainsFold(v string) predicate.Book {
	return predicate.Book(sql.FieldContainsFold(FieldSeriesName, v))
}

// SeriesPositionEQ applies the EQ predicate on the "series_position" field.
func SeriesPositionEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldSeriesPosition, v))
}

// SeriesPositionNEQ applies the NEQ predicate on the "series_position" field.
func SeriesPositionNEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldSeriesPosition, v))
}

// SeriesPositionIn applies the In predicate on the "series_position" field.
func SeriesPositionIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldSeriesPosition, vs...))
}

// SeriesPositionNotIn applies the NotIn predicate on the "series_position" field.
func SeriesPositionNotIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldSeriesPosition, vs...))
}

// SeriesPositionGT applies the GT predicate on the "series_position" field.
func SeriesPositionGT(v string) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldSeriesPosition, v))
}

// SeriesPositionGTE applies the GTE predicate on the "series_position" field.
func SeriesPositionGTE(v string) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldSeriesPosition, v))
}

// SeriesPositionLT applies the LT predicate on the "series_position" field.
func SeriesPositionLT(v string) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldSeriesPosition, v))
}

// SeriesPositionLTE applies the LTE predicate on the "series_position" field.
func SeriesPositionLTE(v string) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldSeriesPosition, v))
}

// SeriesPositionContains applies the Contains predicate on the "series_position" field.
func SeriesPositionContains(v string) predicate.Book {
	return predicate.Book(sql.FieldContains(FieldSeriesPosition, v))
}

// SeriesPositionHasPrefix applies the HasPrefix predicate on the "series_position" field.
func SeriesPositionHasPrefix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasPrefix(FieldSeriesPosition, v))
}

// SeriesPositionHasSuffix applies the HasSuffix predicate on the "series_position" field.
func SeriesPositionHasSuffix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasSuffix(FieldSeriesPosition, v))
}

// SeriesPositionIsNil applies the IsNil predicate on the "series_position" field.
func SeriesPositionIsNil() predicate.Book {
	return predicate.Book(sql.FieldIsNull(FieldSeriesPosition))
}

// SeriesPositionNotNil applies the NotNil predicate on the "series_position" field.
func SeriesPositionNotNil() predicate.Book {
	return predicate.Book(sql.FieldNotNull(FieldSeriesPosition))
}

// SeriesPositionEqualFold applies the EqualFold predicate on the "series_position" field.
func SeriesPositionEqualFold(v string) predicate.Book {
	return predicate.Book(sql.FieldEqualFold(FieldSeriesPosition, v))
}

// SeriesPositionContainsFold applies the ContainsFold predicate on the "series_position" field.
func SeriesPositionContainsFold(v string) predicate.Book {
	return predicate.Book(sql.FieldContainsFold(FieldSeriesPosition, v))
}

// EbookMonitoredEQ applies the EQ predicate on the "ebook_monitored" field.
func EbookMonitoredEQ(v bool) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldEbookMonitored, v))
}

// EbookMonitoredNEQ applies the NEQ predicate on the "ebook_monitored" field.
func EbookMonitoredNEQ(v bool) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldEbookMonitored, v))
}

// EbookStatusEQ applies the EQ predicate on the "ebook_status" field.
func EbookStatusEQ(v EbookStatus) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldEbookStatus, v))
}

// EbookStatusNEQ applies the NEQ predicate on the "ebook_status" field.
func EbookStatusNEQ(v EbookStatus) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldEbookStatus, v))
}

// EbookStatusIn applies the In predicate on the "ebook_status" field.
func EbookStatusIn(vs ...EbookStatus) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldEbookStatus, vs...))
}

// EbookStatusNotIn applies the NotIn predicate on the "ebook_status" field.
func EbookStatusNotIn(vs ...EbookStatus) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldEbookStatus, vs...))
}

// EbookGrabFailuresEQ applies the EQ predicate on the "ebook_grab_failures" field.
func EbookGrabFailuresEQ(v uint8) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldEbookGrabFailures, v))
}

// EbookGrabFailuresNEQ applies the NEQ predicate on the "ebook_grab_failures" field.
func EbookGrabFailuresNEQ(v uint8) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldEbookGrabFailures, v))
}

// EbookGrabFailuresIn applies the In predicate on the "ebook_grab_failures" field.
func EbookGrabFailuresIn(vs ...uint8) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldEbookGrabFailures, vs...))
}

// EbookGrabFailuresNotIn applies the NotIn predicate on the "ebook_grab_failures" field.
func EbookGrabFailuresNotIn(vs ...uint8) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldEbookGrabFailures, vs...))
}

// EbookGrabFailuresGT applies the GT predicate on the "ebook_grab_failures" field.
func EbookGrabFailuresGT(v uint8) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldEbookGrabFailures, v))
}

// EbookGrabFailuresGTE applies the GTE predicate on the "ebook_grab_failures" field.
func EbookGrabFailuresGTE(v uint8) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldEbookGrabFailures, v))
}

// EbookGrabFailuresLT applies the LT predicate on the "ebook_grab_failures" field.
func EbookGrabFailuresLT(v uint8) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldEbookGrabFailures, v))
}

// EbookGrabFailuresLTE applies the LTE predicate on the "ebook_grab_failures" field.
func EbookGrabFailuresLTE(v uint8) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldEbookGrabFailures, v))
}

// EbookLastSearchAtEQ applies the EQ predicate on the "ebook_last_search_at" field.
func EbookLastSearchAtEQ(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldEbookLastSearchAt, v))
}

// EbookLastSearchAtNEQ applies the NEQ predicate on the "ebook_last_search_at" field.
func EbookLastSearchAtNEQ(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldEbookLastSearchAt, v))
}

// EbookLastSearchAtIn applies the In predicate on the "ebook_last_search_at" field.
func EbookLastSearchAtIn(vs ...time.Time) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldEbookLastSearchAt, vs...))
}

// EbookLastSearchAtNotIn applies the NotIn predicate on the "ebook_last_search_at" field.
func EbookLastSearchAtNotIn(vs ...time.Time) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldEbookLastSearchAt, vs...))
}

// EbookLastSearchAtGT applies the GT predicate on the "ebook_last_search_at" field.
func EbookLastSearchAtGT(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldEbookLastSearchAt, v))
}

// EbookLastSearchAtGTE applies the GTE predicate on the "ebook_last_search_at" field.
func EbookLastSearchAtGTE(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldEbookLastSearchAt, v))
}

// EbookLastSearchAtLT applies the LT predicate on the "ebook_last_search_at" field.
func EbookLastSearchAtLT(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldEbookLastSearchAt, v))
}

// EbookLastSearchAtLTE applies the LTE predicate on the "ebook_last_search_at" field.
func EbookLastSearchAtLTE(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldEbookLastSearchAt, v))
}

// EbookLastSearchAtIsNil applies the IsNil predicate on the "ebook_last_search_at" field.
func EbookLastSearchAtIsNil() predicate.Book {
	return predicate.Book(sql.FieldIsNull(FieldEbookLastSearchAt))
}

// EbookLastSearchAtNotNil applies the NotNil predicate on the "ebook_last_search_at" field.
func EbookLastSearchAtNotNil() predicate.Book {
	return predicate.Book(sql.FieldNotNull(FieldEbookLastSearchAt))
}

// AudiobookMonitoredEQ applies the EQ predicate on the "audiobook_monitored" field.
func AudiobookMonitoredEQ(v bool) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldAudiobookMonitored, v))
}

// AudiobookMonitoredNEQ applies the NEQ predicate on the "audiobook_monitored" field.
func AudiobookMonitoredNEQ(v bool) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldAudiobookMonitored, v))
}

// AudiobookStatusEQ applies the EQ predicate on the "audiobook_status" field.
func AudiobookStatusEQ(v AudiobookStatus) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldAudiobookStatus, v))
}

// AudiobookStatusNEQ applies the NEQ predicate on the "audiobook_status" field.
func AudiobookStatusNEQ(v AudiobookStatus) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldAudiobookStatus, v))
}

// AudiobookStatusIn applies the In predicate on the "audiobook_status" field.
func AudiobookStatusIn(vs ...AudiobookStatus) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldAudiobookStatus, vs...))
}

// AudiobookStatusNotIn applies the NotIn predicate on the "audiobook_status" field.
func AudiobookStatusNotIn(vs ...AudiobookStatus) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldAudiobookStatus, vs...))
}

// AudiobookGrabFailuresEQ applies the EQ predicate on the "audiobook_grab_failures" field.
func AudiobookGrabFailuresEQ(v uint8) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldAudiobookGrabFailures, v))
}

// AudiobookGrabFailuresNEQ applies the NEQ predicate on the "audiobook_grab_failures" field.
func AudiobookGrabFailuresNEQ(v uint8) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldAudiobookGrabFailures, v))
}

// AudiobookGrabFailuresIn applies the In predicate on the "audiobook_grab_failures" field.
func AudiobookGrabFailuresIn(vs ...uint8) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldAudiobookGrabFailures, vs...))
}

// AudiobookGrabFailuresNotIn applies the NotIn predicate on the "audiobook_grab_failures" field.
func AudiobookGrabFailuresNotIn(vs ...uint8) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldAudiobookGrabFailures, vs...))
}

// AudiobookGrabFailuresGT applies the GT predicate on the "audiobook_grab_failures" field.
func AudiobookGrabFailuresGT(v uint8) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldAudiobookGrabFailures, v))
}

// AudiobookGrabFailuresGTE applies the GTE predicate on the "audiobook_grab_failures" field.
func AudiobookGrabFailuresGTE(v uint8) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldAudiobookGrabFailures, v))
}

// AudiobookGrabFailuresLT applies the LT predicate on the "audiobook_grab_failures" field.
func AudiobookGrabFailuresLT(v uint8) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldAudiobookGrabFailures, v))
}

// AudiobookGrabFailuresLTE applies the LTE predicate on the "audiobook_grab_failures" field.
func AudiobookGrabFailuresLTE(v uint8) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldAudiobookGrabFailures, v))
}

// AudiobookLastSearchAtEQ applies the EQ predicate on the "audiobook_last_search_at" field.
func AudiobookLastSearchAtEQ(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldAudiobookLastSearchAt, v))
}

// AudiobookLastSearchAtNEQ applies the NEQ predicate on the "audiobook_last_search_at" field.
func AudiobookLastSearchAtNEQ(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldAudiobookLastSearchAt, v))
}

// AudiobookLastSearchAtIn applies the In predicate on the "audiobook_last_search_at" field.
func AudiobookLastSearchAtIn(vs ...time.Time) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldAudiobookLastSearchAt, vs...))
}

// AudiobookLastSearchAtNotIn applies the NotIn predicate on the "audiobook_last_search_at" field.
func AudiobookLastSearchAtNotIn(vs ...time.Time) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldAudiobookLastSearchAt, vs...))
}

// AudiobookLastSearchAtGT applies the GT predicate on the "audiobook_last_search_at" field.
func AudiobookLastSearchAtGT(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldAudiobookLastSearchAt, v))
}

// AudiobookLastSearchAtGTE applies the GTE predicate on the "audiobook_last_search_at" field.
func AudiobookLastSearchAtGTE(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldAudiobookLastSearchAt, v))
}

// AudiobookLastSearchAtLT applies the LT predicate on the "audiobook_last_search_at" field.
func AudiobookLastSearchAtLT(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldAudiobookLastSearchAt, v))
}

// AudiobookLastSearchAtLTE applies the LTE predicate on the "audiobook_last_search_at" field.
func AudiobookLastSearchAtLTE(v time.Time) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldAudiobookLastSearchAt, v))
}

// AudiobookLastSearchAtIsNil applies the IsNil predicate on the "audiobook_last_search_at" field.
func AudiobookLastSearchAtIsNil() predicate.Book {
	return predicate.Book(sql.FieldIsNull(FieldAudiobookLastSearchAt))
}

// AudiobookLastSearchAtNotNil applies the NotNil predicate on the "audiobook_last_search_at" field.
func AudiobookLastSearchAtNotNil() predicate.Book {
	return predicate.Book(sql.FieldNotNull(FieldAudiobookLastSearchAt))
}

// HasAuthor applies the HasEdge predicate on the "author" edge.
func HasAuthor() predicate.Book {
	return predicate.Book(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorWith applies the HasEdge predicate on the "author" edge with a given conditions (other predicates).
func HasAuthorWith(preds ...predicate.Author) predicate.Book {
	return predicate.Book(func(s *sql.Selector) {
		step := newAuthorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMediaFiles applies the HasEdge predicate on the "media_files" edge.
func HasMediaFiles() predicate.Book {
	return predicate.Book(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MediaFilesTable, MediaFilesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMediaFilesWith applies the HasEdge predicate on the "media_files" edge with a given conditions (other predicates).
func HasMediaFilesWith(preds ...predicate.MediaFile) predicate.Book {
	return predicate.Book(func(s *sql.Selector) {
		step := newMediaFilesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDownloadRecords applies the HasEdge predicate on the "download_records" edge.
func HasDownloadRecords() predicate.Book {
	return predicate.Book(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DownloadRecordsTable, DownloadRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDownloadRecordsWith applies the HasEdge predicate on the "download_records" edge with a given conditions (other predicates).
func HasDownloadRecordsWith(preds ...predicate.DownloadRecord) predicate.Book {
	return predicate.Book(func(s *sql.Selector) {
		step := newDownloadRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Book) predicate.Book {
	return predicate.Book(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Book) predicate.Book {
	return predicate.Book(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Book) predicate.Book {
	return predicate.Book(sql.NotPredicates(p))
}
