package db

import (
	"context"
	"database/sql"
	"embed"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/golang-migrate/migrate/v4"
	"github.com/golang-migrate/migrate/v4/database/sqlite"
	"github.com/golang-migrate/migrate/v4/source/iofs"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// runMigrations applies pending golang-migrate files (generated by
// ent/migrate/main.go) to db. Versioned migration state is tracked in the
// schema_migrations table that golang-migrate manages.
// Reports what it did, on both sides: a slow migration on a large database
// (a WAL checkpoint stalling behind a busy disk) was indistinguishable from a
// hung boot, since nothing said migrations had started, finished, or moved the
// schema version at all.
func runMigrations(ctx context.Context, db *sql.DB) error {
	src, err := iofs.New(migrationsFS, "migrations")
	if err != nil {
		return fmt.Errorf("migration source: %w", err)
	}
	drv, err := sqlite.WithInstance(db, &sqlite.Config{})
	if err != nil {
		return fmt.Errorf("migration driver: %w", err)
	}
	m, err := migrate.NewWithInstance("iofs", src, "sqlite", drv)
	if err != nil {
		return fmt.Errorf("migrate init: %w", err)
	}

	before, _, _ := m.Version()
	slog.InfoContext(ctx, "applying database migrations",
		"schema.version_before", before)

	started := time.Now()
	err = m.Up()
	elapsed := time.Since(started)
	if err != nil && !errors.Is(err, migrate.ErrNoChange) {
		slog.ErrorContext(ctx, "database migrations failed",
			"schema.version_before", before,
			"duration_ms", elapsed.Milliseconds(),
			"error", err)
		return fmt.Errorf("migrate up: %w", err)
	}

	after, dirty, _ := m.Version()
	slog.InfoContext(ctx, "database migrations applied",
		"schema.version_before", before,
		"schema.version", after,
		"schema.dirty", dirty,
		"duration_ms", elapsed.Milliseconds())
	return nil
}
